### ISSUE TITLE
Update installer script

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#1006]
Linux kernel used with TempestaFW was updated to version 4.14.32. Installer script must also be updated.
Probably a new option need to be introduced for the installer: target version: 0.5 or 0.6. 

#762 and #786 provide more requirements for the installer, maybe some of them can be made in current release.

Please also note issue in tempesta-tech/linux-packages#1

**Comment by krizhanovsky** [comment]
It's also good to run dry run script (#1304) on finishing install process.

**Comment by krizhanovsky** [comment]
The script must be updated for Debian 10. Debian 8 can be safely removed, probably as well as Debian 9.

**Comment by ikoveshnikov** [comment]
While I was moving CI from one server to another, I realised that it relatively easy to make scripts for automatic VM creation for evaluation|development purposes:
```
virt-builder debian-9 -o debian-9.qcow2 --format qcow2 \
   --size 15G --root-password file:password --hostname tempesta  \
   --update --firstboot-command 'dpkg-reconfigure openssh-server'
virt-install --name debian-9 --ram 4096 \
   --disk path=debian-9.qcow2,format=qcow2,cache=writeback \
   --nographics --os-variant debian9 --import
```
A `libguestfs` package provides `virt-builder` tool. After Tempeta packages will be available via some package hosting (#762 ) - it will become even more easy, since just a small `install` argument will be required for that script.

**Comment by krizhanovsky** [comment]
Let's move the packages and the docs to Ubuntu 20 as using the same 5.10 kernel.

**Comment by krizhanovsky** [comment]
Done https://github.com/tempesta-tech/tempesta/pull/1581
