### ISSUE TITLE
backup configuration doesn't work properly

### ISSUE THREAD

**Issue by vladtcvs** [tempesta-tech/tempesta#1025]
Tempesta config

```
srv_group primary {
sched ratio;
server 127.0.0.1:8000 conns_n=1;

}
srv_group backup {
sched ratio;
server 127.0.0.1:8001 conns_n=1;

}
vhost primary {
proxy_pass primary;
}
vhost backup {
proxy_pass backup;
}
cache 0;

sched_http_rules {
  match primary * * * backup=backup;
}
```

Start nginx on 8001 port only.

`curl -v http://127.0.0.1` - receive 502 error and dmesg message

`[tempesta] Warning: request dropped: processing error, status 502: ::ffff:7f00:1`

If we start nginx on 8000 or on both 8000 and 8001, tempesta returns correct answer

**Comment by ikoveshnikov** [comment]
Not a bug. `backup` attribute was moved from `sched_http_rules` to `proxy_pass` directive recently. I've created PR #1026 to raise parsing error for this case.
