### ISSUE TITLE
[Frang] Optimize blocking of malitious clients

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#1042]
[Recent research](https://blog.cloudflare.com/how-to-drop-10-million-packets/) shows that filtering single IP address can be ten times more efficient with XDP than with iptables. That can be handy to mitigate DDoS attacks.

**Comment by krizhanovsky** [comment]
We already have #934 to replace our `filter.c` by nftables, XDP/BPF integrations also should be done in the same issue, so I close this one as a duplicate.
