### ISSUE TITLE
XDP DDoS mitigation and L3-L4 LB

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1048]
**depends on:** https://github.com/tempesta-tech/tempesta/issues/1808

While Tempesta FW addresses L7 DDoS attacks and load balancing, low level flooding attacks also must be filtered out. New set of configuration directives must be added to `tempesta_fw.conf` and `tempesta.sh` must generate and load appropriate XDP program.

This feature is required for installation and switching on Tempesta FW under DDoS attack with only purpose to mitigate the attack. The scenario is crucial and considers multiple aspects, e.g. quick cache migration (see [Web-content management tool task, #528](https://github.com/tempesta-tech/tempesta/issues/528)).

The implementation must satisfy [RFC 4987, TCP SYN Flooding Attacks and Common Mitigations](https://tools.ietf.org/html/rfc4987).

It's good to use [XDP Acceleration Using NIC Metadata](https://www.youtube.com/watch?v=BzHiEGzFJC0) to get more performance.

See [SIGCOMM'18 Accelerating Linux Security with eBPF iptables](https://www.researchgate.net/publication/326918200_Accelerating_Linux_Security_with_eBPF_iptables) and [LPC2018 - eBPF / XDP Based Firewall and Packet Filtering](https://www.youtube.com/watch?v=XpBzEq1MwI8) for bit data structures to implement the matching tables.

[XDP based DDoS Mitigation](https://netdevconf.org/0x13/session.html?talk-XDP-based-DDoS-mitigation) describes quite interesting techniques for XDP filtration: `perf` event sampling, single-binary distribution, using `tcpdump` rules for monitoring & debugging. The work also discusses the problems with lock-free rate limiting and filtration of encrypted QUIC traffic.

Also consider [Issuing SYN cookies in XDP](https://netdevconf.info/0x14/session.html?talk-issuing-SYN-cookies-in-XDP) .

P4 also has some capabilities in matching and blocking packets, but need to research whether at least simple rate limits can be implemented using P4 in NIC.

References:
* https://github.com/xdp-project/xdp-tools

**Comment by krizhanovsky** [comment]
Low level (volumetric) DDoS is crucial to for the full solution.

**Comment by ultperf** [comment]
@krizhanovskycan u update tempesta fw github frontpage to mention if tempesta is going to be ebpf compatible because of the kernel patch or caveats / limitations to look out for?

rationale, i've written ebpf programs for ddos etc. but 
i am waiting for http2 of tempesta and hoping my ebpf will run on it if i do use tempesta fw.

sorry for my newbie question but do hope to understand roadmap of this. totally understand tempesta is about security and speed but with kernel patch, not sure if the direction will take ebpf into consideration for customized ebpf solutions.

**Comment by krizhanovsky** [comment]
Hi @ultperf ,

we still didn't implement any Tempesta FW calls, which can be used from BPF programs, so it's too early to write about eBPF on the front page.

I'd invite you to comment https://github.com/tempesta-tech/tempesta/issues/102 on what you need or going to use in your BPF programs. E.g. which HTTP message fields you need access from eBPF, which matching and modification functions and so on. These information will be helpful for us to design the feature.

https://github.com/tempesta-tech/tempesta/issues/102 is a crucial feature for us, but we aren't able to take it into the scope of the current milestone. I hope we'll take it for the next one.

**Comment by ultperf** [comment]
@krizhanovsky ok i've answered

**Comment by krizhanovsky** [comment]
Is under development in a closed repository
