### ISSUE TITLE
Linux 5.10 LTS: migrate & fix _unused attribute is used by pfmemalloc

### ISSUE THREAD

**Issue by sempervictus** [tempesta-tech/tempesta#1049]
Upstream [commit](https://github.com/torvalds/linux/commit/6403b54a4f7e097842d7814fe20124b32e5d3e1d) changes skbuff.h to make use of the last slot in a u8 bitfield of the very conditionally defined sk_buff struct. Tempesta was using this bit space for the skb_page bit, and is now in conflict with the pfmemalloc bit.

**Comment by krizhanovsky** [comment]
@sempervictus thank you for the issue report!

We're using longterm kernels, [linux 4.14](https://github.com/tempesta-tech/linux-4.14.32-tfw) now, but we'll need to fix the issues on migration to the next longterm kernel.

**Comment by krizhanovsky** [comment]
Oh, I see. Then we'll need to fix this before the Beta and move to the latest 4.14.

**Comment by sempervictus** [comment]
I peeked at the kernel repo, looks like its still at the same revision. Any chance you guys could update the kernel side of things to 4.14.78?

**Comment by krizhanovsky** [comment]
Hi @sempervictus ,

yes, we're going to move to newer kernel version, probably higher than 4.14, closer to the [Beta](https://github.com/tempesta-tech/tempesta/milestone/7) - for now, during the alpha stage, we're concentrating on Tempesta bugs and kernel updates, e.g. for #614 .

Do you need the latest 4.14 kernel ?

**Comment by sempervictus** [comment]
Keeping the kernel tree up to date would probably help outside testers/tinkerers, and stabilize implementation hooks somewhat. We generally built against stable-current, and conflicts like this one prevent automated build testing (pipeline dies at the merge failure, requires manual intervention, etc).

**Comment by krizhanovsky** [comment]
Makes sense. Unfortunately, currently we're overloaded with features development and bug fixes and are not going to move to a newer (either 4.14 with higher patchlevel or a new longterm) kernel. Meantime, if you make a pull request for the issue, we'll be happy to apply the patch to master.

**Comment by krizhanovsky** [comment]
[It seems](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html-single/8.0_beta_release_notes/#overview) the next longterm kernel will be released soon and it will be 4.18. 

We release the Beta for 4.14 and will move to 4.18 shortly after that. So I move the task to 1.1 milestone and require full porting to stable 4.18.

**Comment by ikoveshnikov** [comment]
A lot of commits between 4.14.32 (Tempesta's current) and  4.14.y branch of upstream kernel are targeted to fix new warnings generated by gcc-8.1. Most of the warnings are 
```
warning: objtool: tfw_vhost_new()+0x9e: sibling call from callable instruction with modified stack frame
```

The same happens with Tempesta code itself when trying it to build it with gcc-8.1. A lot of such warnings are generated and need to be fixed.

**Comment by sempervictus** [comment]
Given that 4.14.101 is now out, and gcc 8.3 around the corner, any chance of seeing the kernel repo updated to 4.14 current?

**Comment by krizhanovsky** [comment]
Since Debian 10 is released with 4.19, I move the task to 0.8. I believe we should move out from the practice to keep separate repos for each kernel version and just use tags from the Linux tree and apply our patches on top of it.

**Comment by sempervictus** [comment]
@krizhanovsky: with 5.4 out and marked stable, any chance we'll see a 5.4 branch any time soon? Test-grade setups are starting to use it now, with the expectation that it'll someday be the production kernel on systems, and Tempesta will definitely need to be tested by folks looking to optimize their HTTP proxy infrastructure.

**Comment by krizhanovsky** [comment]
Hi @sempervictus ,

the task to move to a newer kernel is one of the top priority tasks for the next milestone. At the moment, we're focusing on to deliver HTTP/2 and fast TLS handshakes in current (0.7) milestone.

I'm wondering if there is a business need from your side to have Tempesta FW working on a newer kernel? Could you please drop me a short message to ak@tempesta-tech.com ?

**Comment by sempervictus** [comment]
Commercial, no - businesses fear kernel-level tools :). That said, I personally think it has merit, but to show value sufficient for businesses to warrant testing past their fears, itd need to line up with their test platforms. The reused field issue I posted prior is a good example of why: out of tree code gets out of sync with mainline, and turns into instant tech debt for anyone using it. Its the minimum critical mass of open source work problem. Will keep an eye on the project and start trying to build for testing once you're on 5.4. Thanks as always

**Comment by krizhanovsky** [comment]
Debian 10 uses newer kernel, so to be able to deploy on Debian 10 we need a newer kernel, so 0.7 must be released with the newer kernel.

**Comment by krizhanovsky** [comment]
Also got `objtool` warning `sibling call from callable instruction with....` for `mpi_sub_x86_64()+0x6c`

**Comment by sempervictus** [comment]
According to the [gentoo thread](https://forums.gentoo.org/viewtopic-t-1075862.html), need to use ld.bfd and `CONFIG_STACK_VALIDATION=no`. Since we use grsec internally, this sort of stuff is handled for us by a professional upstream (vs the gratis Linux upstream which comparably is the wild west in terms of testing and safety), but on our `linux-hardened` branch (not all customers license grsecurity), we've been using the guess unwinder for ages and managed to stumble over a bunch of these problems when they hit since it seems to have something to do with how stack traces are composed.
Whats the build chain in use and the kernel version being built?
I'm hoping to potentially integrate VyOS with this codebase in the future to provide a rolling testbed which we can throw into real workloads. However since we're a security outfit, we'd try to get at least some defensive standoff built in from the linux-hardened branch, and internally with grsec which should help find a _lot_ of bugs (it doesnt like type confusion, and will nuke out on null derefs, invalid accesses across boundaries, or even out of order execution if RAP is in play). So selfishly, i'd prefer it be 5.4 since we have our codebase currently up to snuff with that LTS, but should be able to work off of any LTS once we're close enough to "game time" for functional testing in more than just a dry lab.
Thanks for pushing this forward.

**Comment by krizhanovsky** [comment]
Hi @sempervictus ,

> Whats the build chain in use and the kernel version being built?

Probably I didn't get your question. At the moment we build our current 4.14.32 on Debian 9/10 and VM or hardware servers with requirements https://github.com/tempesta-tech/tempesta/wiki/Requirements#common-requirements

5.4 sound quite reasonable and the most likely next kernel for us.

Could you please describe more your use case? Which build requirements (e.g. configuration options for the kernel) and target architectures and distributions?

**Comment by sempervictus** [comment]
@krizhanovsky: sorry, build chain meaning which version of GCC or compiler/linker/etc. If you're building using the packages provided by a distribution release, it'll be whatever toolchain that distribution has (GCC 8.3 IIRC for deb10). We use Arch as a basis for a lot of what we build, which doesn't have releases per se, its a rolling distribution, so we're on GCC 10.1 now (part of the reason we're using Arch actually is the access to current-edition compiler toolchain).
Our use cases are "anything clients ask us to build" - we're a tailored engineering & security outfit, run a couple private clouds, do everything from adversarial assessment to exascale infrastructure design and deployment. Scale-out systems relying on HTTP APIs could really benefit from this work, as could WAF technologies and so on, so i'm sort of keeping an eye on the project and waiting for a time when it won't require massive effort on my part to start building and testing it. Distribution-wise, i can currently see this going into our own internal Arch setup, into VyOS as that already handles a number of network services in a debian environment, and pretty much anywhere in general compute Linux having to deal with TLS termination and HTTP pre-processing (to include LB and basic proxying).

**Comment by krizhanovsky** [comment]
@sempervictus ,

thanks for the clarifications.

At the moment we build Tempesta FW with GCC 6. GCC of 8 and higher versions still aren't supported. This must be fixed in context for the current task.

**Comment by krizhanovsky** [comment]
Done in commits

https://github.com/tempesta-tech/tempesta/commit/bb6aff888d53742b5041353fa71e94a63762fa00
https://github.com/tempesta-tech/tempesta/commit/d4778d1b15ec78252f24386d4f770f65580c6868
https://github.com/tempesta-tech/tempesta/commit/07880e2571e48684bb81699266df6d4028e8a933
https://github.com/tempesta-tech/tempesta/commit/c5197d920b28959f0fd9842b7705ef3c0597868e
https://github.com/tempesta-tech/tempesta/commit/2e1e824e413a1e98a5f85c9f6888abdfe6f66c9f
https://github.com/tempesta-tech/tempesta/commit/f4a3a9c61e0774891007bc824937b4fa77813a8c
https://github.com/tempesta-tech/tempesta/commit/dcfa7773a83af635b858f1e6af4b15feb3ad3765
