### ISSUE TITLE
Cut of preceding CRLFs before forward message to backend server.

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#1061]
from the [RFC](https://tools.ietf.org/html/rfc7230#section-3.5):
> In the interest of robustness, a server that is expecting to receive
   and parse a request-line SHOULD ignore at least one empty line (CRLF)
   received prior to the request-line.

Tempesta honours the requirement. But CRLF preceding to the message is actually treated as message part, and an HTTP message is forwarded to destination with all the preceding CRLFs. Bot can feed us CRLF spaghetti before send us a request. All CRLFs will be stored in Tempesta buffers and will be forwarded to backend server. There is no existing Frang limit to restrict such behaviour.

Another possible problems - message parsing robustness of backend server. It's an optional requirement for HTTP servers. E.g. Nginx and Tempesta are tolerant to tonns of preceding CRLFs, but not sure for others.

Need to add an appropriate functional test for this.

**Comment by krizhanovsky** [comment]
I think we should allow only one preceding CRLF and block the "tons of CRLFs".

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky  The tests specified here are in #195
