### ISSUE TITLE
Broken items sequence in the work queue w/ backlog

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1066]
Currently the backlog uses `list_add()` for insertion with `list_first_entry()` for eviction, so the backlog operates in LIFO manner instead of intetional LIFO.

Please backport the issue to 0.5-alpha release. @ikoveshnikov please prepare a new release after that.

**Comment by aleksostapenko** [comment]
Fixed in context of https://github.com/tempesta-tech/tempesta/pull/1072.
