### ISSUE TITLE
For Mellanox NIC the tfw_lib.sh script does not assign RX queues to CPUs

### ISSUE THREAD

**Issue by aleksostapenko** [tempesta-tech/tempesta#1073]
This place https://github.com/tempesta-tech/tempesta/blob/871200e5c64c1016dfe4891f365bc78d910cb97c/scripts/tfw_lib.sh#L59 does not work with the Melanox card: in `/proc/interrupts`, its queues are named in driver-like style (not like the logical interface), so the next cycle in script is completely skipped and only eight queues remain (despite the previous `ethtool -L` command) with eight IRQs and their `smp_affinity` is not changed (except for periodic changes from `irqbalance`). Although all created 128 queues can be found in `/sys/class/net/enp7s0 /queues/` but only 8 remain assigned to CPUs. The interrupt numbers for the script can be found in `/sys/class/net/enp7s0/device/msi_irqs/`, but only eight queues/IRQs exist in that directory and have been assigned to CPUs; the rest of created queues, apparently, remain without IRQ numbers.

**Comment by aleksostapenko** [comment]
It is also needed to avoid the setting RPS for `loopback` interface in `tfw_lib.sh` script, since this is not hardware interface and traffic flows are distributed evenly between CPUs for it, while RPS just add unnecessary overhead in this case (traffic redistribution, IPIs introduction etc.).

**Comment by krizhanovsky** [comment]
Probably it has sense to configure RFS for the loopback interface if we see a backend configured on 127.0.0.0/8.

**Comment by aleksostapenko** [comment]
Yes - agree with that.
However, 30-seconds benchmark (from https://github.com/tempesta-tech/tempesta/issues/695#issuecomment-426193629) on bare metal and VM, with RFS on loopback interface - does not show difference in `requests per second` value. It seems that deeper investigation is needed here, to discover detailed impact of RPS/RFS on Tempesta FW perfomance in case of loopback interface. Among possible causes of current behaviour could be: establihsing all backend connections in one-time manner, during start of Tempesta FW; persistent pinning of web-server processes per CPU).

**Comment by krizhanovsky** [comment]
Yeah, we also have [UNIX sockets #390](https://github.com/tempesta-tech/tempesta/issues/390) issue for better loopback performance. Maybe it makes sense to postpone the RFS investigation and pinning of web-server processes to that time.

**Comment by aleksostapenko** [comment]
Agree - added comment into https://github.com/tempesta-tech/tempesta/issues/390.

**Comment by aleksostapenko** [comment]
The cause of specified above interrupts-rings mismatch for Mellanox NIC is that the `mlx4` driver has two-tier rings architecture. The upper layer (so called `Event Queues`) is configured during driver loading: in situation with MSI/MSI-X interrupts enabled (case under consideration) - the count of EQs is determined as count of system CPUs (but not more then 64, and not more than MSI count which PCI bus can provide); one interrupt vector and one CPU (via affinity mask) are allotted for each EQ. The lower level (`Completion Queues`) is configured during interface enabling or via `ethtool` operations: e.g. in case of new queues/channels/rings count specification - each created ring (from specified total amount) is pinned to separate CQ, so count of rings is equal to count of CQs, which in turn are evenly distributed between existing EQs; if CQs count is more than system CPUs (i.e. amount of allotted interrupts), then each EQ service several CQs, generating interrupts for pinned rings.
So, as a result, if we'll specify 128 rx queues (via `ethtool -L` command) on system with 8 CPUs and with MSI/MSI-X support - then, in general case, the traffic will be processed by 128 rings ('ethtool -S' command shows evenly distribution of processed packets and bytes among all 128 queues) and will be passed to one of eight EQs, which generate interrupt with assigned vector (one of eight allotted) for specific CPU.
