### ISSUE TITLE
Make documentation more friendly for new users

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#1078]
Configuration file format is not going to be stabilised until 1.0 or higher versions, but our wiki pages can fit only master release. We need to update the documentation and add the following:
- [ ] Add 'Available from: VERSION' to all directives to indicate which minimal version must be used for the directive. E.g. directive `vhost` was introduced in 0.6 release, but not accessible in 0.5 release. 
- [ ] Deprecated directives and behaviour. As long as some directives are added, others are removed. E.g. `http_sched_rules` directive is deprecated and replaced by `http_chain` in 0.6 release.
- [ ] Specify the scope for every directive. E.g. `cache_bypass` may be listed out of any directive blocks, inside `vhost` block and inside `location` block.
- [ ] Add configuration examples for common presets or common use cases for every directive.  Especially implicit diractives.

- [ ] Move to per-release documentation if documentation is too complicated due to tons of new and deprecated directives, too different use cases and it's worth to form unique documentation for every release. Exact implementation is TBD

**Comment by krizhanovsky** [comment]
This is unrealistic to rework the whole wiki at once. Instead I added the documentation guidelines to the Wiki https://github.com/tempesta-tech/tempesta/wiki/Development-Guidelines#documentation, so let's follow the guidelines for the new directives.
