### ISSUE TITLE
Incorrect calculation of sticky cookie length

### ISSUE THREAD

**Issue by aleksostapenko** [tempesta-tech/tempesta#1086]
In fact there are two problems:
1. Actually, wrong calculation for sticky cookie - of length and chunks count - here https://github.com/tempesta-tech/tempesta/blob/9d1a39311f678f8dd197438c47a27f9346720965/tempesta_fw/str.c#L153
2. Misbehavior during detection of invalid length of sticky cookie (response with just `0` cookie value is send to client, in case of cookie bad length) - here https://github.com/tempesta-tech/tempesta/blob/9d1a39311f678f8dd197438c47a27f9346720965/tempesta_fw/http_sess.c#L699 the correct behavior in this case - is to generate valid cookie and insert it into response like in other similar cases.

Also, backport to `0.5` for fixes of this issue is needed.

Besides, since these bugs are quite old and had been discovered only via HTTP requests splitted into several TCP segments - functional tests with splitted requests behavior should be implemented for verification of this and similar cases.

**Comment by i-rinat** [comment]
(fix to the master branch: https://github.com/tempesta-tech/tempesta/pull/1088)

**Comment by i-rinat** [comment]
(fix backport to the `release-0.5` branch: https://github.com/tempesta-tech/tempesta/pull/1090)

**Comment by i-rinat** [comment]
(additional test for the cookie parser: https://github.com/tempesta-tech/tempesta/pull/1092, https://github.com/tempesta-tech/tempesta/pull/1093)
