### ISSUE TITLE
Per-vhost ratelimits

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1107]
Now rate limits can be cofigured [per-vhost](https://github.com/tempesta-tech/tempesta/issues/688) - please describe this in [HTTP security](https://github.com/tempesta-tech/tempesta/wiki/HTTP-security#frang-security-limits-enforcing-module) wiki (now it states only that there is specific configuration section) and [vhosts](https://github.com/tempesta-tech/tempesta/wiki/Virtual-hosts-and-locations) wiki (now it doesn't mention rate limits at all).

**Comment by aleksostapenko** [comment]
Done.
