### ISSUE TITLE
Case insensitivity collateral damage in HTTP parser

### ISSUE THREAD

**Issue by i-rinat** [tempesta-tech/tempesta#1121]
**1. \x1a instead of \x3a**
To speed-up case-insensitive comparison in HTTP parser a trick is used in `C4_INT_LCM()` and `C8_INT_LCM()` macros: each byte is OR'red with 0x20. That maps all uppercase letters to lowercase, A to a, B to b, and so on. It's safe to do so with letters, but for other characters it may lead to recognizing something else as a desired character.

For example, when searching for `Host:` string, we do:
```c
&& C4_INT_LCM(p + 1, 'o', 's', 't', ':')
```
That matches both `ost:` and `ost\x1a`, as `0x1a | 0x20` equals to `0x3a`, which corresponds to `:`.

To fix that, ensure that all single-character parameters of `C4_INT_LCM` and `C8_INT_LCM` are lowercase letters. Also, check all occurrences of `TFW_LC_INT`, `TFW_LC_LONG`, `TFW_CHAR4_INT`, `TFW_CHAR8_INT`, `TFW_P2LCINT` to be sure.

**2. Case sensitivity**
Check case sensitivity of header field names. At the time of writing, there is an issue with at least "`Server`".

**3. Unit-test for case insensitivity**
It would be nice to have a unit-test for all upper-case variations of recognized header field names.

(code version: ac3aebae3378310f6ee883bff844eeb45498846b)

**Comment by krizhanovsky** [comment]
Probably good to do with #695
