### ISSUE TITLE
[Parser] Incorrect move in 'End of Term` state right after TRY_STR macro was used

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#1128]
All over the code TRY_STR macro matches only prefix of the term and moves parser to End of Term state. If next character is allowed token symbol, token delimiter is ignored.

It's more easy to show the error on example, let it be [__req_parse_accept()](https://github.com/tempesta-tech/tempesta/blob/cac94130f4a47060221dc34e24c6d42750b21db4/tempesta_fw/http_parser.c#L1936).

At some stage we match current token `text/htmlbla-bla-bla` with known token pattern. It matches, we set the flag and move to EndOfTerm (`I_EoT`) state:
https://github.com/tempesta-tech/tempesta/blob/cac94130f4a47060221dc34e24c6d42750b21db4/tempesta_fw/http_parser.c#L1935-L1938

At `I_EoT` state the next character is checked, it's token character, so we move to `Req_I_Accept` state back again. Now we try to match `bla-bla-bla` with known patterns and move to state `Req_I_AcceptOther` and continue parsing.

The original expression `text/htmlbla-bla-bla` shouldn't be parsed as known pattern at all. But it was parsed as combination of two patterns `text/html` and `bla-bla-bla`, which is not valid parsing.

The same error happens whenever `TRY_STR` macro is used. E.g. the patch as follows _must_ fail the unit test `TEST(http_parser, fills_hdr_tbl_for_req)`, but it passes.
```diff
--- a/tempesta_fw/t/unit/test_http_parser.c
+++ b/tempesta_fw/t/unit/test_http_parser.c
@@ -771,7 +771,7 @@ TEST(http_parser, fills_hdr_tbl_for_req)
        const char *s_xch = "X-Custom-Hdr: custom header values";
        const char *s_dummy9 = "Dummy9: 9";
        const char *s_dummy4 = "Dummy4: 4";
-       const char *s_cc  = "Cache-Control: max-age=1, no-store, min-fresh=30";
+       const char *s_cc  = "Cache-Control: max-age=1, no-storer, min-fresh=30";
        const char *s_te  = "compress, gzip, chunked";
        /* Trailing spaces are stored within header strings. */
        const char *s_pragma =  "Pragma: no-cache, fooo ";
@@ -796,7 +796,7 @@ TEST(http_parser, fills_hdr_tbl_for_req)
                "Dummy7: 7\r\n"
                "Dummy8: 8\r\n" /* That is done to check table reallocation. */
                "Dummy9: 9\r\n"
-               "Cache-Control: max-age=1, no-store, min-fresh=30\r\n"
+               "Cache-Control: max-age=1, no-storer, min-fresh=30\r\n"
                "Pragma: no-cache, fooo \r\n"
                "Transfer-Encoding: compress, gzip, chunked\r\n"
                "Cookie: session=42; theme=dark\r\n"
```

**Comment by krizhanovsky** [comment]
Probably we can introduce a new matcher or amend `TRY_STR` macros to match a possible set of delimiters, e.g. match `,` or `\r`, or `\n`. This technique is usually referenced as *peeking* in automata. The second option, probably easier one, is to do an action (e.g. `msg->flags |= TFW_HTTP_F_ACCEPT_HTML`) on next character & state.

It's unclear how crucial the issues is, but it's good to explore it with #695 and #1121, so schedule it to 0.7.
