### ISSUE TITLE
HTTP parser: replace switch by direct jumps by lables address

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1131]
The main our FSM for HTTP parser as well as generic `lib/fsm.h` and frang state machines still use `switch` statements for very initial entry to a FSM - all consequent jumps are performed directly by jumps. The HTTP FSM is pretty large, so even having compiler optimizations for large `switch` such as binary search and hashing, the lookup can be costly and there is no sense to spend CPU on them.

[GCC allows](https://gcc.gnu.org/onlinedocs/gcc/Labels-as-Values.html) to directly get addresses of labels, so we can use them in `goto` statements with a variable containing a label address. Also this reading can be good and useful [JIT Compilation Without (Much) Assembler in GNU C](http://dginasa.blogspot.com/2012/05/jit-compilation-without-much-assembler.html).

All the FSMs must be reworked to use the direct immediate jumps. With the change we also can remove doubling of `case` labels and labels used for `goto` statements leaving only the last ones.

**Comment by sempervictus** [comment]
Would this approach still be safe with randstruct involved if the label targets are struct fields?

**Comment by krizhanovsky** [comment]
Hi @sempervictus ,

it seems I didn't get your question. [Randstruct](https://lwn.net/Articles/722293/) is about randomization of a structure members, i.e data segments. The task is about getting addresses of labels placed in code segments and storing the addresses in some `void *` member of our parser data structure. So if the member of the parser data structure changes it's location, how does it affect `switch` and `goto` statements?
