### ISSUE TITLE
Unable to install ? Error on Script and while compiling sources

### ISSUE THREAD

**Issue by Theoooooo** [tempesta-tech/tempesta#1218]
I'm currently trying to install tempesta on a new Debian 9.5.0 VM which is separated in a DMZ network.

I followed the step to install the solution with the package solution and ran the .sh script from your documentation (https://raw.githubusercontent.com/tempesta-tech/tempesta/master/pkg/scripts/tempesta_installer.sh)

Unfortunately, the script is always stopping in the "Downloading latest packages from github.com/tempesta-tech/tempesta ..." step with the following error : 

Can't download file tempesta-fw-dkms from release debian-9/0.6.1 in repo:
https://github.com/tempesta-tech/tempesta
Or may be Github API rate limit exceeded.

Later, i tried to install the solution from source and followed the steps in the github documentation.

After installing the patch kernel for my VM, i start compiling the Tempesta sources.
But then, i got a bunch of errors relating to wrong value type.
There is the entire response from the "make" command in the git directory that i pull myself (git clone https://github.com/tempesta-tech/tempesta) :

Makefile:72: WARNING: NO AVX2 SUPPORT, YOU WILL BE SLOW
make -C tempesta_db
make[1] : on entre dans le répertoire « /home/ronce/tempesta/tempesta_db »
make -C libtdb
make[2] : on entre dans le répertoire « /home/ronce/tempesta/tempesta_db/libtdb »
g++ -O2 -std=gnu++11 -ggdb -Wall -I../core -shared -fPIC -c handler.cc -o handler.o
handler.cc: In member function ‘void TdbHndl::alloc_trx_frame()’:
handler.cc:198:42: warning: throw will always call terminate() [-Wterminate]
   throw TdbExcept("no tx frame available");
                                          ^
g++ -O2 -std=gnu++11 -ggdb -Wall -shared -fPIC -o libtdb.so handler.o
make[2] : on quitte le répertoire « /home/ronce/tempesta/tempesta_db/libtdb »
make -C tdbq
make[2] : on entre dans le répertoire « /home/ronce/tempesta/tempesta_db/tdbq »
g++ -O2 -std=gnu++11 -ggdb -Wall -I../libtdb -I../core -c main.cc -o main.o
g++ -O2 -std=gnu++11 -ggdb -Wall -o tdbq main.o -lboost_program_options -L../libtdb -ltdb
make[2] : on quitte le répertoire « /home/ronce/tempesta/tempesta_db/tdbq »
make[1] : on quitte le répertoire « /home/ronce/tempesta/tempesta_db »
make -C /lib/modules/4.9.0-tempesta-amd64/build M=/home/ronce/tempesta modules
make[1] : on entre dans le répertoire « /usr/src/linux-headers-4.9.0-tempesta-amd64 »
  CC [M]  /home/ronce/tempesta/lib/hash.o
  CC [M]  /home/ronce/tempesta/lib/main.o
  LD [M]  /home/ronce/tempesta/lib/tempesta_lib.o
  CC [M]  /home/ronce/tempesta/tempesta_db/core/file.o
/home/ronce/tempesta/tempesta_db/core/file.c: In function ‘tempesta_map_file’:
/home/ronce/tempesta/tempesta_db/core/file.c:201:27: error: passing argument 2 of ‘kernel_read’ makes integer from pointer without a cast [-Werror=int-conversion]
  addr = kernel_read(file, (char *)ma->start, len, &off);
                           ^
In file included from /home/ronce/tempesta/tempesta_db/core/file.c:24:0:
/usr/src/linux-headers-4.9.0-tempesta-common/include/linux/fs.h:2714:12: note: expected ‘loff_t {aka long long int}’ but argument is of type ‘char *’
 extern int kernel_read(struct file *, loff_t, char *, unsigned long);
            ^~~~~~~~~~~
/home/ronce/tempesta/tempesta_db/core/file.c:201:46: error: passing argument 3 of ‘kernel_read’ makes pointer from integer without a cast [-Werror=int-conversion]
  addr = kernel_read(file, (char *)ma->start, len, &off);
                                              ^~~
In file included from /home/ronce/tempesta/tempesta_db/core/file.c:24:0:
/usr/src/linux-headers-4.9.0-tempesta-common/include/linux/fs.h:2714:12: note: expected ‘char *’ but argument is of type ‘long unsigned int’
 extern int kernel_read(struct file *, loff_t, char *, unsigned long);
            ^~~~~~~~~~~
/home/ronce/tempesta/tempesta_db/core/file.c:201:51: error: passing argument 4 of ‘kernel_read’ makes integer from pointer without a cast [-Werror=int-conversion]
  addr = kernel_read(file, (char *)ma->start, len, &off);
                                                   ^
In file included from /home/ronce/tempesta/tempesta_db/core/file.c:24:0:
/usr/src/linux-headers-4.9.0-tempesta-common/include/linux/fs.h:2714:12: note: expected ‘long unsigned int’ but argument is of type ‘loff_t * {aka long long int *}’
 extern int kernel_read(struct file *, loff_t, char *, unsigned long);
            ^~~~~~~~~~~
/home/ronce/tempesta/tempesta_db/core/file.c: In function ‘tempesta_unmap_file’:
/home/ronce/tempesta/tempesta_db/core/file.c:245:49: error: passing argument 4 of ‘kernel_write’ makes integer from pointer without a cast [-Werror=int-conversion]
  r = kernel_write(file, (void *)ma->start, len, &off);
                                                 ^
In file included from /home/ronce/tempesta/tempesta_db/core/file.c:24:0:
/usr/src/linux-headers-4.9.0-tempesta-common/include/linux/fs.h:2721:16: note: expected ‘loff_t {aka long long int}’ but argument is of type ‘loff_t * {aka long long int *}’
 extern ssize_t kernel_write(struct file *, const char *, size_t, loff_t);
                ^~~~~~~~~~~~
cc1: all warnings being treated as errors
/usr/src/linux-headers-4.9.0-tempesta-common/scripts/Makefile.build:298 : la recette pour la cible « /home/ronce/tempesta/tempesta_db/core/file.o » a échouée
make[5]: *** [/home/ronce/tempesta/tempesta_db/core/file.o] Erreur 1
/usr/src/linux-headers-4.9.0-tempesta-common/scripts/Makefile.build:549 : la recette pour la cible « /home/ronce/tempesta/tempesta_db/core » a échouée
make[4]: *** [/home/ronce/tempesta/tempesta_db/core] Erreur 2
/usr/src/linux-headers-4.9.0-tempesta-common/Makefile:1507 : la recette pour la cible « _module_/home/ronce/tempesta » a échouée
make[3]: *** [_module_/home/ronce/tempesta] Erreur 2
Makefile:150 : la recette pour la cible « sub-make » a échouée
make[2]: *** [sub-make] Erreur 2
Makefile:8 : la recette pour la cible « all » a échouée
make[1]: *** [all] Erreur 2
make[1] : on quitte le répertoire « /usr/src/linux-headers-4.9.0-tempesta-amd64 »
Makefile:72 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 2

I also add that every pre-requies package and modification write in the documentation have been done on my sight.

**Comment by ikoveshnikov** [comment]
Hi Théo,

Thank you for bug report! The installer script and the documentation on wiki pages is outdated. Current master (and latest 0.6 release) of the Tempesta ADC requires [4.14 kernel](https://github.com/tempesta-tech/linux-4.14.32-tfw/), not 4.9.

We will update the binary packages and documentation ASAP, but if the fresh build is required now, you can follow "building from sources" instruction using the 4.14 kernel.
