### ISSUE TITLE
tempesta_tls.ko: Unknown symbol in module

### ISSUE THREAD

**Issue by Theoooooo** [tempesta-tech/tempesta#1224]
There is the steps to reproduce the problem :

- Installed Debian 9.5.0 and configure an access to pull the required packages for the installation
- Build the kernel patch (4.14.32) from source and install it with these instructions : https://github.com/tempesta-tech/tempesta/wiki/Install-from-Sources
-  Build and install the Tempesta source with the same link.

When i start the service or load the modules with the tempesta.sh, i got the following errors :

----@Tempesta:~/linux-4.14.32-tfw/tempesta# scripts/tempesta.sh --load
Loading Tempesta kernel modules...
Loading module tempesta_tls
insmod: ERROR: could not insert module /root/linux-4.14.32-tfw/tempesta/tls/tempesta_tls.ko: Unknown symbol in module
ERROR: cannot load tempesta TLS module

I got no error during the compilation/installation from both the kernel and tempesta.
I still have the entire session logs if you need the full logs during the compilation/installation of the kernel patch and tempesta.

**Comment by ikoveshnikov** [comment]
Hi Théo,

I just sent an email to you. Could you provide some more information on the issue:
- are you building Tempesta from current master?
- what is the missed symbol? Could you provide sytem log after `scripts/tempesta.sh --load` command was called?

**Comment by ikoveshnikov** [comment]
related to #1218

**Comment by Theoooooo** [comment]
Thanks for the answer, there is the informations you need :

- I build the sources from the "git clone https://github.com/tempesta-tech/tempesta"
- After installer the kernel patch, i rebooted with the patch version properly (i think)
- There is the error return by the script with the "dmesg" command :
`[ 2237.062950] tempesta_lib: loading out-of-tree module taints kernel.
[ 2237.316588] [tempesta tls] ERROR: Cannot preload sha512-avx2 module, please check /proc/crypto.
`

**Comment by avbelov23** [comment]
@Theoooooo, do you try under virtualbox under windows?

**Comment by Theoooooo** [comment]
@avbelov23 I can't try it to VirtualBox i don't have the necessary right to test this on my computer. I install it in a VM under VMware ESXi 6.0.0

**Comment by avbelov23** [comment]
@Theoooooo, please show `cat / proc / cpuinfo` output on vm

**Comment by ikoveshnikov** [comment]
Tempesta is designed to deliver high speed HTTP processing and we use AVX2 and other advanced instructions as often as possible. Running Tempesta on non-AVX2 enabled targets is back compatibility feature. @avbelov23 has found that the issue was in that back compatibility code (lack of thereof).

We used `sha512-avx2` hash function implementation to get better performance on TLS processing. But on some virtual machines `bmi2` instruction set required for this crypto functions is not available, that was the reason for `Unknown symbol in module` message.

We have fixed the code to chose the best suitable algorithm depending on target cpu. The solution is provided in #1227 and will be merged into master shortly.

**Comment by Theoooooo** [comment]
> Tempesta is designed to deliver high speed HTTP processing and we use AVX2 and other advanced instructions as often as possible. Running Tempesta on non-AVX2 enabled targets is back compatibility feature. @avbelov23 has found that the issue was in that back compatibility code (lack of thereof).
> 
> We used `sha512-avx2` hash function implementation to get better performance on TLS processing. But on some virtual machines `bmi2` instruction set required for this crypto functions is not available, that was the reason for `Unknown symbol in module` message.
> 
> We have fixed the code to chose the best suitable algorithm depending on target cpu. The solution is provided in #1227 and will be merged into master shortly.

Ty for the precise reply. I will wait until the next merge for this code change (:

**Comment by i-rinat** [comment]
> wait until the next merge for this code change

Code is now merged into the `master` branch. So the modules should now load on machines with no (usable) AVX2 extensions. If the modules still fail to load, feel free to reopen the issue (or create another one).
