### ISSUE TITLE
Handle Content-Type in GET requests

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1296]
There is a [WAF bypass](https://www.youtube.com/watch?v=tSf_IXfuzXk) ([slides](https://www.slideshare.net/SoroushDalili/waf-bypass-techniques-using-http-standard-and-web-servers-behaviour)) technique to send GET requests with attack payload and Content-Type header - some web servers still process the body of GET requests. In `__req_parse_content_type()` we just skip Content-Type parsing and seems just normally forward such requests to a backend.

Need to check RFC for Content-Type requirements - if it prohibits such requests, then we must block them. Otherwise probably we need a new configuration option like `http_strict_mode` which allows to set Tempesta mode for various  HTTP fields in which it blocks such HTTP messages. If the mode isn't set for a HTTP field, then we should just print warning. There are potentially many HTTP fields which behavior are either not clearly defined by RFC or impractical (e.g. single LF character for end of HTTP line).

Please update [HTTP security](https://github.com/tempesta-tech/tempesta/wiki/HTTP-security) and [Web security](https://github.com/tempesta-tech/tempesta/wiki/Web-security) wikis with detailed examples of the attacks (with reference to the original talk) and Tempesta settings.

**Comment by krizhanovsky** [comment]
RFC 7231 4.3.* say:
```
   A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.
```
```
   A payload within a HEAD request message has no defined semantics;
   sending a payload body on a HEAD request might cause some existing
   implementations to reject the request.
```
```
   A payload within a DELETE request message has no defined semantics;
   sending a payload body on a DELETE request might cause some existing
   implementations to reject the request.
```
```
   A payload within a CONNECT request message has no defined semantics;
   sending a payload body on a CONNECT request might cause some existing
   implementations to reject the request.
```
```
   A client MUST NOT send a message body in a TRACE request.
```
So Content-Type and Content-Length headers must not be allowed for the methods as well as parser must not have a path to body processing for these methods.

We still need to describe the logic for blocking such requests with links to the attacks scenarios in the Wiki

**Comment by krizhanovsky** [comment]
The unit test for HTTP parser had a bug fixed in https://github.com/tempesta-tech/tempesta/commit/4c9d287c5e999d807048724459d7da7ca5bca2b6#diff-b1785da4f54bd40909398a1a64bcdeef768a8a30c0764f23cb706d2102cfc657L821 . After the fix many failures on Content-Type validation appeared in the test:
```
[   57.529869] tfw_test: /root/tempesta/fw/t/unit/test_http_parser.c:861: error:
[   57.531219] tfw_test: FAIL:
[   57.531687] tfw_test:   test__http_parser__fills_hdr_tbl_for_req()
[   57.532610] tfw_test:   EXPECT_TRUE((tfw_str_eq_cstr(&h_conttype, s_ct, strlen(s_ct), 0))) => 0x0
[   57.534012] tfw_test: /root/tempesta/fw/t/unit/test_http_parser.c:861: error:
[   57.535564] tfw_test: FAIL:
[   57.536098] tfw_test:   test__http_parser__fills_hdr_tbl_for_req()
[   57.537008] tfw_test:   EXPECT_TRUE((tfw_str_eq_cstr(&h_conttype, s_ct, strlen(s_ct), 0))) => 0x0
[   57.538460] tfw_test: /root/tempesta/fw/t/unit/test_http_parser.c:861: error:
[   57.539565] tfw_test: FAIL:
[   57.540044] tfw_test:   test__http_parser__fills_hdr_tbl_for_req()
[   57.540951] tfw_test:   EXPECT_TRUE((tfw_str_eq_cstr(&h_conttype, s_ct, strlen(s_ct), 0))) => 0x0
[   57.543131] tfw_test: /root/tempesta/fw/t/unit/test_http_parser.c:861: error:
....
```

Besides the fix, there is also the bug with the loop in `split_and_parse_n()` (I belive it's already discussed in other issues/pull requests), which must be fixed.

**Comment by ttaym** [comment]
[Hacker_WAF-Bypass-Techniques_Soroush-Dalili_AppSecEU2018.pptx](https://github.com/tempesta-tech/tempesta/files/7994421/Hacker_WAF-Bypass-Techniques_Soroush-Dalili_AppSecEU2018.pptx)

Upload mentioned slides here as they are not available by old link.

**Comment by ttaym** [comment]
Rewrite web security wiki page in [HTTP request smuggling section](https://github.com/tempesta-tech/tempesta/wiki/Web-security#http-request-smuggling) to reflect base types of smuggling attacks with comments and attack surface and what Tempesta FW may do (or may be already does) about it.
