### ISSUE TITLE
[unittest] HTTP/2 parser

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1297]
Need to extent `t/unit/test_http_parser.c` to run the same tests against HTTP/2 requests (we do not process HTTP/2 responses yet). The test must carefully test and fuzz the framing layer.

#1560 introduced h2 tests in `t/unit/test_http_parser.c` to not to duplicate all strings parsing and basic tests helping routines. Need to extend the tests to cover the same test cases in the h2 parser as in the http/1 parser. Whether to keep tests for both the parsers in the same file is TDB.

The task is very large, so please make it with a small pull requests, that we can make a smooth progress on it.

- [x] **(crucial!)** Process chunked messages, especially in the headers part to stress hpack decoder. `Authorization` header and other HTTP/2 headers mentioned in https://github.com/tempesta-tech/tempesta/pull/1566/files#r807475198 must be tested with chunked mode to test the fix #1566.
- [x] Body-less methods with Content-Type, Content-Length and/or body (see #1296 )
- [x] All the cases for the [static table](https://datatracker.ietf.org/doc/html/rfc7541#appendix-A)
- [x] dymamic table (this is might be not so easy to do in the unit test, TBD )

There are concerns, that in fact chunk fuzzing not run (or at least run not in full). See https://github.com/tempesta-tech/tempesta/pull/1576#issuecomment-1057878436 . Need to ensure 'with instrumentation and/or parser debugging' facilities that chunk fuzzing fully run as intended and give tangible evidence on this. 

See also #1059.

**Comment by voodam** [comment]
What also is good to be checked ana maybe fixed:
1. This code in `tfw_h2_parse_req_finish` is probably wrong:
```
	if (req->content_length
	    && req->content_length != req->body.len)
	{
		return T_DROP;
	}
	/*
	 * RFC 7540 8.1.2.6: A request or response that includes a payload
	 * body can include a content-length header field.
	 *
	 * Since the h2 provides explicit message framing, the content-length
	 * header is not required at all. But our code may rely on
	 * req->content_length field value, fill it.
	 */
	req->content_length = req->body.len;
```
First time `req->content_length != req->body.len` is checked, then `req->content_length = req->body.len` is set.

Also for now `content_length` have limit `LONG_MAX` to fit `parser->to_read` field, so maybe `req->body.len` also need to be limited in the same way.

2. Is it OK that in `tfw_h2_parse_body` on this line `long` type is passed when `len` is `unsigned long`?
```
m_len = min_t(long, parser->to_read, len);
```
 And the same question is for the other similar places.

**Comment by keshonok** [comment]
On (1), I don't see a logic flaw. The comment in the code helps to clarify the intent.
First, it's enforced that if the `Content-Length` header is present, then it's value must be equal to `req->body.len`. If it's not set, then it's all fine and dandy. Then, `req->content_length` is set to be equal to `req->body.len`, as there's (or there may be) code (I guess, written before HTTP2 implementation) that relies on it being set.

**Comment by krizhanovsky** [comment]
> It seems that chunked messages not always work for h2 frame parsing.
> 
> I tried multichunked parsing of headers frame (+END_STREAM +END_HEADERS) in unit tests of h2 parsing and they are not worked to me. I tried it on plain string without Huffman encoding and indexing of names or values.
> 
> As i can see `tfw_hpack_decode()` do not store enough state for reentering on next chunk for example in the middle of header name. I mean this place
> 
> https://github.com/tempesta-tech/tempesta/blob/25a420c294a0867e2c8946e065da39dd4463ca9c/fw/hpack.c#L1421
> . State will be updated to `HPACK_STATE_VALUE` unconditionally after partial name extraction.

As I see with pull requests #1597 #1603 #1612 #1615 #1616 #1620 #1622 #1621 , HTTP/2 testing messages are splitted for many chunks, just like HTTP/1

**Comment by alegz-filomaphitskay** [comment]
> 2. Is it OK that in `tfw_h2_parse_body` on this line `long` type is passed when `len` is `unsigned long`?
> ```
> m_len = min_t(long, parser->to_read, len);
> ```
>  And the same question is for the other similar places.

On the technical side, it looks like there might be problems. The key points are related to http_parser.c. In addition to the demonstrated example, we can highlight the following: `parser->to_read = msg->content_length; // long = long unsigned` or `parser->to_read = parser->_acc; // long = long unsigned`. They demonstrate the assignment of the value received from the incoming request, which theoretically could be `ULONG_MAX`. But we can see how `msg->content_length` gets its value: `r = parse_long_ws(data, len, &msg->content_length);` which expands to `__parse_ulong_ws(data, len, &msg->content_length, LONG_MAX)`. So, based on the logic of the code, the value of the `msg->content_length` variable cannot exceed `LONG_MAX`, which gives us some guarantee. There are several similar places, but everywhere there is a limitation from the current code logic.
As for the original remark about `tfw_h2_parse_body()`, there is also a limiting factor at a higher level of logic that ensures that the value that comes with type `size_t` does not exceed `unsigned int`. There is a PR about it - #1620.
