### ISSUE TITLE
Failed skcipher tests on system boot

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1340]
## Scope

During system boot with current kernel and config 
[linux-4.14.32-config.txt](https://github.com/tempesta-tech/tempesta/files/3512391/linux-4.14.32-config.txt) following warnings are thrown into dmesg:
```
[    3.491539] alg: aead: setkey failed on test 1 for generic-gcm-aesni: flags=0
[    3.494103] alg: skcipher: Test 1 failed (invalid result) on encryption for cbc-aes-aesni
[    3.495861] 00000000: 3a e0 0f bd 31 df ae ed 4d a6 e4 4f e2 c1 1b 4f
[    3.497791] alg: skcipher: Test 1 failed (invalid result) on encryption for ctr-aes-aesni
[    3.499969] 00000000: 3a d7 7b b4 0d 7a 36 60 a8 9e ca f3 24 66 ef 97
[    3.501601] 00000010: f5 d3 d5 85 03 b9 69 9d e7 85 89 5a 96 fd ba af
[    3.503249] 00000020: 43 b1 cd 7f 59 8e ce 23 88 1b 00 e3 ed 03 06 88
[    3.505258] 00000030: 7b 0c 78 5e 27 e8 ad 3f 82 23 20 71 04 72 5d d4
[    3.507602] alg: skcipher: Test 1 failed (invalid result) on encryption for xts-aes-aesni
[    3.510034] 00000000: dc 95 c0 78 a2 40 89 89 ad 48 a2 14 92 84 20 87
[    3.511848] 00000010: dc 95 c0 78 a2 40 89 89 ad 48 a2 14 92 84 20 87
```
It seems the latest patch in `/linux/crypt` has broken something.

## Testing

A functional test must check dmesg for the messages.

**Comment by krizhanovsky** [comment]
The tests are executed by `crypto/testmgr.c` and can be run manually with tcrypt module. Tempesta TLS uses `gcm(aes)` (mode 35), `ccm(aes)` (mode 37), `hmac(sha256)` (mode 102), `hmac(sha384)` (mode 103), and `hmac(sha512)` (mode 104), so the command to run the test is:
```
# for m in 35 37 102 103 104; do modprobe tcrypt mode=$m; done
modprobe: ERROR: could not insert 'tcrypt': Resource temporarily unavailable
modprobe: ERROR: could not insert 'tcrypt': Resource temporarily unavailable
modprobe: ERROR: could not insert 'tcrypt': Resource temporarily unavailable
modprobe: ERROR: could not insert 'tcrypt': Resource temporarily unavailable
modprobe: ERROR: could not insert 'tcrypt': Resource temporarily unavailable
```
`-EAGAIN` return code is the successful return code of the module.

Actually, I didn't see the initial error messages in my dmesg for a while and the `tcrypt` testing module also doesn't reveal any problem.

**Comment by i-rinat** [comment]
The issue can be reproduced with the 4.14.32-tfw kernel before changes from https://github.com/tempesta-tech/linux-4.14.32-tfw/pull/8, and cannot be reproduced after. That patch dealt with too aggressive algorithm caching that caused code from mismatched algorithms to be executed.

I strongly believe that the issue was fixed by https://github.com/tempesta-tech/linux-4.14.32-tfw/pull/8.
