### ISSUE TITLE
Write header names in lower case when transform h1 responses to h2

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#1380]
From the [RFC 7540 8.1.2](https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.2)
 > Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion. However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed (Section 8.1.2.6).

According the RFC an end point must close a connection (send error) on receiving our responses, ~~but major browsers and curl _ignore_ this requirement. Well, it's a problem for us, actually.~~ **All modern browsers treat mixed case in headers names as protocol error.** Converting header names to lower case definitely has performance impact. ~~But even if browsers are OK, we can't just break the RFC requirement and leave headers names in mixed case.~~

From https://github.com/tempesta-tech/tempesta/pull/1374#discussion_r368960033

**Comment by krizhanovsky** [comment]
I agree that it does not make much sense to convert the cases. Probably we can just generate our headers in lower case always, including HTTP/1 (RFC 7230 doesn't require that the first character must be capital).

**Comment by ikoveshnikov** [comment]
We already generate lowercase headers for all protocols. Just like all other modern http servers.

If you try to grep mixed-case headers, you will find them in `http_msg.c`, but only inside macroses that tell header name length. So there is nothing worry about.

**Comment by ikoveshnikov** [comment]
I have rechecked the issue by @avbelov23  request. All the modern browsers do treat mixed case headers as malformed. I took me relative long time to figure out why I made such a misleading conclusion in January. I installed an OS with packets dated by January, ann all clients there still block the responses. It seems like I tested mixed case only on headers that are encoded using static tables. When firefox decodes them it uses mixed case. Probably this is an explanation of this awkward situation.

Note: we can add custom headers to http messages (`resp_header_add` and Co) - it worth to convert to lower case the header name while parsing configuration file.

**Comment by krizhanovsky** [comment]
`tfw_h2_resp_adjust_fwd()` wrongly comments that
> Major browsers and curl ignore that RFC requirement an work well. But
> that is definitely an RFC violation and implementation specific behaviour.

Since the header name strings are quite short, there is no sense to use SIMD for the characters case conversion. However, we should not traverse the data twice. I think the appropriate place to lower the case of header names is `tfw_hpack_encode()` or some core around/inside the function. For example, we can replace `memcpy_fast()` call in `tfw_h2_msg_rewrite_data()` with copying data along the case conversion. The case conversion should be done using recoding table without conditional statements.
