### ISSUE TITLE
Error during parsing cache-control header

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#1386]
## Scope

I have configured Tempesta to stand in front of our CI server and got a response dropped by Tempesta. The reason to block the response was  `Cache-control: public;max-age=0`.  But the header is [defined](https://tools.ietf.org/html/rfc7234) as:
```
Cache-Control = *( "," OWS ) cache-directive *( OWS "," [ OWS
    cache-directive ] )
 cache-directive = token [ "=" ( token / quoted-string ) ]
```
So the header is not formatted as required by RFC and it must be filtered out. It's definitely an issue of the Buildbot itself. But all the browsers are happy with the response and show the content normally. Seems we should also. Need to take a look to a different servers, how they deal with the problem.

**Comment by krizhanovsky** [comment]
There are two aspects of the problem:
1. malformed headers might have a security implications, for example a web cache poisoning in this case if an attacker can control the header value;
2. robust user experience even for poorly developed web apps.

I think we should do following:
1. print a net rate limited warning about malformed header in a response - this will help a site owner to fix the problem;
2. do not cache response with malformed cache management headers to avoid cache related attacks;
3. pass the response as is to a client to not to break the user experience.

**Comment by krizhanovsky** [comment]
This task is for responses only. We should still drop malformed requests. The implementation must be as tiny as possible to not to affect the parser performance.

**Comment by krizhanovsky** [comment]
The original BuildBot issue was already fixed by @ikoveshnikov 's report and this is the right way to deal with such problems: it's better to fix buggy apps, than adjust other software to deal with the bugs.
