### ISSUE TITLE
Can't pass redirect mark, when browser restores old session

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#1398]
## Scope

This issue describes issues with redirect mark (`cookie max_misses` directive) with browsers on session restores.

Tempesta config:
```
sticky {
    cookie name=jdkey enforce max_misses=3 timeout=3;
}

srv_group default {
    server 127.0.0.1:8080;
}

http_chain {
     -> default;
}

```

### Can't reload page in restored session

Browsers may save and restore user sessions on restart. In this case browsers preserve sticky cookie between reboots and also uri redirect.

To reproduce: 
- start Tempesta;
- start browser and open a new session to the protected server with path `/`;
- a sticky cookie challenge will be performed with the redirection mark injection;
- browser gets 302 redirect with sticky cookie and uri as follows: `/__tfw=00000001000000010005cdca7ecbf845cc8fa0151e704f7ae26fd6414a423749/`
- browser follows the redirect with sticky cookie set;
- Tempesta grants access and return content of `/` uri.
- The whole page is displayed correctly, *but the uri in address bar is* `/__tfw=00000001000000010005cdca7ecbf845cc8fa0151e704f7ae26fd6414a423749/`. 
- Exit firefox with session save and reload Tempesta to clear sessions DB;
- Start firefox once agsin, restore the latest session.
- Firefox tries to load the uri `/__tfw=00000001000000010005cdca7ecbf845cc8fa0151e704f7ae26fd6414a423749/` with last sticky cookie.
- Since the cookie is bit outdated and `timeout` is set as 2 seconds, Tempesta treats redirection mark as greatly outdated and blocks client by ip.

Client can't access the site any more. This happen because  cached sticky cookie was too ancient. Seems like directive `sticky { cookie `timeout=3` ) issue. Probably it should be treated as global timeout? Maximum 3 attempts in 3 seconds? Not cookie lifetime?

### Can't reload page in restored session and clean cookies

Same situation as above, but sticky cookie is cleared now after reboot (cookie `jdkey` is missing). Also imagine that we don't block ancient sessions but restart challenge for them (previous part of the issue is resolved).

- browser  tries to load the uri `/__tfw=00000001000000010005cdca7ecbf845cc8fa0151e704f7ae26fd6414a423749/` with no sticky cookie set.
- Tempesta checks the challenge, treats challenge as failed and sends a new redirection mark and cookie.
- browser  tries to load the uri `/__tfw=<NEW_VALUE>/` with **no** sticky cookie set.
- Tempesta redirects client once more time. This repeats `max_misses` times and client gets blocked by IP.

See the point here: client follows redirect but never sets cookie. This happen because Tempesta sticky cookie is **relative** and set only for paths /__tfw=<SOME_VALUE>/`,  /__tfw=<SOME_VALUE>/`  but not over the whole service.

Workaround is available here: set **path** cookie option.

 ```
sticky {
    cookie name=jdkey enforce max_misses=3 timeout=3 options="path=/";
}

```

Seems like the issue can be applied to the sticky cookie in whole, but the problem is shadowed, because redirect mark blocks by ip on every miss while sticky cookies allows any amount of redirects.

### Client can be banned on restart

Imagine client tried to pass redirect mark challenge several times, and finished it only at last chance. Now if client save the session by closing the browser and tries to resume it, it retries uri with last attempt possible. Since a lot of time has passed, redirect mark challenge will be failed, but client already exceeded all possible attempts, so it get banned. Right on session resume.  

## Testing

Check scenarios above.

**Comment by krizhanovsky** [comment]
The problem with the browser address field, containing our security token after the challenge, can be fixed with an additional redirect. This is the known problem and for example tempesta-tech.com sends some meaningful pages instead of 404, but the browser still shows the original and wrong URI.

**Comment by krizhanovsky** [comment]
During the testing please check that the configuration (our demo configuration) can be `--reload`'ed with enabled and disabled JSCH configuration. In the demo case I faced following issue:

1. start Temesta in a VM with the configuration at the below with disabled JSCH configuration, use tempesta-tech.com content under Apache HTTPD as a backend;
2. start Firefox browser on the host in private mode, check that there is no cookies for the VM
3. request `/`
4. `--reload` Tempesta with JSCH enabled
5. Delete cookies in the browswer
6. request `/` again. **No JSCH.**

If I `--restart` Tempesta on step 4, then I do see JSCH on step 6.

```
listen 192.168.100.4:443 proto=https;
listen 192.168.100.4:80;

frang_limits {
	# Conenction level limits.
	client_header_timeout 20;
	client_body_timeout 10;
	http_header_chunk_cnt 10;
	http_body_chunk_cnt 0;

	# Message level limits (per-vhost)
	http_methods GET;
	http_uri_len 512;
	http_resp_code_block 400 403 404 3 10;
}

# Allow only following characters in URI (no '%'): /a-zA-Z0-9&?:-._=
http_uri_brange 0x2f 0x41-0x5a 0x61-0x7a 0x30-0x39 0x26 0x3f 0x3a 0x2d 0x2e 0x5f 0x3d;

sticky {
	cookie name=my_js_cookie enforce max_misses=3 timeout=3;
	js_challenge resp_code=503 delay_min=1000 delay_range=1000 delay_limit=3000 /root/tempesta/etc/js_challenge.html;
}

block_action attack reply;
block_action error reply;

srv_group default {
	server 127.0.0.1:8080 conns_n=4;
}

#vhost debian {
vhost default {
	tls_certificate /root/tempesta/etc/tfw-root.crt;
	tls_certificate_key /root/tempesta/etc/tfw-root.key;

	resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains";

	proxy_pass default;
}

cache 0;
#cache_fulfill * *;

http_chain {
	#hdr "Referer" == "http://badhost.com*" -> block;

	#-> debian;
	-> default;
}
```

**Comment by ikoveshnikov** [comment]
Need to check, but it seems like https://github.com/tempesta-tech/tempesta/issues/1398#issuecomment-680061630 is reconfiguration issue that can be fixed by single line. `allow_reconfig` must have been lost here when JSCH was reformed as per-vhost configuration: https://github.com/tempesta-tech/tempesta/blob/19ee616d51af7fedad4993aee0264ee7712ea37b/tempesta_fw/http_sess_conf.c#L596-L600

`js_challenge` is part of `sticky` configuration, which is part of `vhost`. On reconfiguration on set of vhosts is replaced with a new one, i.e. all vhosts are recreated from scratch. But `js_challenge` directive is not marked as able to reconfig and skipped. BTW, a warning message should appear in the log. So need to add the lost property.

This is how I see the case.
