### ISSUE TITLE
Inconsistent vhost & JSCH configuration

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1452]
## Scope

https://github.com/tempesta-tech/tempesta/wiki/Sticky-Cookie#http-session-management makes false statement that vhost can inherit default sticky configuration. There is quite nasty inconsistency. The config:
```
listen 192.168.100.4:80;

sticky {
        cookie name=my_js_cookie enforce max_misses=3 timeout=3;
        js_challenge resp_code=503 delay_min=1000 delay_range=1000 delay_limit=3000 /root/tempesta/etc/js_challenge.html;
}

srv_group default {
        server 127.0.0.1:9090;
}

vhost default {
        proxy_pass default;
}

cache 1;
cache_fulfill * *;

http_chain {
        -> default;
}
```
Works fine, but
```
listen 192.168.100.4:80;

sticky {
        cookie name=my_js_cookie enforce max_misses=3 timeout=3;
        js_challenge resp_code=503 delay_min=1000 delay_range=1000 delay_limit=3000 /root/tempesta/etc/js_challenge.html;
}

srv_group default {
        server 127.0.0.1:9090;
}

vhost debian {
        proxy_pass default;
}

cache 1;
cache_fulfill * *;

http_chain {
        -> debian;
}
```
does not work. Any non default vhost must use stick inside vhost configuration only, so to make the last config work we have to rewrite it as
```
listen 192.168.100.4:80;

srv_group default {
        server 127.0.0.1:9090;
}

vhost debian {
        sticky {
                cookie name=my_js_cookie enforce max_misses=3 timeout=3;
                js_challenge resp_code=503 delay_min=1000 delay_range=1000 delay_limit=3000 /root/tempesta/etc/js_challenge.html;
        }

        proxy_pass default;
}

cache 1;
cache_fulfill * *;

http_chain {
        -> debian;
}
```

It seems that the only reason for the behaviour is that `update_template.pl` can not track sticky state across the configuration file.

## Testing

- [x] The default sticky in a named vhost
- [x] Double default sticky for a named host - the second sticky should be used
- [x] Double default sticky for the default host - the second sticky should be used
- [x] Internal vhost sticky cookie overrides the default one

## Documentation

Update https://github.com/tempesta-tech/tempesta/wiki/Sticky-Cookie#http-session-management with words that default `sticky` must be always *before* vhost, otherwise the sticky section will be *ignored*.

Please also make https://github.com/tempesta-tech/enterprise/issues/18 as the part of the issue.

**Comment by ikoveshnikov** [comment]
fixed by #1460
