### ISSUE TITLE
Setting cache problems

### ISSUE THREAD

**Issue by DagothDeer** [tempesta-tech/tempesta#1513]
os: Debian-9.13.0
tempesta ver.: 0.6.7

1. Setting caching mode equal 1 or 2 not take difference at all to me.

"https://github.com/tempesta-tech/tempesta/commit/0f5003976ee39a860cb6b80bdc31e87830c052f9"

"Tempesta creates per NUMA node database files, so if you have two
processor packages on modern hardware, then follwoing files will be created
(one for earch processor package) for the example above:
        /opt/tempesta/db/cache0.tdb
        /opt/tempesta/db/cache1.tdb"

But no matter what mode i set 1 or 2 in the directory "/opt/tempesta/db" appears only ONE file: "cache0.tdb".
But in the console the string ".../cache.tdb: size=..." appears two times.
![1](https://user-images.githubusercontent.com/33806067/127068853-8a950d07-8eef-429a-8dfd-c65eb8d56110.png)

And only, when i set caching mode equal = 0 these strings are disappear.

2. Multiple of cache_size

In the config file you are write: 
"# SIZE is specified in bytes, suffixes like 'MB' are not supported yet.
     Also, the number must be a multiple of 2MB (Tempesta DB extent size)."

But, in the console error output you program write that size must be a multiple of 4096 (byte?) and NOT 2MB.
![2](https://user-images.githubusercontent.com/33806067/127069937-6c41401b-70d1-4e40-b05c-542486e81cc3.png)

3. Setting cache_size

In the file "tempesta_fw/cache.c" 1108-1117 strings you set limit of range from PAGE_SIZE (4096 byte?) to 1 « 30 (equal 1073741824 byte == 1GB).
![3](https://user-images.githubusercontent.com/33806067/127071036-c476e91e-6082-4e05-a5a9-867b2645af54.png)

At first, 1 GB of cache is too small for store *.JPG, *.PNG, *.MP4 and etc. as you describe in the config and Wiki. If you have hundreds backends and server with 512 GB of memory you exactly want to have cache more than 1 GB. Some servers have more than 6 TB of memory, so limit cache_size with integer value and parse it with function "TfwCfgSpecInt()" is NOT right.

At second, Tempesta FW could not allow to set "cache_size 1073741824;". I can set maximum 470 MB (492830720 byte).
![4](https://user-images.githubusercontent.com/33806067/127074132-b2028126-6dfd-4fd5-b417-82af32f4b03b.png)

But when i set 471 MB and over i see crash of Tempesta.
![5](https://user-images.githubusercontent.com/33806067/127075205-84e70300-8788-4f3f-89d0-6aeafd084ec7.png)

4. Questions

When i set cache mode 2 with cache_size for example 1 GB, how much Tempesta FW should allocate of system memory? At start it allocate double minimum amout value (256 MB * 2 = 512 MB?) and when the cache fill up it allocate double of set size 
(1 GB * 2 = 2 GB) of system memory. Is it so?

P.S. А можно ли Вам сюда писать на русском языке, чтобы было быстрее и доходчивее?

**Comment by krizhanovsky** [comment]
Hi @DagothDeer ,

thank you for trying Tempesta FW and the issue report!

May I know whether you try to run Tempesta FW on a multi-processor (NUMA) system? If so, then how many nodes do you have? You may not see per-node TDB files since inside `tfw_cache_start()` we iterate over physical NUMA nodes to create the TDB files.

> When i set cache mode 2 with cache_size for example 1 GB, how much Tempesta FW should allocate of system memory? At start it allocate double minimum amout value (256 MB * 2 = 512 MB?) and when the cache fill up it allocate double of set size
(1 GB * 2 = 2 GB) of system memory. Is it so?

Yes, `tfw_cache_start()` iterates the NUMA nodes and creates the TDB file of the specified size `cache_cfg.db_size` for each of them.

I believe we need to fix all the Wiki pages dealing with TempestaDB file sizes. There is `tempesta_dbmem` kernel boot parameter, described in https://github.com/tempesta-tech/tempesta/wiki/Run-&-Stop . With this parameter Tempesta FW allocates contiguous space of huge 2MB pages at early boot stage, while the memory fragmentation is still low. If some Tempesta FW subsystem tries to overuse the space, then typically we should throw a configuration error.

But it seems in your case we just catch the crash in run time. So besides the documentation, we need to carefully check the limits on Tempesta FW start.

P.S. Да, конечно, если Вам удобнее, то пишите на Русском. Мы всегда сможем написать summary на Английском в задаче, чтобы была информативной и для не рускоговорящей аудитории.

**Comment by DagothDeer** [comment]
Здравствуйте Александр @krizhanovsky ,

Мы запускаем Tempesta-FW в виртуальной среде Proxmox. В качестве хоста используется серверная двухпроцессорная плата с двумя процессорами Xeon E5-2697v2 (к сожалению не на архитектуре "Intel Broadwell", но, что есть, то есть. Мы понимаем, что производительность упадет в несколько раз), т.е. 2 NUMA блока.

Конфигурация виртуальной машины:
* ЦП: 2 сокета по 12 ядер, включена поддержка Numa блоков.
* ОЗУ: 10 ГБ
* SCSI: 5 ГБ (из них 512 МБ - swap)
* ОС: Debian-9.13.0

Вот, как NUMA блоки "выглядят" внутри виртуалки:
![1](https://user-images.githubusercontent.com/33806067/128253165-ce7a03fa-c826-4888-b301-d166c68d20a0.png)

"Kern.log" при удачной загрузке системы с настройками cache 2; и cache_size 492830720;
[kern.log](https://github.com/tempesta-tech/tempesta/files/6934446/kern.log)

Судя по строчкам 173 и 174, Tempesta-FW удачно зарезервировала свои 512 МБ на каждой ноде:
`Aug 5 03:13:40 Tempesta-FW kernel: [ 0.000000] Tempesta: allocated huge pages space ffff947a8b800000 512MB at node 0`
`Aug 5 03:13:40 Tempesta-FW kernel: [ 0.000000] Tempesta: allocated huge pages space ffff947bda400000 512MB at node 1`

Судя по строчкам 760 и 761, Tempesta-FW создала один файл cache.tdb:
`Aug 5 03:13:40 Tempesta-FW kernel: [ 3.046259] [tdb] Opened table /opt/tempesta/db/cache.tdb: size=492830720 rec_size=0 base=ffff947a8e200000`
`Aug 5 03:13:40 Tempesta-FW kernel: [ 3.256441] [tdb] Opened table /opt/tempesta/db/cache.tdb: size=492830720 rec_size=0 base=ffff947bdbe00000`

"Kern_stop.log" - лог ядра, при штатном выключении Tempesta-FW
[kern_stop.log](https://github.com/tempesta-tech/tempesta/files/6934507/kern_stop.log)

Как видим, согласно 3 строчке "закрывается" лишь 1 файл "cache0.tdb" => только он 1 и был создан.
`Aug 5 03:28:14 Tempesta-FW kernel: [ 877.625868] [tdb] Close table 'cache0.tdb'`

Получить лог краша так и не получилось, т.к. ssh сессии, собственно как и эмулируемый serial порт с терминалом, просто "падают" вместе с ядром.
Попытки увеличения раздела swap, подсовывания параметра загрузки ядра "tempesta_dbmem=9" (не уверены, что правильно подали этот параметр в загрузчик GRUB), попытки установить все тоже самое на VMware Workstation (за исключением того, что на данной конфигурации раздельные NUMA блоки - не эмулировались) не принесли ни какого успеха, ядро по-прежнему "падает" при выставлении параметра "cache_size 493879296".

Другие мысли:
Вы писали "we need to carefully check the limits on Tempesta FW start". Складывается ощущение, что резервируемый объем памяти в 512 МБ ("tempesta_dbmem=8"), дополнительно расходуется на другие нужды помимо самого кэша (определяемый параметром "cache_size"), например на таблицы клиентов и правил по 16 МБ. Итого получим на 3 таблицы уже 470 + 16 + 16 = 502 МБ. Осталось лишь 10 МБ, которые Tempesta-FW возможно использует для своих "нужд". 
Но это лишь предположение. Эту часть кода мы не смотрели, но само лимитирование 470 МБ из выделенных 512 МБ на это указывает. По какой формуле можно расчитать объем памяти, которая останется свободной под отображение кэша в оперативку? И если краш ядра вызывается все таки черезмерно-большим значением кэша (не влазящим в заранее зарезервированную область в 512 МБ), то видимо нам не удалось выставить "tempesta_dbmem=9". Не подскажете ли Вы, как правильно задать этот параметр? Мы его пытались подсовывать в командную строку GRUB, но возможно его нужно было прописать в какой-то файл, т.к. судя по литературе, у каждой подсистемы есть куча своих параметров ядра и все они разбросаны по разным файлам.

P.S. Мы (2 человека), имеем опыт программирования за плечами, но в Linux делаем только свои первые шаги и изучаем его не более пары месяцев, по этому, возможно, можем не видеть каких-то элементарных оплошностей. Пожалуйста, просим это учесть. 
Собственно, по этой причине и пишем только через неделю, т.к. все это время пытались выявить причину и отладить ее самостоятельно.
P.P.S. Сейчас пробуем собрать из исходников Current (версию 0.7), но конфигурирование ядра (анкета на 500+ параметров) вызывает у нас еще больше вопросов...

**Comment by DagothDeer** [comment]
UPDATE

Удалось выставить параметр "tempesta_dbmem=9", прописав его в "/etc/default/grub", в строке GRUB_CMDLINE_LINUX_DEFAULT="quiet tempesta_dbmem=9"

В результате, в kern.log строка резервирования памяти заменилась на следующую:
`Tempesta: allocated huge pages space ffff9e67b9400000 1024MB at node 0`

Манипуляция проводилась на VMWare с одной нодой.

Результат:

Вылет ядра на шаге создания файла с таблицей кэша.

**Comment by krizhanovsky** [comment]
@DagothDeer спасибо за подробное описание проблемы!

Я сделал несколько фиксов в https://github.com/tempesta-tech/tempesta/pull/1514 - не могли бы вы попробовать этот бранч?

Как выделяется память я описал в https://github.com/tempesta-tech/tempesta/wiki/Run-&-Stop#prepare-to-start - кроме описанных вами есть еще таблица сессий - это еще 16MB.

Я попробовал позапускать Темпесту с различными значениями `cache_size`, общую конфигурацию я использовал такую:
```
listen 192.168.100.4:443 proto=https;
listen 192.168.100.4:80;

srv_group default {
        server 127.0.0.1:8080 conns_n=4;
}

vhost default {
        tls_certificate /root/tempesta/etc/tfw-root.crt;
        tls_certificate_key /root/tempesta/etc/tfw-root.key;

        #resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains"

        proxy_pass default;
}

cache 2;
cache_fulfill * *;
cache_size 16777216;

block_action attack reply;

http_chain {
        -> default;
}
```

Запускал я на KVM с 4 hardware CPU и виртуальной двухнодовой NUMA и 4GB RAM, полная конфигурация VM:
```qemu-system-x86_64 -s -machine dump-guest-core=on -enable-kvm -m 4096 -numa node,nodeid=0 -numa node,nodeid=1 -cpu host -smp cpus=2 -no-hpet -name tfw-test -drive file=debian.img,format=raw -netdev tap,ifname=tap0,id=n1,vhost=on,queues=1,script=no -device virtio-net-pci,netdev=n1,mq=on,vectors=3 -boot order=cd,menu=on -serial file:serial-deb.txt
```

Крэш у мегя вопсроизвести не получилось. Буду благодарен, если сможете воспроизвести проблуму с включенной [netconsole](https://wiki.ubuntu.com/Kernel/Netconsole) с выводом на другой сервер (например, если вы работаете с удаленным сервером, то локально у себя можно запустить `nc` на UDP порту и Oops'ы обычно хорошо ловятся, даже на удаленной машине).

**Comment by krizhanovsky** [comment]
There is no response for 2 weeks and #1514 is merged. Please reopen the issue if the problem appears with the fixes.
