### ISSUE TITLE
Automatic Platform Optimization

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1516]
## Scope

CloudFlare provides [APO](https://blog.cloudflare.com/automatic-platform-optimizations-starting-with-wordpress/) which seems just an automatic population of changed content into the cache, i.e. instead of purging content on update, they immediately update the web cache. Very similar set of features is provided by the [LiteSpeed WordPress plugin](https://wordpress.org/plugins/litespeed-cache/). This task will be easily done with the web-content tool. We can do not only web cache population, but also optimizations such as content minification.

Basically, the APO can be easily implemented using `wget -r <domain_name>`, probably with generated headers according to the web server settings for `Vary` values. However, in more advanced (heavy loaded) case wget requires to transfer response bodies and process them on the `wget` side. This is not wished and the Tempesta tool should send some header or introduce a specific method (this requires the Tempesta FW update) to make Tempesta FW just cache the responses and return only status code, without unnecessary headers and body.

This all is too complicated and it's much easier to add a specific header like
```
X-Tempesta-Cache: get
```
which is valid for `PURGE` method only. If the header is present, then Tempesta FW after deletion of the cache entry must send a GET request to the upstream server, cache it and *do not* send body to the client. ~Some of the headers also must be stripped, at least `Set-Cookie`~(this is the subject for #530). This must be a _special_ and _singualr_ header, see [tfw_http_hdr_t](https://github.com/tempesta-tech/tempesta/blob/master/fw/http.h#L182).

The grammar for the header (in terms of RFC 2616 2.1):
```
       X-Tempesta-Cache         = "X-Tempesta-Cache" ":" method

       method                           = "get"
```
At the moment we're going to support only one method for the cache population.

We SHOULD NOT support HTTP/2 for the PURGE logic.

## Testing & documentation 

Develop following functional tests in HTTP/1:

- [x] send `X-Tempesta-Cache` for other method, e.g. GET, and make sure that it doesn't do anything
- [x] Populate the cache with a response body, check that it's in the cache, PURGE the entry, change the response string and resend the request - check that the deproxy server receives the request. Repeat the request and check that the second response string is returned from the cache.
- [ ] use a 3rd string for the response and send PURGE with the header and check that the deproxy server receives the request, but the deproxy client doesn't receive the response body, ~Use `Set-Cookie` in deproxy server and check that the client doesn't receive it~ (this is the subject for #530 ). Resend the request and check that the 3rd version is returned from the cache and the deproxy server doesn't receive the request.
- [ ] Make sure that there is exactly 1 response, not 0 and not more than 1, without body for any PURGE request
- [x] try different values for the `method` parameter, only warning should be printed and the whole header should be just ignored
- [x] ~Test the method rewrite logic for heavily chunked request, preferably to do this test on top of https://github.com/tempesta-tech/tempesta-test/issues/115~ Moved to https://github.com/tempesta-tech/tempesta/issues/810#issuecomment-966690711 since it requires the framework development. Just please test manually for now with `pv`
- [x] Send PURGE with `X-Tempesta-Cache` for an existing cache entry, but generate HTTP response, which doesn't pass `tfw_cache_employ_resp()` (i.e. non-cacheable). Make sure that there is neither the old entry nor the new response in the cache (i.g. following GET goes to the upstream bypassing the cache).
- [x] Send the PURGE with `X-Tempesta-Cache` for a non-cached entry. Make sure that the new cache entry is populated after the request

Besides the functional tests, also please add the appropriate parser test to `fw/t/test_http_parser.c`

Update https://github.com/tempesta-tech/tempesta/wiki/Caching-Responses

**Comment by osevan** [comment]
> The issue requires additional fragmentation API to rewrite request method from `PURGE` to `GET` (let's make it simple for this methods only for now) and removing the response body (seems simple, but still need to do on skb layer), so this task is definitely not good to start from.

Nice intention to do.

I have a question : 

Tempesta kernel 5.10 and latest master module compiling from git ,working already with described steps in "installation from source document"?

Or I need modifications and not mentioned in installation from.source document? 

Thanks and

Best regards

**Comment by krizhanovsky** [comment]
Hi @osevan ,

we do work with Debian 10. You don't need any changes to compile on Debain 10. Also 0.7 will be packaged for Debian 11 https://github.com/tempesta-tech/tempesta/issues/1502

**Comment by krizhanovsky** [comment]
There is an implementation draft in #1518 and the design is well discussed there, so there are only straightforward adjustments are required

**Comment by ad-tmpst** [comment]
I added some tests in https://github.com/tempesta-tech/tempesta-test/pull/193 and ticked the related checkboxes above.

**Comment by krizhanovsky** [comment]
I added description of the logic to https://github.com/tempesta-tech/tempesta/wiki/Caching-Responses#manual-cache-purging
