### ISSUE TITLE
Enhancement possibility to compile with -flto and -fprofile-generate  for LTO and PGO compilation at kernel compiling level. 

### ISSUE THREAD

**Issue by osevan** [tempesta-tech/tempesta#1523]
PGO  trained .gcda  could boost tempestakernel maybe 30 % after profiles generated,because tempesta fw do frequently  repeated operations, and are ideal for PGO (2 times compilations),to reduce context switch and cache misses,when training are done with real world benchmarks like wrk and ddos situations. 

Thanks and

Best Regards

**Comment by krizhanovsky** [comment]
We have played with PGO https://github.com/tempesta-tech/tempesta/pull/1219 . The most performance crucial part is the HTTP parser and while PGO explores hot and cold code paths, it does not account code dependency. You can find more details on the subject in my SCALE x17 talk https://tempesta-tech.com/research/http_str.pdf , slide 27 is about PGO.

We ended up with manual compiler guidance on the proper code layout.
