### ISSUE TITLE
Enhancement try to avoid kmalloc and vmalloc in tempesta fw

### ISSUE THREAD

**Issue by osevan** [tempesta-tech/tempesta#1524]
If possible use scalloc,  Jemalloc, mimalloc ,rpmalloc

For more performance and scaling threads on multicore CPUs  . 

Thanks and

Best Regards

**Comment by krizhanovsky** [comment]
We do our best to avoid memory allocations at all on the hot paths. `vmalloc()` is used on configuration stage only, while the hot paths deals with memory allocations mostly on socket buffer layer using cached page fragments using `pg_skb_alloc()` (see https://github.com/tempesta-tech/tempesta/blob/master/linux-5.10.35.patch#L1375).

Meantime scalloc, Jemalloc, mimalloc ,rpmalloc are user space libraries unavailable in the kernel space.
