### ISSUE TITLE
HTTP parser accidentaly accepts double LF sequence before request line.

### ISSUE THREAD

**Issue by Dmitry-Gouriev** [tempesta-tech/tempesta#1536]
## Scope

This issue continues issue #1061. The problem of #1061 in general is solved in PR #1534.
However the particular case decribed in the SUBJ remains uncovered.
More detailed description is here
https://github.com/tempesta-tech/tempesta/pull/1534#issuecomment-990241035

## Testing

The test suite for processing of preceding CRLF sequences is in
https://github.com/tempesta-tech/tempesta-test
file `malformed/test_malformed_crlfs.py`
(currently in the dg-tests-1061-1535 branch, waiting to be merged into master branch (PR 195)

UPDATE:
Tests for double LF sequence, as well as tests for other cases gathered on the way, are added to
unit test set, so unit tests are now reference tests for this growing case.

**Comment by krizhanovsky** [comment]
It seems the problem exists for HTTP/1 parser only, since H2 does
```C
        __FSM_STATE(Req_MethodUnknown, cold) {
                __fsm_n = __data_remain(p);
                __fsm_sz = tfw_match_token(p, __fsm_n);
                if (likely(__fsm_sz == __fsm_n)) {
```
and we definitely have at least 1 byte if we're in the state.

The task is crucial since we need the parser for an OEM project.

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky 

> I thinks that any character, which isn't in the token alphabet ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#$%&'*+-.^_|~0123456789` and not only LF, will cause the problem.

I feel, we should use more resticted alphabet when parsing a method name.

**Comment by krizhanovsky** [comment]
Please check this against RFC, IIRC it requires this alphabet for methods parsing

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky In this case +GET and PO+T are legal names for unknown advanced methods.
Even we fix `__FSM_MOVE_nofixup` probrm, these names will be acceptable.

**Comment by Dmitry-Gouriev** [comment]
Yes, RFC 7230 states exactly that :'(

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky 
> 
> The `__FSM_MATCH_MOVE_nofixup()` is only used in this one place. I think we should just fix the code in the macro and use it directly in the `Req_MethodUnknown` state, just like h2 parser does this (BTW it seems it does this in the safe and right way):
> 

This will be more clear. However,
I did not found any incorectness with `__FSM_MATCH_MOVE_nofixup()` n my testing.
It returns exactly what was expected.
The bug happens earier.

**Comment by krizhanovsky** [comment]
> I did not find any incorectness with __FSM_MATCH_MOVE_nofixup() in my testing.

How the code handles the case with zero matching bytes returned from `__FSM_MATCH_MOVE_nofixup()`, i.e. where is the mistake in my analysis? Can your tests miss some case, which leads to incorrect functionality of `__FSM_MATCH_MOVE_nofixup()` call?

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky Zero matching: it returns zero and pointer stay at place. Subsequent analysis rejectts the message, in needed.
However if __FSM_MOVE_nofixup eats the problematic character, __FSM_MATCH_MOVE_nofixup counts up to space and the message is accepted.

**Comment by krizhanovsky** [comment]
OK, consider
```
 / HTTP/1.1
Host: foo.com
```
there is no method at all (just a space at the beginning of the message and I believe we'll process the message normally, however we must block it.

I think you're only considering something like
```
} / HTTP/1.1
Host: foo.com
```
In this case `}` will be passed to `Req_MUSpace` state and the request is blocked.

Please review t/unit/test_http_parser.c  for both of the cases (maybe not necessary *these* cases, but the cases utilizing the same workflows of the parser).

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky you are right. Empty method remains uncovered.
Tried just now:
```
.=====test_13_space_hch=====
Sending request----
 / HTTP/1.1
Host: localhost


-------------------
Request forwarded to backend----
 / HTTP/1.1
Host: localhost
X-Forwarded-For: 127.0.0.1
via: 1.1 tempesta_fw (Tempesta FW 0.7.0)
Connection: keep-alive


--------------------------------
*** Expected NONE
Response status:200
*** Expected: 400
.
----------------------------------------------------------------------

```
Anyway, however, this error is in calling code rather than in __FSM_MATCH_MOVE_nofixup().

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky 
For now I made 2 replacements of `__FSM_MOVE_nofixup` with `__FSM_JMP()` ( dg-1536  )
and it seems all the tests passed (in general...).

The changes seems to be ready for pull.
However, there are some questions.

1. `__FSM_MOVE_nofixup` used instead of `__FSM_JMP()` in many places.
Should I make similar replacements in that places as well?
This will require thorough testing to be sure that nothing is broken by the changes.

2. I see rare sporadic faults on various tests. These faults are not connected with particular
tests but jump from one to another. So, it seems, the faults are connected with smth unexpected
in message dynamics rather than with functionality. Probably better to detect a reason of these
faults first? However this can consume a lot of time.

3. I have found that functional tests (python) detects more faults, than unit tests, at least in my case.
It seems, unit tests can not provide 1-byte chunks.

4. Check for zero length method name, as you mentioned above.

**Comment by krizhanovsky** [comment]
> __FSM_MOVE_nofixup used instead of __FSM_JMP() in many places.
> Should I make similar replacements in that places as well?

The main differences between MOVE and JMP mcros is that the first ones eat 1 or more bytes of input data, while the second ones leave the data pointer at the same place and just change the current state. What are the places which must not eat input data?

For (2) we have blonking tests in tempesta-test. I'd recommend at the moment to pay attention only to tests, which cove exactly parser functionality. There are many reasons for blinking tests, e.g. timeouts which might be enough for one cases and not for others. We have issues for the test framework which are still to be fixed.

> It seems, unit tests can not provide 1-byte chunks.

The unit test must check 1-byte chunks. This happens in `do_split_and_parse()` function.

**Comment by Dmitry-Gouriev** [comment]
> What are the places which must not eat input data?

To begin with.
```
431 /* Used for improbable states only, so use cold label. */
  432 #define __FSM_METH_MOVE(st, ch, st_next)                                \
  433 __FSM_STATE(st, cold) {                                                 \
  434         if (likely(c == (ch)))                                          \
  435                 __FSM_MOVE_nofixup(st_next);                            \
  436         __FSM_MOVE_nofixup(Req_MethodUnknown);                          \
  437 }
  438
  439 #define __FSM_METH_MOVE_finish(st, ch, m_type)                          \
  440 __FSM_STATE(st, cold) {                                                 \
  441         if (unlikely(c != (ch)))                                        \
  442                 __FSM_MOVE_nofixup(Req_MethodUnknown);                  \ /*****/
  443         req->method = (m_type);                                         \
  444         __FSM_MOVE_nofixup(Req_MUSpace);                                \
  445 }

```
Then
```
4452         __FSM_STATE(Req_MethP, cold) {
 4453                 switch (c) {
 4454                 case 'O':
 4455                         __FSM_MOVE_nofixup(Req_MethPo);
 4456                 case 'A':
 4457                         __FSM_MOVE_nofixup(Req_MethPa);
 4458                 case 'R':
 4459                         __FSM_MOVE_nofixup(Req_MethPr);
 4460                 case 'U':
 4461                         __FSM_MOVE_nofixup(Req_MethPu);
 4462                 }
 4463                 __FSM_MOVE_nofixup(Req_MethodUnknown); /******/
 4464         }
```
Also
```
 4482                 __FSM_MOVE_nofixup(Req_MethodUnknown);
```
```
 4503                 __FSM_MOVE_nofixup(Req_MethodUnknown);
```
```
4534                 __FSM_MOVE_nofixup(Req_MethodUnknown);
```
and so on. The same things I see in non-chunked part of the parser.

**Comment by Dmitry-Gouriev** [comment]
> The unit test must check 1-byte chunks. This happens in do_split_and_parse() function.
But this is a pseudo-random process, so may be it make and may be do not make :)
At least, the python test with hardcoded 1-byte chunk messages detects fault where unit test do not.

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky 

> OK, consider
> 
>  / HTTP/1.1
> Host: foo.com
> there is no method at all (just a space at the beginning of the message and I believe we'll process the message normally, however we must block it.

Now I am thinkng about, how to block requests with zero-length method name.
For now, I have no any working idea... :(

**Comment by krizhanovsky** [comment]
Dmitry, good catch! `__FSM_METH_MOVE()` and `__FSM_METH_MOVE_finish()` really accept `G{T` or `GE}` as unknown methods. The places https://github.com/tempesta-tech/tempesta/issues/1536#issuecomment-993754917 should be replaces with `__FSM_JMP()`.

Please make a pull request.

**Comment by Dmitry-Gouriev** [comment]
@krizhanovsky it seems the code is not ready for PR yet.
you can explore changes in [https://github.com/tempesta-tech/tempesta/tree/dg-1536](https://github.com/tempesta-tech/tempesta/tree/dg-1536)

**Comment by krizhanovsky** [comment]
Sure. Work on the code and when you feel that it's ready and/or there are certain design questions to be discussed, publish the PR. If it's unfinished, then mark it as Draft.

**Comment by Dmitry-Gouriev** [comment]
> Implemented chunking model based on fixed chunk size list.
> The only 1 additional test fails: **fills_hdr_tbl_for_req**.
> This failure is left for further study (probably outside this issue).
> More details are [here](https://github.com/tempesta-tech/tempesta/commit/35d46bb53c92dd11b4e67a95401e55e6142e12d4#commitcomment-61969391)
> 

### Results of additional investigation of the case.

Parser for the Contant-Type returns incorrect header contant in case, when chunk size is > 16 bytes.

Additionaly, the test **fills_hdr_tbl_for_req** and similar test **fills_hdr_tbl_for_resp** have a serios defect:
At the first step the test call the message parsing test, which iterates over various chunk sizes,
and at the second step the test compares contents of parsed headers with expected ones,
so that the only result of the last iteration over chunk sizes is compared with expected content of the headers.
The older chunking procedure based on PRIMES walks from large chunks to small ones, and the test succeed,
whereas the newer chunking procedure based on fixed CHUNK_SIZES list walks from small chunks to large ones,
and the test fails.

This could be a subject of separate issue. The problem could be stated as follows.
1. Debug the parser for Content-Type header, make it able to work with large input chunks.
2. Improve the tests **fills_hdr_tbl_for_req** and **fills_hdr_tbl_for_resp** to check parsed headers against expected ones in every iteration over various chunk size.
3. (optional?) Get rid of older chunking procedure based on PRIMES.

**Comment by Dmitry-Gouriev** [comment]
> Results of additional investigation of the case.

The case is moved into separate issue [https://github.com/tempesta-tech/tempesta/issues/1537](https://github.com/tempesta-tech/tempesta/issues/1537)

**Comment by Dmitry-Gouriev** [comment]
Soulutions of this issue submitted with PR #1538
