### ISSUE TITLE
H2-request with http-scheme not blocked by hpack parser

### ISSUE THREAD

**Issue by alegz-filomaphitskay** [tempesta-tech/tempesta#1614]
The request below with http-scheme not blocked as expected (at now only http**S**-scheme is supported):
```
	EXPECT_BLOCK_REQ_H2(
	    HEADERS_FRAME_BEGIN();
		// :method = "GET"
		HEADER(INDEX(2));
		// :scheme = "http"
		HEADER(INDEX(6));
		// :path = "/"
		HEADER(INDEX(4));
	    HEADERS_FRAME_END();
	);
```

See TODO in t/unit/test_http2_parser.c

**Comment by krizhanovsky** [comment]
There is no big issue if we accept `http` scheme for HTTP/2. Meantime this is handled by static table on HTPACK layer and we'd need to introduce relatively heavyweight checks on http limits layer.
