### ISSUE TITLE
Handling non-idempotent requests in HTTP/2

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1619]
# Scope

The `TFW_HTTP_B_NON_IDEMP` is set in `tfw_h1_req_process()` -> `tfw_http_req_add_seq_queue()` -> `tfw_http_req_mark_nip()`, i.e. for HTTP/1 only while we do proxy HTTP/2 requests over HTTP/1 backend connections.

# Testing

Extend `pipelining/test_pipelining.py` with the scenario for HTTP/2

**Comment by const-t** [comment]
Also, maybe need we to send `REFUSED_STREAM` error when failed request forwarding if `server_retry_nonidempotent` is not set?

RFC 9113 8.7 Request Reliability:
> The REFUSED_STREAM error code can be included in a RST_STREAM frame to indicate that the stream is being closed prior to any processing having occurred. Any request that was sent on the reset stream can be safely retried.
