### ISSUE TITLE
Unify HTTP/1 `req->host` and HTTP/2 `:authority` processing

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1630]
At the moment we store URI authority part in `req->host` for HTTP/1, but we have a designated `TFW_HTTP_HDR_H2_AUTHORITY` special header for HTTP/2 for `:authority`. This complicates the logic (e.g. see https://github.com/tempesta-tech/tempesta/pull/1629#discussion_r880487824 discussion). Need to store URI authority for HTTP/1 in the special header, just as we do this for HTTP/2, and adjust all the places processing `req->host`.

No need any special testing - these changes are well covered by the existing test suite.

**Comment by const-t** [comment]
Current issue may contribute to https://github.com/tempesta-tech/tempesta/issues/1630

**Comment by RomanBelozerov** [comment]
If send h2 request with `host: ' (empty), we will receive response status code - 400 and `Warning: failed to parse request`. #1705 hides warning. 
But http 1.1 request will be processed successfully.

**Comment by krizhanovsky** [comment]
Please also fix https://github.com/tempesta-tech/tempesta/wiki/HTTP-tables

> `host` - the host part from URI in HTTP request line, or the value of "Host" header field or value of "host" parameter from "Forwarded" header field. The Host part in URI takes priority over the Host header field value and "host" parameter from "Forwarded" header.

Which makes false statement about URI priority over `Host` header value and does not consider http2. See better description for `http_host_required` in https://github.com/tempesta-tech/tempesta/wiki/HTTP-security
