### ISSUE TITLE
Kernel crash on ws.test_ws_ping.CacheTest.test_ping_websockets

### ISSUE THREAD

**Issue by pale-emperor** [tempesta-tech/tempesta#1647]
# Steps to reproduce

Run tests couple of times:

```
for i in `seq 40`; do ./run_tests.py ws.test_ws_ping.CacheTest.test_ping_websockets; done
```

Result:

Kernel panic and reboot

**Comment by pale-emperor** [comment]
DMESG

[   73.074562] Start test: ws.test_ws_ping.CacheTest.test_ping_websockets
[   73.136746] [tdb] Start Tempesta DB
[   73.153563] [tempesta fw] Initializing Tempesta FW kernel module...
[   73.221991] [tempesta fw] Configuration processing is completed.
[   73.242323] [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=000000007a36f7b5
[   73.309753] [tdb] Opened table /opt/tempesta/db/cache0.tdb: size=268435456 rec_size=0 base=000000005ebb1814
[   73.314848] [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=000000003b67df5e
[   73.319858] [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=000000008efba8a1
[   73.425914] [tempesta fw] Open listen socket on: 0.0.0.0:82
[   73.426520] [tempesta fw] Open listen socket on: 0.0.0.0:81
[   73.553889] [tempesta fw] Tempesta FW is ready
[   73.582015] [tempesta fw] 127.0.0.1 "localhost" "GET / HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
[   75.538030] net_ratelimit: 24 callbacks suppressed
[   75.538032] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.538938] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.539365] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.539781] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.540183] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.540581] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.540963] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.541337] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.541703] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   75.542102] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   79.634057] [tempesta fw] 127.0.0.1 "localhost" "GET / HTTP/1.1" 504 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
[   79.769808] [tdb] Close table 'client0.tdb'
[   79.777688] [tdb] Close table 'sessions0.tdb'
[   79.880538] [tdb] Close table 'cache0.tdb'
[   80.001779] [tdb] Close table 'filter0.tdb'
[   80.143347] [tempesta fw] exiting...
[   80.336119] [tdb] Shutdown Tempesta DB
[   80.528215] End test:   ws.test_ws_ping.CacheTest.test_ping_websockets

[   89.415482] Start test: ws.test_ws_ping.CacheTest.test_ping_websockets
[   89.531377] [tdb] Start Tempesta DB
[   89.570142] [tempesta fw] Initializing Tempesta FW kernel module...
[   89.750118] [tempesta fw] Configuration processing is completed.
[   89.882704] [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=000000007a36f7b5
[   89.955027] [tdb] Opened table /opt/tempesta/db/cache0.tdb: size=268435456 rec_size=0 base=000000005ebb1814
[   89.959940] [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=000000003b67df5e
[   89.964776] [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=000000008efba8a1
[   89.965235] [tempesta fw] Open listen socket on: 0.0.0.0:82
[   89.965649] [tempesta fw] Open listen socket on: 0.0.0.0:81
[   90.109979] [tempesta fw] Tempesta FW is ready
[   90.232295] [tempesta fw] 127.0.0.1 "localhost" "GET / HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
[   92.178146] net_ratelimit: 24 callbacks suppressed
[   92.178148] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.179232] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.179662] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.180081] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.180490] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.180886] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.181274] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.181652] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.182043] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   92.182411] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8099: 6 tries, keep trying...
[   96.274170] [tempesta fw] 127.0.0.1 "localhost" "GET / HTTP/1.1" 504 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
[   96.409659] [tdb] Close table 'client0.tdb'
[   96.418023] [tdb] Close table 'sessions0.tdb'
[   96.523863] [tdb] Close table 'cache0.tdb'
[   96.721999] [tdb] Close table 'filter0.tdb'
[   96.859457] [tempesta fw] exiting...
[   97.064411] [tdb] Shutdown Tempesta DB
[   97.254755] End test:   ws.test_ws_ping.CacheTest.test_ping_websockets

[   98.973121] Start test: ws.test_ws_ping.CacheTest.test_ping_websockets
[   99.085391] [tdb] Start Tempesta DB
[   99.102080] [tempesta fw] Initializing Tempesta FW kernel module...
[   99.302157] [tempesta fw] Configuration processing is completed.
[   99.438563] [tdb] Opened table /opt/tempesta/db/filter0.tdb: size=16777216 rec_size=20 base=000000007a36f7b5
[   99.507569] [tdb] Opened table /opt/tempesta/db/cache0.tdb: size=268435456 rec_size=0 base=000000005ebb1814
[   99.512988] [tdb] Opened table /opt/tempesta/db/sessions0.tdb: size=16777216 rec_size=312 base=000000003b67df5e
[   99.518426] [tdb] Opened table /opt/tempesta/db/client0.tdb: size=16777216 rec_size=624 base=000000008efba8a1
[   99.662006] [tempesta fw] Open listen socket on: 0.0.0.0:82
[   99.718264] [tempesta fw] Open listen socket on: 0.0.0.0:81
[   99.902030] [tempesta fw] Tempesta FW is ready
[   99.925896] [tempesta fw] 127.0.0.1 "localhost" "GET / HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"

**Comment by krizhanovsky** [comment]
The appropriate test from tests_disabled.json fails

**Comment by avbelov23** [comment]
Race example
The client connection is destroyed, and at this time `tfw_ws_msg_process()` is called on the server connection and accesses the client connection
```
[  286.890412] [tempesta fw]     tfw_ws_srv_new_steal_sk: conn=[00000000975eb662]
[  286.890956] [tempesta fw]     tfw_ws_conn_alloc: conn=[00000000a7fc873c]
[  286.891518] [tempesta fw]       [3]: ss_do_send: sk=00000000aad8e500 queue_empty=1 send_head=0000000000000000 sk_state=1 mss=32768 size=32768
[  286.892471] [tempesta fw]       [3]: ss_do_send: entail sk=00000000aad8e500 skb=000000007f2cb9c2 data_len=343 len=343 truesize=1423 mark=0 tls_type=0
[  286.893492] [tempesta fw]       [3]: ss_do_send: sk=00000000aad8e500 send_head=000000007f2cb9c2 sk_state=1 flags=0
[  286.894492] [tempesta fw]       [3]: ss_tcp_state_change: sk=00000000c994882b state=Established
[  286.894679] [tempesta fw]       [2]: ss_tcp_data_ready: sk=00000000f220d9ff state=Established
[  286.895302] [tempesta fw]   connected: 127.0.0.1:8099
[  286.895961] [tempesta fw]       [1]: ss_tcp_state_change: sk=00000000aad8e500 state=Close Wait
[  286.895964] [tempesta fw]     Received data FIN on sk=00000000aad8e500, cpu=1
[  286.895967] [tempesta fw]     [1]: Peer connection closing
[  286.895970] [tempesta fw]       [1]: ss_tcp_data_ready: sk=00000000aad8e500 state=Close Wait
[  286.895976] [tempesta fw]     [1]: Close socket 00000000aad8e500 (Close Wait): account=1 refcnt=5
[  286.895987] [tempesta fw]     connection lost: close client socket: sk=00000000aad8e500, conn=00000000b5e955a9, client=0000000001a7f114
[  286.895990] [tempesta fw]   tfw_ws_conn_drop: conn=[00000000b5e955a9]
[  286.895992] [tempesta fw]   tfw_ws_conn_close: conn=[00000000a7fc873c]
[  286.896002] [tempesta fw]     put client 0000000001a7f114, users=2
[  286.896491] [tempesta fw]     tfw_ws_msg_process: conn=[00000000a7fc873c], skb=[0000000022408a28]
```

**Comment by krizhanovsky** [comment]
With the last patches in #1786 a multi-cpu scenario still leads to crash, e.g.
```
[   97.223651] [tempesta fw]     tfw_ws_srv_new_steal_sk cpu/3: conn=000000005cfdcf14
[   97.227013] [tempesta fw]     tfw_ws_conn_alloc cpu/3: conn=000000004fb4e4f5
[   97.230208] [tempesta fw] 127.0.0.1 "localhost" "GET / HTTP/1.1" 101 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
[   97.236768] [tempesta fw]     tfw_ws_conn_send cpu/3: conn=0000000097a2fc60, msg=000000008db2a9b7
[   97.240838] [tempesta fw]     tfw_ws_msg_process cpu/1: conn=000000004fb4e4f5 -> conn=0000000097a2fc60, skb=000000001b7eff27
[   97.241655] [tempesta fw]   tfw_ws_conn_drop cpu/0: conn=0000000097a2fc60
[   97.242520] ==================================================================
[   97.245819] [tempesta fw]   tfw_ws_conn_close cpu/0: conn=000000004fb4e4f5
[   97.247278] BUG: KASAN: null-ptr-deref in tfw_connection_send+0x13/0x60 [tempesta_fw]
[   97.252381] Read of size 4 at addr 0000000000000008 by task python3/1701
[   97.254072]
[   97.255572] CPU: 1 PID: 1701 Comm: python3 Tainted: G           O      5.10.35-kdump+ #17
[   97.257592] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.15.0-1 04/01/2014
[   97.259480] Call Trace:
[   97.261083]  <IRQ>
[   97.262590]  dump_stack+0x7d/0xa3
[   97.264167]  ? tfw_connection_send+0x13/0x60 [tempesta_fw]
[   97.265850]  kasan_report.cold+0x5/0x37
[   97.267472]  ? tfw_connection_send+0x13/0x60 [tempesta_fw]
[   97.269167]  tfw_connection_send+0x13/0x60 [tempesta_fw]
[   97.270899]  tfw_ws_msg_process+0x15a/0x4da [tempesta_fw]
[   97.272836]  ? tfw_http_websocket_upgrade.cold+0x20e/0x20e [tempesta_fw]
[   97.274684]  ? kfree_skbmem+0x3c/0x2b0
[   97.276382]  ? ss_skb_unroll+0x3d2/0x550 [tempesta_fw]
[   97.278126]  tfw_connection_recv+0xcf/0xe0 [tempesta_fw]
[   97.279916]  ss_tcp_process_skb.constprop.0+0x280/0x470 [tempesta_fw]
[   97.281758]  ? ss_conn_drop_guard_exit+0x70/0x70 [tempesta_fw]
[   97.283602]  ss_tcp_process_data+0x137/0x290 [tempesta_fw]
[   97.285462]  ? ss_tcp_process_skb.constprop.0+0x470/0x470 [tempesta_fw]
[   97.287409]  ss_tcp_data_ready+0x6c/0xf0 [tempesta_fw]
[   97.289280]  tcp_rcv_established+0x933/0xb40
[   97.291093]  ? tcp_data_queue+0xa40/0xa40
[   97.292919]  ? bpf_get_listener_sock+0x40/0x80
[   97.294772]  tcp_v4_do_rcv+0x24a/0x340
```

This could be fixed by acquiring `conn->pair->sk->sk_lock` in `tfw_ws_conn_unpair()` to make sure that nobody uses our pair - having that the current socket on `conn` is dead since `conn_drop` hook is called, this should be save.

However, technically concurrent connection drops may happen for both the paired connections, leading to crash at least in `tfw_ws_conn_unpair()`, which isn't protected by any locks. In general, it's quite an issue that `connection_drop` hooks called from the socket layer are called unlocked...

Probably, there is a websocket architecture issue thta `connection_drop` hook (designated to be an upcall) is just a wrapper for `conn_drop` (designated to be a downcall).

**Comment by krizhanovsky** [comment]
fixed in https://github.com/tempesta-tech/tempesta/pull/1797
