### ISSUE TITLE
apparmor module loading with security default tempesta not possible 

### ISSUE THREAD

**Issue by osevan** [tempesta-tech/tempesta#1653]
Can we load apparmor as module plus apparmor filesystem mount equal time with tempesta? 

If yes how to do it? 

Boot flag  already set : apparmor=1 security=1

But apparmor filesystem can't load according

aa-status

If not possible why? 

Thanks an

 best regards

**Comment by osevan** [comment]
Need i do
Config_default_security _apparmor=y ?

When i run parallel security modules?

**Comment by krizhanovsky** [comment]
Hi @osevan ,

you should be able to use apparmor together with Tempesta FW. Consider as an example the config from my VM:
```bash
~/linux-5.10.35-tfw# grep -i 'apparmor\|tempesta' .config
CONFIG_SECURITY_APPARMOR=y
CONFIG_SECURITY_APPARMOR_HASH=y
CONFIG_SECURITY_APPARMOR_HASH_DEFAULT=y
# CONFIG_SECURITY_APPARMOR_DEBUG is not set
CONFIG_SECURITY_TEMPESTA=y
CONFIG_DEFAULT_SECURITY_TEMPESTA=y
# CONFIG_DEFAULT_SECURITY_APPARMOR is not set
CONFIG_LSM="tempesta,lockdown,yama,loadpin,safesetid,integrity,selinux,smack,tomoyo,apparmor,bpf"

~/linux-5.10.35-tfw# grep -c apparmor /proc/kallsyms 
103

~/linux-5.10.35-tfw# uname -a
Linux ubuntu 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by osevan** [comment]
CONFIG_SECURITY_APPARMOR=y
CONFIG_SECURITY_APPARMOR_HASH=y
CONFIG_SECURITY_APPARMOR_HASH_DEFAULT=y


This is already in my config. 


But apparmor fs cant mounting  at restart according aa-status

**Comment by osevan** [comment]
And inside securityfs

/sys/kernel/security/ no apparmor inside

**Comment by osevan** [comment]
Journalctl spits out : 

Systemd: condition check  resulted  in load apparmor  profiles beimg skipped.

**Comment by osevan** [comment]
Debian 11 Like developers machine i have. 


On stock kernel,  Apparmor starting well, and i can see Apparmor in /sys/kernel/security/.


But,  not with tempesta kernel booted

**Comment by pale-emperor** [comment]
@osevan Hi there!

1. Please ensure you add following flags /boot/grub/grub.cfg
`GRUB_CMDLINE_LINUX_DEFAULT=".............. apparmor=1 lsm=lockdown,yama,apparmor"`

2. Run 
apt install apparmor-profiles -y
update-grub
reboot

If apparmor still not working - provide result of command below:
`journalctl --all | grep 'AppArmor'`

**Comment by osevan** [comment]
My apparmor working now wonderfully .

Thanks and


Best regards...
