### ISSUE TITLE
non-idempotent requests caching

### ISSUE THREAD

**Issue by nickzaev** [tempesta-tech/tempesta#1663]
During development of a functional test for cache policies enforcement within `location` directives, I've discovered that we cache non-idempotent request, i.e. with this config:

```
server ${server_ip}:8000;
vhost default {
    proxy_pass default;

    location prefix "/cached" {
        proxy_pass default;
        cache_fulfill * *;
    }

    location prefix "/bypassed" {
        proxy_pass default;
        cache_bypass * *;
    }
    location prefix "/nonidempotent" {
        proxy_pass default;
        cache_fulfill * *;
        nonidempotent GET * *;
        nonidempotent HEAD * *;
    }
}
```
`GET` requests to `/nonidempotent` do get cached, but apparently `HEAD` ones do not.
See https://github.com/tempesta-tech/tempesta-test/pull/244#discussion_r917464395

**Comment by krizhanovsky** [comment]
Related issue #1995
