### ISSUE TITLE
Frang: tls_connection_burst does not work as expected

### ISSUE THREAD

**Issue by ProshNad** [tempesta-tech/tempesta#1716]
# Motivation
All tests should work
# Scope
The limit currently works in such a way that there must always be at least 125 ms between a new connection and the previous one, which is not consistent with the documentation. The essence of the limit is to limit a certain number of connections in the interval of 125 ms. This does not mean that there should be 125ms between each connection. There can be 10ms between connections and this shouldn't be a problem as long as there are less than the set number of connections in 125ms.
# Testing

To reproduce the bug, you can use tests
t_frang.test_tls_rate_burst.FrangTlsRateBurstTestCase.test_tls_connection_burst_without_reaching_the_limit
t_frang.test_tls_rate_burst.FrangTlsBurstTestCase.test_tls_connection_burst_without_reaching_the_limit
 that are currently disabled.

# Documentation
https://github.com/tempesta-tech/tempesta/wiki/HTTP-security#:~:text=tls_connection_burst%20%5BNUM%5D%0Adisable%20the%20limit.%0AMaximum%20burst%20of%20new%20TLS%20sessions%20rate%20on%20short%20periods%20of%20time%20(125%20ms).%20The%20option%20can%20be%20used%20independently%20from%20tls_connection_rate%20limit.%200%20to%20Defaults%3A%200%20(disabled).

**Comment by voodam** [comment]
https://github.com/tempesta-tech/tempesta-test/pull/486
https://github.com/tempesta-tech/linux-5.10.35-tfw/pull/16
https://github.com/tempesta-tech/tempesta/pull/1925

**Comment by voodam** [comment]
Done with a lot of extra work in tempesta-test. Also https://github.com/tempesta-tech/tempesta/issues/1751 part (proper reset TCP connections with RST) is done here.
