### ISSUE TITLE
Frang: http_host_required, http2 header :authority

### ISSUE THREAD

**Issue by ProshNad** [tempesta-tech/tempesta#1717]
# Motivation
All tests should work

# Scope
For http2 requests, the :authority: header is ignored. Although according to the documentation it should be checked.

# Testing

I'm expecting an error in  t_frang.test_host_required.FrangHostRequiredH2TestCase.test_h2_host_header_authority test, but it doesn't happen. The test is disabled now.

# Documentation

https://github.com/tempesta-tech/tempesta/wiki/HTTP-security#:~:text=http_host_required%20%5Btrue%7Cfalse%5D

**Comment by const-t** [comment]
The test is not suitable to test `:authority`, see my [cooment](https://github.com/tempesta-tech/tempesta-test/pull/265/files#r994465188). However, we need to investigate what goes wrong. If I correct and curl just adds `:authority` to the end of headers, Tempesta must block such request. Pseudo-headers MUST be in head of headers, they can't be placed after regular headers.

**Comment by ProshNad** [comment]
not tempesta bug

**Comment by krizhanovsky** [comment]
Reopen to not to lose the issue

**Comment by ProshNad** [comment]
So, after doing some analysis of the tests, I came to the conclusion that the tests 
 - t_frang.test_host_required.FrangHostRequiredH2TestCase.test_h2_host_header_mismatch
 - t_frang.test_host_required.FrangHostRequiredH2TestCase.test_h2_host_header_authority
 should be rewritten, because curl automatically sets the necessary values for pseudo headers, like `:authority:`
 It should be noted that for HTTP2 testing it is better to use deproxy_h2
