### ISSUE TITLE
Frang: http_ct_vals does not work with text/*

### ISSUE THREAD

**Issue by ProshNad** [tempesta-tech/tempesta#1720]
# Motivation

tests should work

# Scope

configuration 
```
frang_limits {
    http_ct_vals text/*;
}
```
should work with values text/html and text/plain but now it's not like that

# Testing
use test t_frang.test_http_ct_vals.FrangHttpCtValsTestCase.test_content_vals_set_ok_conf2

# Documentation
https://github.com/tempesta-tech/tempesta/wiki/HTTP-security#:~:text=get%20post%20head%3B-,http_ct_vals,-%5B%22CONTENT_TYPE%22%5D...%0AThe

**Comment by RomanBelozerov** [comment]
Invalid. Documentation:

>   Note that the full types must be specified, i.e. if you need to allow text/html and text/plain, then you should specify http_ct_vals "text/plain" "text/html", http_ct_vals "text/*" won't match the required values.
