### ISSUE TITLE
Frang: concurrent_connections 

### ISSUE THREAD

**Issue by ProshNad** [tempesta-tech/tempesta#1723]
# Motivation
all tests must pass

# Scope

If ip_block is disabled by default, then all clients, even if they have the same ip, should not be blocked (correct?). And all clients should get answers. Or, if clients must be blocked, then all clients must be blocked. However, this is not the case in my test. As a result, only two clients receive responses, but none of them is blocked.

# Testing
use test **t_frang.test_concurrent_connections.ConcurrentConnections.test_three_clients_one_ip**

# Documentation

https://github.com/tempesta-tech/tempesta/wiki/HTTP-security#:~:text=0%20(disabled).-,concurrent_connections,-%5BNUM%5D%0AMaximum

**Comment by RomanBelozerov** [comment]
> If ip_block is disabled by default, then all clients, even if they have the same ip, should not be blocked (correct?). 

correct

> And all clients should get answers. Or, if clients must be blocked, then all clients must be blocked.

incorrect

For three clients with same IP and Tempesta config:
```
frang_limits {
    concurrent_connections 2;
}
```
Only two clients will establish connections, and last one will not be serviced. This test works correctly.
