### ISSUE TITLE
Incorrect initializing of parser state while decoding full indexed hpack headers

### ISSUE THREAD

**Issue by const-t** [tempesta-tech/tempesta#1735]
For full indexed header we calling tfw_hpack_hdr_set where coping already parsed value to currently parsing header, therefore parsing functions will not be called and parser state for current request will not be properly initialized. We handle such cases now for Host and If-Modified-Since, but not for other headers. Also handling it in such way not looks correctly, because of calling parsing functions directly from hpack. It's not a problem for one request, but it is a problem for multiplexed requests, because single hpack context used for whole connection and all requests/responses in it. For instance we have two such requests in single connection:
```
':authority', 'localhost:81'
':path', '/'
':scheme', 'https'
':method', 'GET'
```

for first request `TfwHttpReq.req_host_port` will be 81, for second it will be 0. This applies to any other header during parsing which we change state of parser or request.

# Testing
Need to develop test using response from example.

**Comment by krizhanovsky** [comment]
Done in #1835
