### ISSUE TITLE
Forwarding http2 splitted cookie header for

### ISSUE THREAD

**Issue by const-t** [tempesta-tech/tempesta#1736]
# Scope

We allow splitted cookie header for http2, but we MUST not send it to http1 server. See RFC 9113 8.2.3 and RFC 6265 5.4.

> If there are multiple Cookie header fields after decompression, these MUST be concatenated into a single octet string using the two-octet delimiter of 0x3b, 0x20 (the ASCII string "; ")

# Testing
Need to develop functional test which will verify that splitted cookie from HTTP2 client forwards to HTTP1 as single header.

**Comment by dmpetroff** [comment]
Fixed in #1895
