### ISSUE TITLE
update frang documentation

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1741]
# Motivation

Please,  add more information to `frang` documentation on working with `ip_block` and `block_action` directives.
Also, for the `block_action` directive I don't understand what event will call 'frang' with `ip_block on\off`. I think, it's "attack", but it's not written.

For example:
what should client receive on 3rd connection?
1. `ip_block off; connection_burst 2; block_action attack reply;` -  403 or not?
2. `ip_block off; connection_burst 2; block_action attack drop;` - none?
3. `ip_block on; connection_burst 2; block_action attack drop;` - none? 
4. `ip_block on; connection_burst 2; block_action attack reply;` - three 403 responses?

# Documentation

https://github.com/tempesta-tech/tempesta/wiki/HTTP-security

**Comment by krizhanovsky** [comment]
@RomanBelozerov I updated the page https://github.com/tempesta-tech/tempesta/wiki/HTTP-security - please review whether it is clear and answers all the questions.

Answers to the 4 questions above according to the new doc and https://github.com/tempesta-tech/tempesta/issues/1751:

> 1. `ip_block off; connection_burst 2; block_action attack reply;` -  403 or not?

Connection is just reset (RST), so no any responses - there is nowhere to send the response

> 2. `ip_block off; connection_burst 2; block_action attack drop;` - none?

The same, just reset connection

> 3. `ip_block on; connection_burst 2; block_action attack drop;` - none? 

Connection reset and the IP is blocked.

> 4. `ip_block on; connection_burst 2; block_action attack reply;` - three 403 responses?

Connection reset and the IP is blocked. Nothing is sent to the client
