### ISSUE TITLE
Decryption failed or bad record mac

### ISSUE THREAD

**Issue by const-t** [tempesta-tech/tempesta#1756]
# Scope
Faced `curl: (56) OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0` when sending parallel http2 requests by curl or via h2load when tempesta config contained `resp_hdr_set` directive.

# Testing
```
listen 443 proto=h2;
listen 80;

# Allow only following characters in URI (no '%'): /a-zA-Z0-9&?:-._=
http_uri_brange 0x2f 0x41-0x5a 0x61-0x7a 0x30-0x39 0x26 0x3f 0x3a 0x2d 0x2e 0x5f 0x3d;

srv_group default {
    server 127.0.0.1:8080 conns_n=16;
}

vhost debian {

    proxy_pass default;

    tls_certificate /etc/tempesta/tfw-root.crt;
    tls_certificate_key /etc/tempesta/tfw-root.key;
    resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains";
}

cache 0;
cache_fulfill * *;
block_action attack reply;

http_chain {
  -> debian;
}
```
Command: `curl -k --parallel --parallel-immediate https://debian https://debian https://debian https://debian`

**Comment by krizhanovsky** [comment]
@const-t can you add the description of the error itself?

**Comment by krizhanovsky** [comment]
Relates to #1669
