### ISSUE TITLE
frang: `client_body_timeout` and `client_header_timeout` does not work as expected

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1762]
# Scope

For Tempesta config:
```python
frang_limits {
    client_header_timeout 1;
    ip_block off;
}
block_action attack reply;
```

1. make request which does not contain all headers and empty string. For example `"POST / HTTP/1.1\r\nHost: debian\r\n"`;
2. wait more than 1 sec.;

AR: Tempesta is waiting for rest of request.
ER: Tempesta resets connection after 1 sec.

# Testing

Test to [reproduce.](https://github.com/tempesta-tech/tempesta-test/blob/11e9ae5034a41870194307e256bf568bfefe97cb/t_frang/test_client_body_and_header_timeout.py#L52)

**Comment by RomanBelozerov** [comment]
It also does not work for H2.

**Comment by EvgeniiMekhanik** [comment]
Fix tests and add better description for this frang options to wiki
