### ISSUE TITLE
Can't delete len=1 from skb

### ISSUE THREAD

**Issue by const-t** [tempesta-tech/tempesta#1782]
# Scope

During benchmarking tempesta HTTP/1.1 I've faced such warning `Warning: Can't delete len=1 from skb=00000000f39542ff`

Reproduce with: `h2load -c100 -m100 --duration=30 -t2 --npn-list=http/1.1 https://debian` Try with cache and without

# Testing
We have `wrk` in our test suite and need to find out why `wrk` doesn't cause this warning.

**Comment by EvgeniiMekhanik** [comment]
I can't reproduce this bug

**Comment by const-t** [comment]
I can't reproduce also

**Comment by EvgeniiMekhanik** [comment]
https://github.com/tempesta-tech/tempesta/commit/969a71977f4f5e7596154d8ca0693e8b357f5a8c and https://github.com/tempesta-tech/tempesta/commit/ecda98c57974f919790cdfe19b5023debf823592 fix this bug
