### ISSUE TITLE
Get an error when include !include /etc/tempesta/sites/*

### ISSUE THREAD

**Issue by DevTom811** [tempesta-tech/tempesta#1791]
Hi,

i add !include /etc/tempesta/sites/* in my config and then i got an error 
[95224.669456] [tempesta fw] ERROR: the first character is not a letter: '!'
[95224.669461] [tempesta fw] ERROR: syntax error
[95224.669465] [tempesta fw] ERROR: configuration parsing error:
                  4: !include /etc/tempesta/sites/*

**Comment by krizhanovsky** [comment]
Hi @DevTom811 ,

thank you for the issue report. May I ask you to post the full configuration file that we can try it to reproduce the bug and debug it?

**Comment by DevTom811** [comment]
> Hi @DevTom811 ,
> 
> thank you for the issue report. May I ask you to post the full configuration file that we can try it to reproduce the bug and debug it?

listen 10.0.0.1:443 proto=https;
access_log on;
!include /etc/tempesta/sites/*

srv_group domain {
    server 10.0.0.1:3000 conns_n=4;
}


vhost domain {

    tls_certificate /etc/letsencrypt/live/domain/cert.pem;
    tls_certificate_key /etc/letsencrypt/live/domain/privkey.pem;
    resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains";

    proxy_pass domain;
    sticky {
        cookie name=domain enforce max_misses=3 timeout=3;
    }
}

frang_limits {
    http_header_chunk_cnt 10;
    http_body_chunk_cnt 30;
    client_header_timeout 10;
    client_body_timeout 25;
    http_host_required;
}

cache 1;
cache_fulfill * *;

keepalive_timeout 50;


http_chain {
    -> domain;
}

**Comment by DevTom811** [comment]
@krizhanovsky already test my config?

**Comment by DevTom811** [comment]
Already test my config @krizhanovsky ?

**Comment by krizhanovsky** [comment]
Hi @DevTom811 ,

may I know how to you run Tempesta FW? Do you use `tempesta.sh` script for this like `./tempesta/scripts/tempesta.sh --start`? If yes, then is the script of the last version, in particular can you check that it has function `templater()`, like `grep 'templater()' tempesta/scripts/tempesta.sh`?

The script `tempesta.sh` resolves all the `!include` directives in the configuration file and generate a new temporary file with the files' content included and start Tempesta FW with the generated file. Apparently, Tempesta FW loads the configuration file as is, without content of the included `/etc/tempesta/sites/*` files. I suppose that either there is some bug in the script or something is wrong with the startup process.

@pale-emperor I'm assigning you to the issue as well. Do you have an idea which information about the target system may help us to debug the problem?

**Comment by pale-emperor** [comment]
Hi @DevTom811 i running tempesta-fw with some fixes in your config to avoid some problems with certificates and ssl configfuration:
1. Comment certificate lines
2. Remove https protocol

```
listen 10.0.0.1:80;
access_log on;
!include /etc/tempesta/sites/*

srv_group domain {
server 10.0.0.1:3000 conns_n=4;
}

vhost domain {

#tls_certificate /etc/letsencrypt/live/domain/cert.pem;
#tls_certificate_key /etc/letsencrypt/live/domain/privkey.pem;
resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains";

proxy_pass domain;
sticky {
    cookie name=domain enforce max_misses=3 timeout=3;
}

}

frang_limits {
http_header_chunk_cnt 10;
http_body_chunk_cnt 30;
client_header_timeout 10;
client_body_timeout 25;
http_host_required;
}

cache 1;
cache_fulfill * *;

keepalive_timeout 50;

http_chain {
-> domain;
}
```

With your config Tempesta-fw is starting fine on my side.
Also i add some test config at `/etc/tempesta/sites/test.conf` to ensure templater() function works fine
```
srv_group domain1 {
  server 10.0.0.1:3000 conns_n=4;
}

vhost domain1 {

#tls_certificate /etc/letsencrypt/live/domain/cert.pem;
#tls_certificate_key /etc/letsencrypt/live/domain/privkey.pem;
resp_hdr_set Strict-Transport-Security "max-age=31536000; includeSubDomains";

proxy_pass domain1;

sticky {
    cookie name=domain enforce max_misses=3 timeout=3;
}
}
```
-----------------------------------------

In your case templater() function didn't replace !include directive, its strange. Lets try to figure out the problem

1. Could you check `!include ...` line for spec-symbols?
2. Is tempesta-fw starting when you comment `#!include` line?
3. Ensure the included files (files in `/etc/temesta/site/`) doesn't contain !include directive - it only top-level strict function
4. If first 3 points doesn't fix the bug: Provide your `/root/tempesta/scripts/tempesta.sh` file content
  It must include following code:
```
templater()
{
        # Replace !include dircetive with file contents
        > $tfw_cfg_temp
        mkdir $TFW_ROOT/etc 2>/dev/null
        while IFS= read -r line
        do
                if [[ ${line:0:1} = \# ]]; then
                        :
                elif [[ $line =~ '!include' ]]; then
                        IFS=' '
                        read -ra path <<< "$line"

                        files=$(find ${path[1]} -type f -regextype posix-extended -regex '.*\.conf$')
                        while IFS= read -r file; do
                                value=`cat $file`
                                echo "$value" >> $tfw_cfg_temp
                        done <<< "$files"
                else
                        value="$line"
                        echo "$value" >> $tfw_cfg_temp
                fi
        done < "$tfw_cfg_path"
}
```

**Comment by krizhanovsky** [comment]
Two weeks passed, so I close the issue for now. @DevTom811 feel free to reopen it if the problem still exists.
