### ISSUE TITLE
SETTINGS_HEADER_TABLE_SIZE: Tempesta does not encode header into dynamic table

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1793]
# Scope

1. Client send SETTINGS frame with SETTINGS_HEADER_TABLE_SIZE = 0;
2. Tempesta clearing dynamic table. RFC 7541 4.2;
3. Client send SETTINGS frame with SETTINGS_HEADER_TABLE_SIZE = 4096 (not 0);
4. Client send request;

ER: Tempesta saves response header in dynamic table.
AR: Tempesta does not saves response header in dynamic table.

# Testing

[Test to reproduce](https://github.com/tempesta-tech/tempesta-test/blob/e355614b9332dfdddcb47b76ebdd969052005db6/http2_general/test_h2_hpack.py#L276)

**Comment by EvgeniiMekhanik** [comment]
Closed by merged PR
