### ISSUE TITLE
Tempesta forwards connection-specific headers for h2 connection

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1805]
# Scope
[RFC 9113 8.2.2](https://www.rfc-editor.org/rfc/rfc9113.html#name-connection-specific-header-)

> Any message containing connection-specific header fields MUST be treated as [malformed](https://www.rfc-editor.org/rfc/rfc9113.html#malformed) ([Section 8.1.1](https://www.rfc-editor.org/rfc/rfc9113.html#malformed)).

> An intermediary transforming an HTTP/1.x message to HTTP/2 MUST remove connection-specific header fields as discussed in [Section 7.6.1](https://www.rfc-editor.org/rfc/rfc9110#section-7.6.1) of [[HTTP](https://www.rfc-editor.org/rfc/rfc9113.html#RFC9110)], or their messages will be treated by other HTTP/2 endpoints as [malformed](https://www.rfc-editor.org/rfc/rfc9113.html#malformed) ([Section 8.1.1](https://www.rfc-editor.org/rfc/rfc9113.html#malformed)).

Tempesta forwards `Proxy-Connection` and `Upgrade` headers in requests/responses.

[Test to reproduce](https://github.com/tempesta-tech/tempesta-test/blob/0e05a147dc96f2ef6f2b985501f4a4a460c6fe77/http2_general/test_h2_headers.py#L165). Please enable after fixes.

**Comment by dmpetroff** [comment]
Fixed in #1885

**Comment by dmpetroff** [comment]
It seems I've forgotten about `Te` header in HTTP/1.x upstream response.

**Comment by krizhanovsky** [comment]
Fixed again in #1917
