### ISSUE TITLE
SETTINGS_HEADER_TABLE_SIZE > 4096 bytes does not work as expected

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1807]
# Scope

If client sends settings frame with SETTINGS_HEADER_TABLE_SIZE > 4096, we must:

- or does not send settings frame with `ack` flag;
- or change settings with new value for table size and encode header > 4096 bytes in dynamic table (now Tempesta does not encode headers > 4096 bytes).

# Testing
Need test for one of cases

**Comment by krizhanovsky** [comment]
It seems we can expand the table, but we need to consider security to not get DDoSed with too many and too large such requests. If we do expand the table, then we need to have some limit for this, maybe a configuration option.

Also need to check whether popular browsers, like Chorme and Firefox, request the extensions.

**Comment by krizhanovsky** [comment]
Closed by https://github.com/tempesta-tech/tempesta/pull/1815
