### ISSUE TITLE
0.7 release

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1811]
As the last task in the milestone, please prepare the release for 0.7 and deploy the new Tempesta FW version on our website.

Please also create new branch `release-0.6`, which will aggregate all backported fixes. Also please create `0.7.0` tag as for previous releases.

Probably need to update https://github.com/tempesta-tech/tempesta/wiki/Install-from-packages

**Comment by kolinfluence** [comment]
been looking at this for a long time.

pls provide instructions on how to install and use! can't wait to try it.

**Comment by krizhanovsky** [comment]
@kolinfluence usage docs are available at https://github.com/tempesta-tech/tempesta/wiki/Install-from-packages
