### ISSUE TITLE
Tempesta sends incorrect 304 response from cache

### ISSUE THREAD

**Issue by EvgeniiMekhanik** [tempesta-tech/tempesta#1814]
Deproxy client can't parse 304 response from tempesta and drop it.

# Testing
http2_general.test_h2_hpack.TestHpackCache.test_h2_cache_after_setting_header_table_size
in https://github.com/tempesta-tech/tempesta-test/pull/395

**Comment by krizhanovsky** [comment]
Fixed in https://github.com/tempesta-tech/tempesta/pull/1832
