### ISSUE TITLE
h2spec: http2/4.3/3 and http2/6.2/2 - incorrect processing of header block in different streams

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1823]
# Scope
Tempesta must not process header block (HEADERS, CONTINUATION, PUSH_PROMISE frames) in new streams until it receives END_HEADERS in previous stream.

1. Client send HEADERS frame with stream_id = 1 and END_HEADERS - False;
2. Client send HEADERS frame with stream_id = 3
3. Client send CONTINUATION frame with stream_id = 1 and END_HEADERS - True

ER: GOAWAY frame with PROTOCOL ERROR
AR: Tempesta returns HEADERS frame.

[RFC 9113 4.3](https://httpwg.org/specs/rfc9113.html#FieldBlock)

> Each field block is processed as a discrete unit. Field blocks MUST be transmitted as a contiguous sequence of frames, with no interleaved frames of any other type or from any other stream. The last frame in a sequence of HEADERS or CONTINUATION frames has the END_HEADERS flag set. The last frame in a sequence of PUSH_PROMISE or CONTINUATION frames has the END_HEADERS flag set. This allows a field block to be logically equivalent to a single frame.

# Testing

Tests to reproduce [1](https://github.com/tempesta-tech/tempesta-test/blob/c485d6c32ae365ca10756f2bd3fc14bb3c5eb21a/http2_general/test_h2_specs.py#L110) and [2](https://github.com/tempesta-tech/tempesta-test/blob/c485d6c32ae365ca10756f2bd3fc14bb3c5eb21a/http2_general/test_h2_specs.py#L120). Please enable tests after fix.

**Comment by RomanBelozerov** [comment]
Same problem:

1. Client send HEADERS frame with stream_id - 1, END_HEADERS - True and END_STREAM - False;
2. Client send HEADERS frame with stream_id - 1, END_HEADERS - True and END_STREAM - True;

ER: GOAWAY with PROTOCOL_ERROR;
AR: headers are concatenated and forwarded to server;

RFC 9113 4.3

> A complete field section consists of either:
> 
> - a single HEADERS or PUSH_PROMISE frame, with the END_HEADERS flag set, or
> 
> - a HEADERS or PUSH_PROMISE frame with the END_HEADERS flag unset and one or more CONTINUATION frames, where the last CONTINUATION frame has the END_HEADERS flag set.

**Comment by EvgeniiMekhanik** [comment]
Also there is a problem with sending responses to clients if we have error in parsing request before we receive END_HEADER flag. We have some problems in processing stream state.

**Comment by EvgeniiMekhanik** [comment]
> Same problem:
> 
>     1. Client send HEADERS frame with stream_id - 1, END_HEADERS - True and END_STREAM - False;
> 
>     2. Client send HEADERS frame with stream_id - 1, END_HEADERS - True and END_STREAM - True;
> 
> 
> ER: GOAWAY with PROTOCOL_ERROR; AR: headers are concatenated and forwarded to server;
> 
> RFC 9113 4.3
> 
> > A complete field section consists of either:
> > 
> > * a single HEADERS or PUSH_PROMISE frame, with the END_HEADERS flag set, or
> > * a HEADERS or PUSH_PROMISE frame with the END_HEADERS flag unset and one or more CONTINUATION frames, where the last CONTINUATION frame has the END_HEADERS flag set.

According to our discussion it is ok for trailers
