### ISSUE TITLE
h2spec: http2/5.1/11 and http2/5.1/12 - sending HEADERS and DATA frames in closed stream.

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1828]
# Scope

1. Client make request and receive response and END_STREAM flag;
2. Client send DATA or HEADERS frame in this stream

ER: GOAWAY frame with STREAM_CLOSED
AR: Tempesta does not respond.

[RFC 9113 5.1](https://httpwg.org/specs/rfc9113.html#StreamStates)

> A stream also enters the "closed" state after an endpoint either sends or receives a RST_STREAM frame.
An endpoint MUST NOT send frames other than PRIORITY on a closed stream. An endpoint MAY treat receipt of any other type of frame on a closed stream as a connection error (Section 5.4.1) of type STREAM_CLOSED, except as noted below.

# Testing

[Test to reproduce](https://github.com/tempesta-tech/tempesta-test/blob/c485d6c32ae365ca10756f2bd3fc14bb3c5eb21a/http2_general/test_h2_specs.py#L113). Please enable tests after fix.

**Comment by RomanBelozerov** [comment]
Points `http2/5.1/5`, `http2/5.1/6` and `http2/6.1/2` are also related to this.

**Comment by EvgeniiMekhanik** [comment]
Fixed, test was enabled
