### ISSUE TITLE
Tempesta-fw Wordpress frang Error

### ISSUE THREAD

**Issue by pale-emperor** [tempesta-tech/tempesta#1829]
# Motivation

Wordpress CMS behind Tempesta framework have some bugs described below:

- [ ] Page/Post Edit - Error on Update:

```
[2413761.180181] [tempesta fw] Warning: frang: restricted overridden HTTP method for 3.72.94.204: 13 (0x2000u)
[2413761.180643] [tempesta fw] Warning: postponed request has been filtered out: 3.72.94.204
```

If anything else comes up - i'll add it here

**Comment by krizhanovsky** [comment]
This might be not a bug: probably WordPress overrides HTTP method, so could you please check setting of `http_method_override_allowed` (see https://github.com/tempesta-tech/tempesta/wiki/HTTP-security)?

If some additional (non-default) configuration for Tempesta and/or WordPress is required, then we need to create a new `WordPress` use case in https://github.com/tempesta-tech/tempesta/wiki/Use-cases and describe all the settings there.

**Comment by pale-emperor** [comment]
Good point

I have added a frang directive at the top level following the wiki pages:
```
frang_limits {
        http_method_override_allowed true;
        http_methods POST GET HEAD PUT;
}
```
But still got same error whatever i configure

Request is POST, override method is PUT

Request headers:
```
POST /wp-json/wp/v2/pages/2258?_locale=user HTTP/1.1
Host: tempesta-tech.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
Accept: application/json, */*;q=0.1
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://tempesta-tech.com/wp-admin/post.php?post=2258&action=edit
X-WP-Nonce: 41ff73417e

X-HTTP-Method-Override: PUT

Content-Type: application/json
Content-Length: 24
Origin: https://tempesta-tech.com
Connection: keep-alive
Cookie: wp-settings-verylongheadertoplaceithere
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by krizhanovsky** [comment]
That might be a bug, need further investigation

**Comment by const-t** [comment]
Can't reproduce with `http_method_override_allowed`. Added to [WordPress Tips and Tricks](https://github.com/tempesta-tech/tempesta/wiki/WordPress-tips-and-tricks#http-method-override) page.
