### ISSUE TITLE
latest tempesta git master cant build in debian bullseye 

### ISSUE THREAD

**Issue by osevan** [tempesta-tech/tempesta#1839]
I get to much compile errors..

Anyone know that?

Im still running old build from 40 days before.

Thanks and

Best regards

**Comment by krizhanovsky** [comment]
Hi @osevan ,

could you please provide more details on the build issues? At least the full build log along with the information about the target system are required.

**Comment by krizhanovsky** [comment]
There is no update for 2 weeks, so I close the task. @osevan please don't hesitate to reopen it if the issue still exists for you.
