### ISSUE TITLE
Rewrite proxied Host header when URI comes in the form of absolut-URI

### ISSUE THREAD

**Issue by dmpetroff** [tempesta-tech/tempesta#1870]
https://www.rfc-editor.org/rfc/rfc9112.html#section-3.2.2

> When a proxy receives a request with an absolute-form of request-target, the proxy MUST ignore the received Host header field (if any) and instead replace it with the host information of the request-target. A proxy that forwards such a request MUST generate a new Host field value based on the received request-target rather than forward the received Host field value.

Currently we only act as origin-server ignoring Host header in presence of absolute-URI

**Comment by voodam** [comment]
It was decided on meeting that this issue should be done after some another @const-t issue, so I set him as assignee.
