### ISSUE TITLE
trailers in h2 request

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1881]
# Scope
[RFC 9113 8.1](https://www.rfc-editor.org/rfc/rfc9113.html#name-http-message-framing)

Cases:
> Trailers MUST NOT include pseudo-header fields (Section 8.3). An endpoint that receives pseudo-header fields in trailers MUST treat the request or response as malformed (Section 8.1.1).

**Fixed**:
> ~~An endpoint that receives a HEADERS frame without the END_STREAM flag set after receiving the HEADERS frame that opens a request or after receiving a final (non-informational) status code MUST treat the corresponding request or response as malformed (Section 8.1.1).~~

> ~~Trailer fields are carried in a field block that also terminates the stream. That is, trailer fields comprise a sequence starting with a HEADERS frame, followed by zero or more CONTINUATION frames, where the HEADERS frame bears an END_STREAM flag.~~

# Testing
Tests to reproduce;
- http2_general.test_h2_headers.TestTrailers.test_trailers_with_pseudo_headers_in_request
- ~~http2_general.test_h2_headers.TestTrailers.test_trailers_without_end_stream_in_request~~
- ~~http2_general.test_h2_headers.TestTrailers.test_trailers_with_continuation_frame_in_request~~

**Comment by krizhanovsky** [comment]
Fixed in https://github.com/tempesta-tech/tempesta/pull/2125
