### ISSUE TITLE
possible to do an af_xdp version so there won't be a need to modify kernel?

### ISSUE THREAD

**Issue by kolinfluence** [tempesta-tech/tempesta#1898]
1. pls update this milestone expected deadline, thx
https://github.com/tempesta-tech/tempesta/milestone/15

2. as was looking at the deadline for this, i thought it would be "better" to just shift to use af_xdp which means we wont need to modify kernel. can this be a possibility? also, it will lay the foundation for h3 too.

**Comment by krizhanovsky** [comment]
Hi @kolinfluence ,

thanks for your request. I updated the expected date for 0.7 - all the tasks seem already have pull requests and I think we'll be able to merge all the fixes and prepare the package within 2 weeks.

Regarding `AF_XDP` it impossible to go with XDP only: Tempesta FW is an HTTP proxy, so it must be placed on to of a TCP/IP stack and be an active TCP endpoint while XDP works on very low network layer, much earlier than TCP and even IP.

I'm closing the issue, but feel free to reopen it if you have any questions or proposals!
