### ISSUE TITLE
cache: proxy-revalidate does not work as must-revalidate for private response

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1899]
# Scope
proxy-revalidate does not work as must-revalidate for response to request with `Authorization` header. 

> This is analogous to must-revalidate [Section 5.2.2.2], except that proxy-revalidate does not apply to private caches.
[RFC 9111 5.2.2.8](https://www.rfc-editor.org/rfc/rfc9111.html#name-proxy-revalidate)

> A shared cache MUST NOT use a cached response to a request with an Authorization header field.
[RFC 9111 3.5](https://www.rfc-editor.org/rfc/rfc9111.html#name-storing-responses-to-authen)

# Testing
Test to reproduce: - `cache.test_h2_cache_control.TestH2CacheControl.test_authorization_in_first_request_proxy_revalidate_in_response` and `cache.test_cache_control.StoringResponsesToAuthenticatedRequestsProxyRevalidateCache`

**Comment by EvgeniiMekhanik** [comment]
Closed by https://github.com/tempesta-tech/tempesta/pull/2005
