### ISSUE TITLE
hpack: response with empty header values

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#1900]
# Scope

For headers with empty values in response:
```python3
HTTP/1.1 200 OK
remove-me:
remove-me-2:
Content-Length: 0

```
Send two request to same resource:

ER: Tempesta forwarded response with headers -  `remove-me: \r\nremove-me-2: \r\n`.
AR: Tempesta forwarded response with headers -  `remove-me-2: \r\nremove-me-2: \r\n`. (hex for first header - `7f0300`, second - `400b72656d6f76652d6d652d3200`, but expected `c3` and `c2`)

See #530 

# Testing
Test to reproduce - `cache.test_cache.TestH2CacheHdrDel.test_cache_bypass`

**Comment by krizhanovsky** [comment]
Fixed in #1920 and backported to release-0.7 in #1950
