### ISSUE TITLE
Seeing http2 is almost done, possible to explore using af_xdp / ebpf directly in future?

### ISSUE THREAD

**Issue by kolinfluence** [tempesta-tech/tempesta#1908]
the speed of development of linux is getting faster and better with io_uring etc.

pls consider using af_xdp / ebpf so we can all move faster without modification to kernel core.

this also provides the opportunity for many more people to use tempesta without kernel mod.

pls seriously consider what i've mentioned regarding ebpf / af_xdp.

Thx

**Comment by krizhanovsky** [comment]
I answered the same question in https://github.com/tempesta-tech/tempesta/issues/1898#issuecomment-1587313259
