### ISSUE TITLE
Wrong matching TLS SNI and Host header

### ISSUE THREAD

**Issue by const-t** [tempesta-tech/tempesta#1911]
# Scope
In case when request contains header `Host: debian:443` SNI matching fails with warning: 
```
frang: vhost by SNI doesn't match vhost by authority for 192.168.122.90 ('debian' vs 'NULL')
[ 4049.213276] [tempesta fw] Warning: parsed request has been filtered out: 192.168.122.90
```

# Testing
Need to develop test for this case.

**Comment by voodam** [comment]
https://github.com/tempesta-tech/tempesta/pull/1981
https://github.com/tempesta-tech/tempesta-test/pull/522
