### ISSUE TITLE
TDB crash

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1921]
Bug report from the recent pilot on just released 0.7 (as of 9653573932a8f4e99bf6f1d08b343c0dc9dbb72e).
![photo_5276405853743860028_y](https://github.com/tempesta-tech/tempesta/assets/884694/64458a3e-87a9-4135-aa1f-5ddc56aafe95)

![photo_5276405853743860019_y](https://github.com/tempesta-tech/tempesta/assets/884694/2c81ea9c-bfd2-4db1-83b5-2709ee49faf7)

![photo_5276405853743860013_y](https://github.com/tempesta-tech/tempesta/assets/884694/497752bc-d04f-4267-9974-4410defee9ed)
![photo_5276405853743860009_y](https://github.com/tempesta-tech/tempesta/assets/884694/a4f316c5-1d68-4502-9d5a-12a56432a7f2)

**Comment by krizhanovsky** [comment]
Tempesta's config:
```
listen 80;
cache 1;
cache_fulfill * *;

block_action attack reply;

server 10.3.145.179:8080;
#access_log off;
vhost fakeapp.lab.bwaf.local {
  proxy_pass default; # reference to the server group
#sticky {
#    cookie name=__tfw;
#    cookie enforce;
#    js_challenge delay_min=1000 delay_range=1000;
#    cookie name=my_js_cookie enforce max_misses=3 timeout=3;
#    js_challenge resp_code=200 delay_min=1000 delay_range=1000 delay_limit=3000;
#}
}
http_chain {
  -> fakeapp.lab.bwaf.local;
}
```

**Comment by const-t** [comment]
HTrie significantly reworked in #2074, therefore it seems outdated.
