### ISSUE TITLE
tempesta_installer.sh script  error . 

### ISSUE THREAD

**Issue by w796933** [tempesta-tech/tempesta#1929]
wget https://raw.githubusercontent.com/tempesta-tech/tempesta/master/pkg/scripts/tempesta_installer.sh
chmod +x tempesta_installer.sh
sudo ./tempesta_installer.sh --install

Setting up libtemplate-perl (2.27-1build2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...

Downloading latest packages from github.com/tempesta-tech/ ...
Can't download file  from release ubuntu-20/0.7.0 in repo:
https://github.com/tempesta-tech/linux-5.10.35-tfw
Or may be Github API rate limit exceeded.

**Comment by w796933** [comment]
and this error . 


 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.10.35.tfw-4c9ba16/updates/dkms/

depmod...

DKMS: install completed.
Building initial module for 5.4.0-153-generic
Error!  The /var/lib/dkms/tempesta-fw/0.7.0/5.4.0-153-generic/x86_64/dkms.conf for module tempesta-fw includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.

**Comment by pale-emperor** [comment]
You have got github api limit exceeded, it means github block request - try run script a bit later

I'll try to change installation script to get Deb packages from our repo to ensure you will receive files properly

**Comment by pale-emperor** [comment]
> and this error .
> 
>     * Original module
>       
>       * No original module exists within this kernel
> 
>     * Installation
>       
>       * Installing to /lib/modules/5.10.35.tfw-4c9ba16/updates/dkms/
> 
> 
> depmod...
> 
> DKMS: install completed. Building initial module for 5.4.0-153-generic Error! The /var/lib/dkms/tempesta-fw/0.7.0/5.4.0-153-generic/x86_64/dkms.conf for module tempesta-fw includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch. This indicates that it should not be built. Skipped.

Have fixed this case in https://github.com/tempesta-tech/tempesta/pull/1932

Please retry after merge or pull branch `ratelimit_fix` insted of `master`

Please provide whole script log next time 

Thanks
