### ISSUE TITLE
Wordpress parser error

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#1936]
This issue appeared on the new website with Wordpress/Tempesta:
```
[  153.689155] [tempesta fw] Warning: HTTP/2 request dropped: state=Req_HdrUpgrade input=0x75('upgrade-insecure'), len=25, off=0
[  153.689219] [tempesta fw] Warning: failed to parse request: 217.66.157.150
```

The website index file was requested to get the error.

**Comment by const-t** [comment]
Please check it with http1 also, not only http2.

**Comment by krizhanovsky** [comment]
The problem is with HTTP/2 parser for `Upgrade-Insecure-Requests`, which is treated as prohibited in HTTP/2  `Upgrade` due to no length or `:` in the parser.
