### ISSUE TITLE
Check that skb->mark is correctly forwarded to backend?

### ISSUE THREAD

**Issue by EvgeniiMekhanik** [tempesta-tech/tempesta#1987]
skb mark is not copied when skn is splitted in `tcp_write_xmit() -> tso_fragment()`. We should write tests for this case and check that all works fine.

**Comment by krizhanovsky** [comment]
IIRC `skb->mark` is used in HTTPtables only for the integration with Netfilter, so probably we can just extend some HTTPtables test (or do we already have such test?)
