### ISSUE TITLE
tfw_lib.sh incorrectly handles veth interfaces (and /sys/class/net path)

### ISSUE THREAD

**Issue by mbabitski-t** [tempesta-tech/tempesta#1990]
## Scope

1. `tempesta.sh` script calls `tfw_lib.sh`
2. `tfw_lib.sh` sees `veth8d3e29bb@if4` interface, tries to access `/sys/class/net//veth8d3e29bb@if4/queues/rx-*/rps_cpus`
4. but only `/sys/class/net/veth8d3e29bb` exists.

```
$ ip link
5: veth8d3e29bb@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master lxdbr0 state UP mode DEFAULT group default qlen 1000
    link/ether fe:fb:8b:08:aa:1a brd ff:ff:ff:ff:ff:ff link-netnsid 0
$ ls /sys/class/net/
veth8d3e29bb
$ sudo -E ./scripts/tempesta.sh --start
Starting Tempesta...
...enable RPS on veth8d3e29bb@if4
./scripts/tfw_lib.sh: line 178: /sys/class/net//veth8d3e29bb@if4/queues/rx-*/rps_cpus: No such file or directory
...load Tempesta modules
Loading Tempesta kernel modules...
Loading module tempesta_lib 
Loading module tempesta_tls 
Loading module tempesta_db 
Loading module tempesta_fw tfw_cfg_path=/home/user/tempesta/etc/tempesta_tmp.conf
...compile html templates for JS challenge
...start Tempesta FW
done
```

## Possible fix

Remove everything after the `@` in the interface name when accessing `/sys`.

**Comment by krizhanovsky** [comment]
I'm wondering which virtual machine do you use and how do you initialize the network interface?

**Comment by mbabitski-t** [comment]
@krizhanovsky VM is Ubuntu 22.04.3 LTS (GNU/Linux 5.10.35.tfw-4c9ba16 x86_64) QEMU libvirtd. 

Network interface is initialized by LXD every time a container with the following config is started, and LXD removes the interface after container is stopped.
```
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
```

**Comment by krizhanovsky** [comment]
Do you run Tempesta FW inside the container, is this container just runs inside the VM with Tempesta FW?

**Comment by mbabitski-t** [comment]
Container just runs inside VM with Tempesta FW.

**Comment by voodam** [comment]
I catched this error on `ff0f02145172b92794ef3cd086a12af737caa793` Tempesta commit, but after rebuilding on master and returning back to the commit it was gone. No LXD, just my ususal VM on Proxmox.

**Comment by mbabitski-t** [comment]
@voodam the error is caused by a buggy `tfw_lib.sh` shell script and should not be tied to a specific TempestaFW version. Maybe network interfaces on your VM have been reconfigured between builds/reboots.

**Comment by EvgeniiMekhanik** [comment]
I think this will be fixed by https://github.com/tempesta-tech/tempesta/pull/2076

**Comment by krizhanovsky** [comment]
So I move it to 0.9 as #2075

**Comment by EvgeniiMekhanik** [comment]
Closed by (https://github.com/tempesta-tech/tempesta/pull/2076
