### ISSUE TITLE
Installation error in ubunutu 22.04

### ISSUE THREAD

**Issue by kismat1330** [tempesta-tech/tempesta#2027]
Setting up linux-libc-dev:amd64 (5.10.35.tfw-4c9ba16-1) ...
Setting up tempesta-fw-dkms (0.7.0) ...
Loading new tempesta-fw-0.7.0 DKMS files...
Building for 5.10.35+, 5.10.35.tfw-4c9ba16, 5.19.0-32-generic and 6.2.0-39-generic
Module build for kernel 5.10.35+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.10.35.tfw-4c9ba16
ERROR (dkms apport): kernel package linux-headers-5.10.35.tfw-4c9ba16 is not supported
Error! Bad return status for module build on kernel: 5.10.35.tfw-4c9ba16 (x86_64)
Consult /var/lib/dkms/tempesta-fw/0.7.0/build/make.log for more information.
dpkg: error processing package tempesta-fw-dkms (--install):
 installed tempesta-fw-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 tempesta-fw-dkms

**Comment by kismat1330** [comment]
Module build for kernel 5.10.35+ was skipped since the
kernel headers for this kernel does not seem to be installed.
Building initial module for 5.10.35.tfw-4c9ba16

**Comment by kismat1330** [comment]
ERROR (dkms apport): kernel package linux-headers-5.10.35.tfw-4c9ba16 is not supported
Error! Bad return status for module build on kernel: 5.10.35.tfw-4c9ba16 (x86_64)
Consult /var/lib/dkms/tempesta-fw/0.7.0/build/make.log for more information.

**Comment by krizhanovsky** [comment]
Probably linked with #2026.

**Comment by ykargin** [comment]
Hello @kismat1330, is the installation issue still present?

**Comment by ykargin** [comment]
Hi @kismat1330,

It looks like the issue has been resolved, so I am closing this bug. However, if you have any additional information or if the issue persists, please feel free to reopen this issue. Thank you for your assistance in improving our project.
