### ISSUE TITLE
BUILD_EXCLUSIVE  directive  does not match this kernel/arch/config.

### ISSUE THREAD

**Issue by kismat1330** [tempesta-tech/tempesta#2035]
Building initial module for 5.15.0-25-generic
Error! The /var/lib/dkms/tempesta-fw/0.7.0/5.15.0-25-generic/x86_64/dkms.conf for module tempesta-fw includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
The /var/lib/dkms/tempesta-fw/0.7.0/5.15.0-25-generic/x86_64/dkms.conf for module tempesta-fw includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch/config.
This indicates that it should not be built.
Skipped.
Building initial module for 6.5.0-14-generic
Error! The /var/lib/dkms/tempesta-fw/0.7.0/6.5.0-14-generic/x86_64/dkms.conf for module tempesta-fw includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
The /var/lib/dkms/tempesta-fw/0.7.0/6.5.0-14-generic/x86_64/dkms.conf for module tempesta-fw includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch/config.
This indicates that it should not be built.
Skipped.

or when i change tempesta config file and after that i restart the tempesta, but getting error like ...

kismat@kismat-linux:~$ sudo systemctl status tempesta-fw.service 
× tempesta-fw.service - High performance HTTP proxy server
     Loaded: loaded (/lib/systemd/system/tempesta-fw.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-01-10 17:47:14 IST; 5s ago
    Process: 6486 ExecStart=/lib/tempesta/scripts/tempesta.sh --start (code=exited, status=1/FAILURE)
    Process: 6574 ExecStopPost=/lib/tempesta/scripts/tempesta.sh --stop (code=exited, status=0/SUCCESS)
   Main PID: 6486 (code=exited, status=1/FAILURE)
        CPU: 147ms

Jan 10 17:47:14 kismat-linux tempesta.sh[6574]: ...unload Tempesta modules
Jan 10 17:47:14 kismat-linux tempesta.sh[6574]: Un-loading Tempesta kernel modules...
Jan 10 17:47:14 kismat-linux tempesta.sh[6589]: rmmod: ERROR: Module tempesta_fw is not currently loaded
Jan 10 17:47:14 kismat-linux tempesta.sh[6590]: rmmod: ERROR: Module tempesta_db is not currently loaded
Jan 10 17:47:14 kismat-linux tempesta.sh[6591]: rmmod: ERROR: Module tempesta_tls is not currently loaded
Jan 10 17:47:14 kismat-linux tempesta.sh[6592]: rmmod: ERROR: Module tempesta_lib is not currently loaded
Jan 10 17:47:14 kismat-linux tempesta.sh[6574]: ...revert irqbalance config
Jan 10 17:47:14 kismat-linux tempesta.sh[6574]: done
Jan 10 17:47:14 kismat-linux systemd[1]: tempesta-fw.service: Failed with result 'exit-code'.
Jan 10 17:47:14 kismat-linux systemd[1]: Failed to start High performance HTTP proxy server.

**Comment by krizhanovsky** [comment]
Hi @ykargin isn't this related to the DKMS build issue?

**Comment by const-t** [comment]
Hi @kismat1330. What version of the linux kernel do you use? Send me please output of `uname -a`.

**Comment by kismat1330** [comment]
@const-t linux:~$ uname -a
Linux kismat-linux 5.10.35.tfw-4c9ba16 #1 SMP Mon Jun 26 15:39:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kismat1330** [comment]
> Hi @kismat1330. What version of the linux kernel do you use? Send me please output of `uname -a`.

@const-t linux:~$ uname -a
Linux kismat-linux 5.10.35.tfw-4c9ba16 #1 SMP Mon Jun 26 15:39:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ykargin** [comment]
Hi @kismat1330. For now, BUILD_EXCLUSIVE [is used](https://github.com/tempesta-tech/tempesta/blob/062a2d1a0a614004f1eee7fcc2905d4cb3a744d2/pkg/scripts/tempesta_installer.sh#L186) to avoid DKMS builds for unsupported kernels. You are using the correct kernel, so it seems like Tempesta FW installed properly, but you are unable to start it. Could you please provide your Tempesta config file?

**Comment by kismat1330** [comment]
> Hi @kismat1330. For now, BUILD_EXCLUSIVE [is used](https://github.com/tempesta-tech/tempesta/blob/062a2d1a0a614004f1eee7fcc2905d4cb3a744d2/pkg/scripts/tempesta_installer.sh#L186) to avoid DKMS builds for unsupported kernels. You are using the correct kernel, so it seems like Tempesta FW installed properly, but you are unable to start it. Could you please provide your Tempesta config file?

when i made changes in config then error exit else it is start and restart properly.

i want implement revers proxy like nginx, but before starting it i only past this # cat etc/tempesta_fw.conf 
listen 192.168.100.4:443 proto=https;
listen 192.168.100.4:80;

# Example include usage
# !include /etc/tempesta/sites/*

srv_group default {
    server 127.0.0.1:8080 conns_n=4;
}

vhost my_hostname {
    tls_certificate /root/tempesta/etc/tfw-root.crt;
    tls_certificate_key /root/tempesta/etc/tfw-root.key;

    proxy_pass default;
}

cache 1;
cache_fulfill * *;

block_action attack reply;

http_chain {
    -> my_hostname;
}

**Comment by ykargin** [comment]
Possible syntax error? Could you please start Tempesta FW and provide the `dmesg` output?

**Comment by kismat1330** [comment]
listen 192.168.100.4:443 proto=https;
#listen 192.168.100.4:80;
srv_group default {
    server 127.0.0.1:8080 conns_n=4;
}
vhost my_hostname {
    proxy_pass default;
}
cache 1;
access_log on;
#block_action attack reply;
http_chain {
    -> my_hostname;
}
above is my config :
Initializing Tempesta FW kernel module...
[87268.841369] [tempesta fw] ERROR: TLS: HTTPS listener set but no TLS certificates provided. At least one vhost must have TLS certificates configured.
[87268.841373] [tempesta fw] ERROR: Unable to complete the configuration of module 'tls': -22
[87268.841373] [tempesta fw] Warning: Configuration parsing has failed. Clean up...
[87268.917373] [tempesta fw] ERROR: TLS: HTTPS listener set but no TLS certificates provided. At least one vhost must have TLS certificates configured.
[87268.917376] [tempesta fw] ERROR: Unable to complete the configuration of module 'tls': -22
[87268.917377] [tempesta fw] Warning: Configuration parsing has failed. Clean up...
[87268.960061] [tempesta fw] exiting...

**Comment by kismat1330** [comment]
#listen 192.168.100.4:443 proto=https;
listen 192.168.100.4:80;
srv_group default {
    server 127.0.0.1:8080 conns_n=4;
}
vhost my_hostname {
    proxy_pass default;
}
cache 1;
access_log on;
#block_action attack reply;
http_chain {
    -> my_hostname;
}
 with this config i am getting .
[87518.883592] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8080: 6 tries, keep trying...
[87518.883611] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8080: 6 tries, keep trying...
[87518.883613] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8080: 6 tries, keep trying...
[87518.883615] [tempesta fw] Warning: sock_srv: cannot establish connection for 127.0.0.1:8080: 6 tries, keep trying...

**Comment by kismat1330** [comment]
@ykargin I think kernel 5.10.35.tfw-4c9ba16 is not supported wiregurad ? because is it not installing properly with interface

**Comment by ykargin** [comment]
Unfortunately, the WireGuard module is not included in our current kernel build. However, you can try building the kernel from the source following the instructions provided in [this link](https://github.com/tempesta-tech/tempesta/wiki/Install-from-Sources). After running the `make olddefconfig` step, you will be able to execute `make menuconfig`.

Once there, you will need to enable the `WireGuard secure network tunnel`. This can be found under the `Device Drivers > Network device support` menu. Additionally, you can speed up the compilation process by disabling the collection of debug data. This option is located in `Kernel Hacking > Compile-time Checks and Compiler Options`. Simply deselect `Compile the kernel with debug info`. After installing the new kernel, please ensure that the correct kernel is selected in GRUB

**Comment by ykargin** [comment]
Hi @kismat1330,

It looks like the issue has been resolved, so I am closing this bug. However, if you have any additional information or if the issue persists, please feel free to reopen this issue. I've also updated the [installation WIKI](https://github.com/tempesta-tech/tempesta/wiki/Install-from-packages) to improve the installation process.
Thank you for your assistance in improving our project.
