### ISSUE TITLE
Kernel panic at skbuff.c

### ISSUE THREAD

**Issue by EvgeniiMekhanik** [tempesta-tech/tempesta#2042]
[ 1768.037843] [tempesta fw] Warning: cpu 0(4), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 1768.038586] [tempesta fw] Warning: cpu 1(4), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 1768.039332] [tempesta fw] Warning: cpu 2(4), backlog size 0, active connections mask 0x100000000, cntwork queue size 0, close backlog is empty
[ 1768.040133] [tempesta fw] Warning: cpu 3(4), backlog size 0, active connections mask 0x0, cntwork queue size 0, close backlog is empty
[ 1768.040876] [tempesta fw] Warning: cpu 4(4), backlog size 0, active connections mask 0x2000000000, cntwork queue size 0, close backlog is empty
[ 1769.503358] skbuff: skb_under_panic: text:ffffffffc0c68060 len:405 put:13 head:ffff98d66e76e580 data:ffff98d66e76e57b tail:0x140 end:0x140 dev:(efault)
[ 1769.505054] ------------[ cut here ]------------
[ 1769.505723] kernel BUG at net/core/skbuff.c:111! (I am not sure, because I catch it on my branch)

**Comment by EvgeniiMekhanik** [comment]
This BUG is very rarely. Was reproduced at 9af1fda1e0bd1bacb35316c35f540c5b587ded13 at MTU 80 after stress tests.

**Comment by EvgeniiMekhanik** [comment]
It is easy to reproduce, just return -ENOMEM from tls_encrypt and do not stop test. On each call  of tls_encrypt we call ss_skb_expand_head_tail for same skb until BUG will be reproduced

**Comment by EvgeniiMekhanik** [comment]
https://github.com/tempesta-tech/tempesta/pull/2168

**Comment by EvgeniiMekhanik** [comment]
The problem occurs because if `tls_encrypt` fails with -ENOMEM (for example when we call `ss_add_overhead` or `kmalloc`, but after we call `ss_skb_expand_head_tail`) Tempesta FW call `tls_encrypt` with the same skb! And `ss_skb_expand_head_tail` is called for this skb again. Each time when we call ``ss_skb_expand_head_tail` we call `skb_push` and if we do it again and again for the same skb BUG occurs.

**Comment by krizhanovsky** [comment]
done in #2168
