### ISSUE TITLE
on-the-fly-configuration: adding listening to a port occupied by another service

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#2043]
Related to #2017 and probably should be fixed at the same time

Tempesta - 9af1fda1e0bd1bacb35316c35f540c5b587ded13

1. start TempestaFW with `listen 443 proto=http;` config;
2. start another service on port `8000`;
3. set TempestaFW config:
```python3
listen 443 proto=http;
listen 8000 proto=http;
listen 4433 proto=http;
```
4. run reload `./tempesta.sh --reload`

ER:
- `tempesta.sh` returns an error about a busy port;
- TempestaFW continues to listen 443 port;

AR:
- `tempesta.sh` returns successfully
```shell
root@cookies-work:~/tempesta# ./scripts/tempesta.sh --reload
...compile html templates for JS challenge
Running live reconfiguration of Tempesta...
sysctl: setting key "net.tempesta.state": Address already in use
done
```
- TempestaFW does not listen to ports - 443, 8000, 4433, but it continues to work.

I always get ERROR in dmesg for `./scripts/tempesta.sh --reload`:
```shell
 [tempesta fw] ERROR: can't bind to: 0.0.0.0:8000
 [tempesta fw] ERROR: can't start listening on: 0.0.0.0:8000
 [tempesta fw] ERROR: Unable to start module 'sock_clnt': -98
 [tdb] Close table 'client0.tdb'
 [tdb] Close table 'sessions0.tdb'
 [tdb] Close table 'cache0.tdb'
 [tdb] Close table 'filter0.tdb'
 [tempesta fw] modules are stopped
```

# Testing

`reconf.test_reconf_base.TestListenCommonReconf.test_reconf_busy_socks`

**Comment by EvgeniiMekhanik** [comment]
During our discussion we decide that there is no sense to continue listen old socks if Tempesta fails to reload. So expected ER is:
1. tempesta.sh returns an error about a busy port;
2. Tempesta stop listening all ports and cleanup its state.
