### ISSUE TITLE
`server_connect_retries` does not work correctly

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#2046]
Tempesta - cf66914624a3906f91e9400d0dbbc7e9ff9de339

Config:
```python3
srv_group default {
    server SERVER_IP:8000 conns_n=1;
    server_connect_retries 3;
}
```

1. start TempestaFW and DeproxyServer on 8000 port;
2. stop DeproxyServer;

ER: TempestaFW make 4 tries and warning in dmesg - `cannot establish connection for SERVER_IP:8000: 4 tries`;
AR: TempestaFW repeats the tries infinitely and warning in dmesg - `cannot establish connection for SERVER_IP:8000: 6 tries, keep trying...` But I set `server_connect_retries 3` and default value is `10`.

# Testing
`reconf.test_reconf_base.TestServerOptionsReconf.test_reconf_server_connect_retries_with_conns_n_1`
`reconf.test_reconf_base.TestServerOptionsReconf.test_reconf_server_connect_retries_with_conns_n_3`
`reconf.test_reconf_base.TestServerOptionsReconf.test_reconf_server_connect_retries_from_default`
`reconf.test_reconf_base.TestServerOptionsReconf.test_reconf_server_connect_retries_from_0`

**Comment by enuribekov-tempesta** [comment]
The cause of such behavior is a following line in a sock_srv.c:
 `*recns = *recns ? max_t(int, *recns, ARRAY_SIZE(tfw_srv_tmo_vals))`,
which directly set as minimal value size of `tfw_srv_tmo_vals array`.
which in turn looks following:
`tfw_srv_tmo_vals[] = { 1, 10, 100, 250, 500, 1000 };`
and contains a sequence of increasing reconnect timeouts.

I did not dive deeper, but it looks like as a implicit lower limit of a reconnection attempts.

**Comment by enuribekov-tempesta** [comment]
At the first glance function  `tfw_sock_srv_connect_try_later()` does not require `recns` limitation and `*recns = *recns ? *recns : UINT_MAX;` solve the problem.

**Comment by krizhanovsky** [comment]
With the call discussions, we do need update `server_connect_retries` description in the wiki

**Comment by krizhanovsky** [comment]
Done in #2213
