### ISSUE TITLE
duplicate value for `Content_Encoding` header in http2 request

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#2081]
Tempesta - 133fba6c3d371ead879414faa40a7bdcacedfac4
Tempesta-test - e8f0da188bbc60e951660683fbc5c52cf153dbce

Tempesta config:
```
cache 0;
listen 80;
listen 443 proto=h2;

tls_certificate ${tempesta_workdir}/tempesta.crt;
tls_certificate_key ${tempesta_workdir}/tempesta.key;
tls_match_any_server_name;

block_action attack reply;
block_action error reply;

server ${server_ip}:8000;
```

I make http2 request from deproxy client with headers
```
[
    (":path", "/"),
    (":scheme", "https"),
    (":method", "POST"),
    (":authority", "localhost"),
    ("content-encoding", "invalid"),
]
```
ER: Tempesta forwarded http1 request with `Content-Encoding: invalid` header
AR: Tempesta forwarded http1 request with `Content-Encoding: invalidinvalid` header

# Testing
`t_malformed.test_h2_malformed_headers.H2MalformedRequestsWithoutStrictParsingTest.test_content_encoding`

**Comment by kingluo** [comment]
The issue is also true for current packages: 4c9ba16

The reason seems to be there is some bug in `__h2_req_parse_content_encoding()`, combined with `saveval=true`, it will double the value chunks:

```
[32042.584807] [tempesta fw]   addr=00000000bdd9f03a skb=0000000000000000 len=24 flags=0 eolen=0:
[32042.586035] [tempesta fw]     duplicate 00000000bdd9f03a, len=24, flags=0 eolen=0:
[32042.587022] [tempesta fw]      len=16, eolen=0 ptr=000000000c5f7200 flags=0 'content-encoding'
[32042.588103] [tempesta fw]      len=4, eolen=0 ptr=000000007a85d158 flags=80 'gzip'
[32042.589200] [tempesta fw]      len=4, eolen=0 ptr=000000007a85d158 flags=80 'gzip'
```

Either fix the parse func (e.g. `__h2_req_parse_referer()`) or set `saveval=false`, the issue is fixed.

```c
/* 'content-encoding' is read, process field-value. */
TFW_H2_PARSE_HDR_VAL(Req_HdrContent_EncodingV, msg,
                     __h2_req_parse_referer,
                     //__h2_req_parse_content_encoding,
                     TFW_HTTP_HDR_CONTENT_ENCODING, 1);
```

I'll submit PR later. Please stay tuned.
