### ISSUE TITLE
Control symbols from the request string in the configuration file passed to string variable as is.  

### ISSUE THREAD

**Issue by enuribekov-tempesta** [tempesta-tech/tempesta#2128]
# Motivation
In the configuration file, in the section  `health_check`   `request` string contains control symbols:
```
health_check auto {
	request		"GET / HTTP/1.0\r\n\r\n";
	request_url	"/";
```
During parsing these string placed to a string buffer as is, with quotation marks and two printables instead of single escape character. 

For example, for the request in the code above we get following:
```
"  G  E  T     /     H  T  T  P  /  1  .  1  \  r  \  n  \  r  \  n  "
22 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 5c 72 5c 6e 5c 72 5c 6e 22
```
instead of:
```
G  E  T     /     H  T  T  P  /  1  .  1
47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a 0d 0a
```
# Scope
Found  in the `health_check` section but potentially may appear in other similar string parameters.
**Does not** appear in the hard-coded default request and configuration files created by `tempesta-test`. 

# Testing
Reproduce only manually.
It make sense to create test case for parsing not generated by framework, but predefined typical configuration file.

**Comment by krizhanovsky** [comment]
> Does not appear in the hard-coded default request and configuration files created by tempesta-test.

Probably it makes sense to process shields in `tempesta.sh` probably with some help of Python/Perl instead of doing this in the kernel, just a proposal.
