### ISSUE TITLE
TfwStr: small rework + unit test

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#215]
TfwStr uses casts of `ptr` field to `char *` and `TfwStr []`, replacing it by

```
    union {
            char *data;
            TfwStr *chunks;
    }
```

will simplify the code and eliminate many casts.

**Comment by krizhanovsky** [comment]
Also it's good to replace current TfwStr->flags by bit field with 3 bytes for number of chunks and 1 byte for actual flags.

**Comment by sergsever** [comment]
Would this union exist simultanuosly whith TfwStr and TfwStr would be it's part?

**Comment by krizhanovsky** [comment]
We need the union inside TfwStr

**Comment by sergsever** [comment]
In original text of issue the union has got a member of type TfwStr. How it could be inside TfwStr?
Or it would be like:
typedef struct {
union {
char *data;
struct sk_buff  *skb;
} TfwStr;

**Comment by sergsever** [comment]
In case that define would be an error:
typedef struct TfwStr {
    union {                                                               
        void            *ptr;
        struct TfwStr * str; <- would be "unknown type name"
    };                                                  
        struct sk_buff  *skb;                                                  
        unsigned int    len;                                                   
        unsigned int    chunks: 24,
                                flags: 8;                                                 
} TfwStr;

**Comment by krizhanovsky** [comment]
**UPD**. `TFW_STR_EMPTY()` should be updated to `(!(s)->len)

**Comment by krizhanovsky** [comment]
Aggregate with #865:
