### ISSUE TITLE
Kernel BUG in hpack.

### ISSUE THREAD

**Issue by EvgeniiMekhanik** [tempesta-tech/tempesta#2152]
kernel BUG at /root/tempesta/fw/hpack.c:3705!
Jun 28 10:34:11 192.168.50.115 [46525.687793] invalid opcode: 0000 [#1] SMP NOPTI
Jun 28 10:34:11 192.168.50.115 [46525.688328] CPU: 1 PID: 0 Comm: swapper/1 Kdump: loaded Tainted: G           OE     5.10.35.tfw-1d07dc5 #1
Jun 28 10:34:11 192.168.50.115 [46525.688861] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.15.0-0-g2dd4b9b3f840-prebuilt.qemu.org 04/01/2014
Jun 28 10:34:11 192.168.50.115 [46525.689955] RIP: 0010:tfw_hpack_enc_tbl_write_sz+0x176/0x200 [tempesta_fw]
Jun 28 10:34:11 192.168.50.115 [46525.690501] Code: 8b 55 e8 65 48 2b 14 25 28 00 00 00 0f 85 91 00 00 00 48 83 c4 50 5b 41 5c 5d c3 48 83 c6 01 29 fa 41 38 f2 0f 87 74 ff ff ff <0f> 0b ba 09 00 00 00 e9 3d ff ff ff 0f 0b 0f b7 53 16 48 89 d0 66
Jun 28 10:34:11 192.168.50.115 [46525.691605] RSP: 0018:ffffb52bc00d8dc0 EFLAGS: 00010246
Jun 28 10:34:11 192.168.50.115 [46525.692141] RAX: ffff8b60eb6e84c0 RBX: ffff8b60e977a710 RCX: 0000000000000000
Jun 28 10:34:11 192.168.50.115 [46525.692675] RDX: 0000000000000000 RSI: 0000000000000001 RDI: 0000000000000009
Jun 28 10:34:11 192.168.50.115 [46525.693207] RBP: ffffb52bc00d8e20 R08: ffff8b5fc0000000 R09: fffff3da80000000
Jun 28 10:34:11 192.168.50.115 [46525.693735] R10: 0000000000000001 R11: 00000000fffffffc R12: ffff8b6186f68780
Jun 28 10:34:11 192.168.50.115 [46525.694258] R13: 0000000000000000 R14: ffff8b6186f68780 R15: ffff8b60e977a648
Jun 28 10:34:11 192.168.50.115 [46525.694789] FS:  0000000000000000(0000) GS:ffff8b61f7c80000(0000) knlGS:0000000000000000
Jun 28 10:34:11 192.168.50.115 [46525.695417] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jun 28 10:34:11 192.168.50.115 [46525.695958] CR2: 000055d463c2c3a8 CR3: 000000012ec00005 CR4: 0000000000770ee0
Jun 28 10:34:11 192.168.50.115 [46525.696484] PKRU: 55555554
Jun 28 10:34:11 192.168.50.115 [46525.697006] Call Trace:
Jun 28 10:34:11 192.168.50.115 [46525.697519]  <IRQ>
Jun 28 10:34:11 192.168.50.115 [46525.698035]  tfw_h2_make_frames+0x543/0x5a0 [tempesta_fw]
Jun 28 10:34:11 192.168.50.115 [46525.698549]  tfw_sk_fill_write_queue+0x150/0x1d0 [tempesta_fw]
Jun 28 10:34:11 192.168.50.115 [46525.699066]  ? tcp_current_mss+0x5e/0xb0
Jun 28 10:34:11 192.168.50.115 [46525.699578]  ss_tx_action+0x6a6/0x770 [tempesta_fw]
Jun 28 10:34:11 192.168.50.115 [46525.700097]  net_tx_action+0x9c/0x250
Jun 28 10:34:11 192.168.50.115 [46525.700611]  __do_softirq+0xd9/0x291
Jun 28 10:34:11 192.168.50.115 [46525.701123]  asm_call_irq_on_stack+0x12/0x20
Jun 28 10:34:11 192.168.50.115 [46525.701659]  </IRQ>
Jun 28 10:34:11 192.168.50.115 [46525.702172]  do_softirq_own_stack+0x3d/0x50
Jun 28 10:34:11 192.168.50.115 [46525.702687]  irq_exit_rcu+0xa4/0xb0
Jun 28 10:34:11 192.168.50.115 [46525.703202]  sysvec_call_function_single+0x3d/0x90
Jun 28 10:34:11 192.168.50.115 [46525.703693]  asm_sysvec_call_function_single+0x12/0x20
Jun 28 10:34:11 192.168.50.115 [46525.704181] RIP: 0010:native_safe_halt+0xe/0x10
Jun 28 10:34:11 192.168.50.115 [46525.704647] Code: 7b ff ff ff eb bd cc cc cc cc cc cc e9 07 00 00 00 0f 00 2d c6 9e 47 00 f4 c3 66 90 e9 07 00 00 00 0f 00 2d b6 9e 47 00 fb f4 <c3> cc 0f 1f 44 00 00 55 48 89 e5 53 65 8b 15 3f ed a7 53 0f 1f 44
Jun 28 10:34:11 192.168.50.115 [46525.705616] RSP: 0018:ffffb52bc008be90 EFLAGS: 00000202
Jun 28 10:34:11 192.168.50.115 [46525.706104] RAX: ffffffffac592690 RBX: 0000000000000001 RCX: ffff8b61f7cacdc0
Jun 28 10:34:11 192.168.50.115 [46525.706592] RDX: 00000000084b86a6 RSI: 00002a50836832f8 RDI: 0000000000000082
Jun 28 10:34:11 192.168.50.115 [46525.707091] RBP: ffffb52bc008be98 R08: 000000cd42e4dffb R09: 00002a5084d668f8
Jun 28 10:34:11 192.168.50.115 [46525.707582] R10: 000000000000000f R11: 0000000000000000 R12: ffff8b60e02db000
Jun 28 10:34:11 192.168.50.115 [46525.708086] R13: ffff8b60e02db000 R14: 0000000000000000 R15: 0000000000000000
Jun 28 10:34:11 192.168.50.115 [46525.708567]  ? __cpuidle_text_start+0x8/0x8
Jun 28 10:34:11 192.168.50.115 [46525.709045]  ? default_idle+0xe/0x20
Jun 28 10:34:11 192.168.50.115 [46525.709519]  arch_cpu_idle+0x15/0x20
Jun 28 10:34:11 192.168.50.115 [46525.709984]  default_idle_call+0x38/0xc0
Jun 28 10:34:11 192.168.50.115 [46525.710441]  do_idle+0x1f8/0x260
Jun 28 10:34:11 192.168.50.115 [46525.710902]  cpu_startup_entry+0x20/0x30
Jun 28 10:34:11 192.168.50.115 [46525.711356]  start_secondary+0x111/0x150
Jun 28 10:34:11 192.168.50.115 [46525.711808]  secondary_startup_64_no_verify+0xb0/0xbb

**Comment by krizhanovsky** [comment]
fixed with #2153
