### ISSUE TITLE
Crash during Tempesta stop under heavy load

### ISSUE THREAD

**Issue by EvgeniiMekhanik** [tempesta-tech/tempesta#2179]
1.  setup Tempesta FW on a baremetal server
2. Try to stop Tempesta under heavy load (Tempesta stops after 10 seconds, because Tempesta can't stop immediatly under heavy load). Sometimes crash occurs, during Tempesta stop

**Comment by krizhanovsky** [comment]
@RomanBelozerov I believe we have exactly this scenario in our stress test suite (restart Tempesta many times under a benchmarking load generator). Maybe it makes sense to run the tests on our SUT system

**Comment by RomanBelozerov** [comment]
> @RomanBelozerov I believe we have exactly this scenario in our stress test suite (restart Tempesta many times under a benchmarking load generator). Maybe it makes sense to run the tests on our SUT system

Yes, you are right. We have such [tests](https://github.com/tempesta-tech/tempesta-test/blob/b7136aa94563063dd75b84cf89858fc03aa4d200/t_regress/test_reboot_under_load.py#L83). I think this issue should be done with #781

**Comment by krizhanovsky** [comment]
@EvgeniiMekhanik need a try to reproduce the  bug, ideally on a mirrored VM

**Comment by krizhanovsky** [comment]
Fixed by https://github.com/tempesta-tech/tempesta/pull/2198
