### ISSUE TITLE
400 bad request without `END_HEADERS` flag

### ISSUE THREAD

**Issue by RomanBelozerov** [tempesta-tech/tempesta#2181]
RFC 9113 6.2

> A HEADERS frame without the END_HEADERS flag set MUST be followed by a [CONTINUATION](https://www.rfc-editor.org/rfc/rfc9113.html#CONTINUATION) frame for the same stream. A receiver MUST treat the receipt of any other type of frame or a frame on a different stream as a [connection error](https://www.rfc-editor.org/rfc/rfc9113.html#ConnectionErrorHandler) ([Section 5.4.1](https://www.rfc-editor.org/rfc/rfc9113.html#ConnectionErrorHandler)) of type [PROTOCOL_ERROR](https://www.rfc-editor.org/rfc/rfc9113.html#PROTOCOL_ERROR).

Client send a lot of invalid requests (tests for header leaks) and wait for a lot of 400 responses with RST_STREAM, but TempestaFW sometimes send a HEADRS frame with END_STREAM and without END_HEADERS and without RST_STREAM frame in this stream (unexpectedly).
stream 2283:
![image](https://github.com/user-attachments/assets/f90b63e3-cdf2-4671-ad26-f340d1cce0f4)

and next stream 2285 (without RST_STREAM between them):

![image](https://github.com/user-attachments/assets/4ee0cd99-f30b-4e0a-93d7-e4c6e3b9b6dc)

Also 2285 stream has a damaged header block

# Testing
[t_stress.test_header_leak.TestH2HeaderLeak.test](https://github.com/tempesta-tech/tempesta-test/blob/b7136aa94563063dd75b84cf89858fc03aa4d200/t_stress/test_header_leak.py#L110)

**Comment by ai-tmpst** [comment]
Couldn't reproduce the bug. Ran the test, collectively, more than 15 times.
Tried to reproduce on the top of the Tempesta FW master branch and with downgrading to the commit 437f9dabd2747afbede4723f721137bcf5016027 (from 01.07.2024) . Also tried to downgrade tempesta-test.
All of the responses contained "End headers" flag and was followed by RST_STREAM frames.

**Comment by krizhanovsky** [comment]
@ai-tmpst can you make an instrumentation patch, which we can run for a long time on our website and CI?

**Comment by ai-tmpst** [comment]
There is a patch to log variables connected to the END_HEADERS flag setting, current + 2 more skbs:
https://github.com/tempesta-tech/tempesta/commit/b20e9bb9bd9830682600eca8291732e79547b25b
