### ISSUE TITLE
Exceeding space in case when there are a lot of clients

### ISSUE THREAD

**Issue by EvgeniiMekhanik** [tempesta-tech/tempesta#2191]
When there are a lot of clients Tempesta FW fails to accept new connection and
writes in dmesg
```
145138.564405] [tdb] ERROR: Cannot allocate cache entry for key=0x7b284d0000000000
[145138.693617] [tdb] ERROR: out of free space
```
We should implement strategy to evict old clients time to time.

**Comment by krizhanovsky** [comment]
Seems duplicate of #2000
