### ISSUE TITLE
Tempesta unittests crash

### ISSUE THREAD

**Issue by KonsKo** [tempesta-tech/tempesta#2222]
# Scope

HEAD 6a11731196b15818d47881e726d220151d01fd67

Server: bare metal, SUT, Linux sut 5.10.35.tfw-1d07dc5 #1 SMP Thu Jun 27 15:40:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

- Reboot the machine
- run `make clean`
- run `make -j`
- run `make test`

Unit Tests are working endlessly (as by hand, as with our CI). If they are interrupted, Tempesta will not be started until a machine is rebooted. 

When Tempesta cannot start after the failed unittests [log_tempesta_cannot_start.txt](https://github.com/user-attachments/files/16731864/log_tempesta_cannot_start.txt)

Dmesg logs for the failed unittests 
[dmesg-Aug-23-2024.txt](https://github.com/user-attachments/files/16731872/dmesg-Aug-23-2024.txt)

# Testing

Unittests

# Documentation

If Tempesta FW behavior or configuration is changed, then please update the [Wiki](https://github.com/tempesta-tech/tempesta/wiki). Don't forget about our [documentation guidelines](https://github.com/tempesta-tech/tempesta/wiki/Development-Guidelines#documentation).

**Comment by krizhanovsky** [comment]
This is about Tempesta FW hang on a baremetal setup, so we need to fix it in Beta, so move to 0.8
