### ISSUE TITLE
Redundant min(src->len, dst->len) in tfw_strcpy()

### ISSUE THREAD

**Issue by ai-tmpst** [tempesta-tech/tempesta#2245]
From tfw_strcpy() function in fw/str.c:702:
```
	if (unlikely(src->len > dst->len))
		return -E2BIG;

	switch (mode) {
	case 3: /* The both are plain. */
		memcpy_fast(dst->data, src->data, min(src->len, dst->len));
		break;
```

If the condition (src->len > dst->len) is true, it returns an error. Since the condition guarantees that src->len <= dst->len, min(src->len, dst->len) can be simplified to src->len.

**Comment by krizhanovsky** [comment]
Done in #2247
