### ISSUE TITLE
Configuration Parsing Failure

### ISSUE THREAD

**Issue by fashtari99** [tempesta-tech/tempesta#2292]
# Motivation

For rate limiting tcp connection rates we used frang limits in tempesta_fw.conf by using tcp_connection_rate and tcp_connection_burst. But the it doesn't work and the tempesta-fw doesn't accept my simple configuration.

Here is my simple configuration
```
frang_limits {
   request_rate 20;
   request_burst 15;
   tcp_connection_rate 16;
   tcp_connection_burst 6;
}
block_action attack reply;

srv_group backend{
        server 10.10.10.1;
}

vhost temp.com {
        proxy_pass backend;
}

http_chain test {
        -> temp.com;
}

http_chain routing {
        host == "*sample.com" -> test;
}

http_chain {
         -> routing;
}
```

and below you can see the demsg logs when I try to restart Tempesta
```
[Nov27 09:20] [tdb] Start Tempesta DB
[  +0.115897] [tempesta fw] Initializing Tempesta FW kernel module...
[  +0.046628] [tempesta fw] ERROR: don't know how to handle: tcp_connection_rate
[  +0.001884] [tempesta fw] ERROR: configuration parsing error:
                 6:    tcp_connection_rate 16;
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
[  +0.004296] [tempesta fw] Warning: Configuration parsing has failed. Clean up...
[  +0.045371] [tempesta fw] ERROR: don't know how to handle: tcp_connection_rate
[  +0.001932] [tempesta fw] ERROR: configuration parsing error:
                 6:    tcp_connection_rate 16;
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
[  +0.004089] [tempesta fw] Warning: Configuration parsing has failed. Clean up...
[  +0.032512] [tempesta fw] exiting...
[  +0.081162] [tdb] Shutdown Tempesta DB
```
Tempesta Version:
5.10.35.tfw-4c9ba16

**Comment by krizhanovsky** [comment]
Hi @fashtari99 thank you for reporting the issue!

@RomanBelozerov may I ask you to investigate the problem? The config looks good for me...

**Comment by RomanBelozerov** [comment]
Hi @fashtari99.

If I understand correctly, you have installed TempestaFW from the [packages](https://github.com/tempesta-tech/tempesta/wiki/Install-from-packages). Unfortunately, the names of the directives has been changed and our wiki matches the current `master` branch. Please try use `connection_rate` and `connection_burst` instead of `tcp_connection_rate` and `tcp_connection_burst`

**Comment by fashtari99** [comment]
Many thanks @krizhanovsky  and @RomanBelozerov . It worked and I have no additional problem
