### ISSUE TITLE
Unblocking blocked IPs

### ISSUE THREAD

**Issue by fashtari99** [tempesta-tech/tempesta#2298]
# Motivation

Unblocking blocked IP by configuring "ip_block on" is not clear. As it could be possible to have some strange cases which we want to unblock some blocked IPs, is there any solution for it? 

# Testing

IP block works correctly and for example it can detect TCP SYN Flooding attack correctly and IP blocks works properly as you can see in below image.

![image](https://github.com/user-attachments/assets/d19b1deb-5ddb-4260-84f4-a489c978bf7d)

But unblocking that exact IP is not clear and even I couldn't find any document about the mechanism of IP blocking and does IP block permanently or temporarily.

**Comment by fashtari99** [comment]
I would be thankful if someone give me a comment. I tried to unblock the blocked IP but I couldn't find any solution.

**Comment by krizhanovsky** [comment]
Hi @fashtari99 ,

sorry for the delay. The filter table, as well as other TDB tables, is supposed to be updated with `tdbq`, https://tempesta-tech.com/knowledge-base/HTTP-security/#filtering . Unfortunately, at the moment `tdbq` is broken https://github.com/tempesta-tech/tempesta/issues/279#issuecomment-2515335443 

Another related issue is #515 : basically the blocked IPs should be evicted by some timeout, but at the moment we don't have a generic TDB eviction mechanism.

At the moment Tempesta FW restart is required to clear the filter table.

**Comment by fashtari99** [comment]
Many thanks @krizhanovsky, Looking forward to test this feature and give you feedback
