### ISSUE TITLE
[Cache] Storing Responses to Authenticated Requests

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#3]
Currently the cache don't consider authorization headers in our caching, but RFC 2616, chapter 14.8 says:

      When a shared cache (see section 13.7) receives a request
      containing an Authorization field, it MUST NOT return the
      corresponding response as a reply to any other request, unless one
      of the following specific exceptions holds:

      1. If the response includes the "s-maxage" cache-control
         directive, the cache MAY use that response in replying to a
         subsequent request. But (if the specified maximum age has
         passed) a proxy cache MUST first revalidate it with the origin
         server, using the request-headers from the new request to allow
         the origin server to authenticate the new request. (This is the
         defined behavior for s-maxage.) If the response includes "s-
         maxage=0", the proxy MUST always revalidate it before re-using
         it.

      2. If the response includes the "must-revalidate" cache-control
         directive, the cache MAY use that response in replying to a
         subsequent request. But if the response is stale, all caches
         MUST first revalidate it with the origin server, using the
         request-headers from the new request to allow the origin server
         to authenticate the new request.

      3. If the response includes the "public" cache-control directive,
         it MAY be returned in reply to any subsequent request.

**Comment by krizhanovsky** [comment]
The new HTTP/1.1 specification requires the same in [RFC 7234 3.2](https://tools.ietf.org/html/rfc7234#section-3.2).

**Comment by keshonok** [comment]
Implemented in #559.
