### ISSUE TITLE
Validating hostname

### ISSUE THREAD

**Issue by vladtcvs** [tempesta-tech/tempesta#347]
RFC 1034 3.5 says:

```
<domain> ::= <subdomain> | " "
<subdomain> ::= <label> | <subdomain> "." <label>
<label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]
<ldh-str> ::= <let-dig-hyp> | <let-dig-hyp> <ldh-str>
<let-dig-hyp> ::= <let-dig> | "-"
<let-dig> ::= <letter> | <digit>

<letter> ::= any one of the 52 alphabetic characters A through Z in
upper case and a through z in lower case

<digit> ::= any one of the ten digits 0 through 9
```

So, hostnames such as 1111, 123.lan, www.123.lan, name-.tld, are invalid and should be blocked

**Comment by krizhanovsky** [comment]
Probably this is good option for filtering/WAF modules like frang, but is shouldn't be in core HTTP parser. For example `123.cn` is a valid domain name:

        $ whois 123.cn
        [Querying whois.cnnic.cn]
        [whois.cnnic.cn]
        Domain Name: 123.cn
        ROID: 20030312s10001s00055206-cn
        Domain Status: clientDeleteProhibited
        Domain Status: clientTransferProhibited
        Registrant ID: ename_1dgacbtwhr
        Registrant: 厦门立投金融信息技术服务有限公司
        Registrant Contact Email: dai@958.com
        Sponsoring Registrar: 厦门易名科技股份有限公司
        Name Server: f1g1ns1.dnspod.net
        Name Server: f1g1ns2.dnspod.net
        Registration Time: 2003-03-17 12:20:05
        Expiration Time: 2020-03-17 12:48:36
        DNSSEC: unsigned

**Comment by krizhanovsky** [comment]
Please update https://github.com/tempesta-tech/tempesta/wiki/Web-security and create a task for functional test.

**Comment by krizhanovsky** [comment]
Tempesta FW is a reverse proxy, so all the host names are known on configuration time. A one wishing to validate `Host` header should just use `sched_http_rules` as shown in https://github.com/tempesta-tech/tempesta/wiki/Web-security#dns-rebinding .
