### ISSUE TITLE
Large number of failures in ab benchmark tests

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#383]
When running Tempesta under benchmark tests such as Apache's `ab` utility, the result is a very large number of failures. All of those failures are non-2xx responses. Tempesta generates error responses on internal errors, but it this case the error in question is `404` that is generated when a back end server is not available.

The issue closely correlates with how fast Tempesta restores connections to back end servers when those connections are closed. Current timeouts for re-establishing the connections with back end servers are too long to work well under high load. A different reconnect timeout algorithm is needed that would allow multiple reconnect attempts in a short time frame, and only after that would gradually increase the delay between attempts.

**Comment by keshonok** [comment]
In addition to making Tempesta restore connections to back end servers faster, there are back end server configuration options that help to keep the connections active for longer periods of time. While it's not recommended to set these options to very high values for traditional HTTP server operation, in our case it's justified.

### Nginx
- [keepalive_timeout](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_timeout)
- [keepalive_requests](http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests)

There's no way to specify unlimited number of requests. There's [a recommendation](http://serverfault.com/questions/425065/nginx-keepalive-requests-what-value-to-use-for-unlimited) from one of `Nginx` developers.

### Apache
- [KeepAlive](https://httpd.apache.org/docs/2.4/mod/core.html#keepalive)
- [KeepAliveTimeout](https://httpd.apache.org/docs/2.4/mod/core.html#keepalivetimeout)
- [MaxKeepAliveRequests](https://httpd.apache.org/docs/2.4/mod/core.html#maxkeepaliverequests)

**Comment by krizhanovsky** [comment]
Actually we need to try next server if a scheduled server is dead, see [Nginx's proxy_next_upstream_tries](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream_tries)

**Comment by krizhanovsky** [comment]
Need to test whether we have the problem on standard Linux kernel + Nginx on real hardware testbed.

**Comment by krizhanovsky** [comment]
There are also must be one more new configuration option - length of the message queue.

**Comment by krizhanovsky** [comment]
Note that Nginx provide `non_idempotent` option for [`proxy_next_upstream`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream) and we should do the same.

**Comment by keshonok** [comment]
Implemented in #660 (merge commit c40924b).
