### ISSUE TITLE
Need to fix some errors in old functional(python) tests.

### ISSUE THREAD

**Issue by sergsever** [tempesta-tech/tempesta#396]
In tfw.py - start/stop parameters.
in fragmented_requests.py - formating.

**Comment by krizhanovsky** [comment]
Please rework the test suite using Python [nose](https://pypi.python.org/pypi/nose/1.3.7). Don't forget to add the nose packages requirements to README prerequisites.

**Comment by ikoveshnikov** [comment]
New test framework is implemented in #679
