### ISSUE TITLE
[TfwBomber] SS: proper errors handling

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#428]
Patch https://github.com/natsys/tempesta/commit/972b7334219814b9f8961ffb29e86d64988ff1ea#diff-1d227fa46d280b745e0336b2f57bc49f removed `sk->sk_error_report()` hook and moved all socket errors processing to `sk->sk_state_change()` at `TCP_CLOSE` state. While `TCP_CLOSE` is normal TCP state, we don't reach it in normal operation; please see the comment below for an  explanation.

However, tfw_bomber requires proper reporting of number of connection errors. While neither client nor server side sockets process errors and normal connection drops in the same way, it has sense to track connection errors for classification modules, more accurate failovering and problems logging.

Thus `sk->sk_error_report()` must be restored and call `connection_error()`, preferably with socket state.

Note that comments  https://github.com/natsys/tempesta/blob/master/tempesta_fw/sock_srv.c#L307 and https://github.com/natsys/tempesta/blob/master/tempesta_fw/sock_srv.c#L323 are invalid and the issue is orthogonal to #254 since the callback distinguish RST/FIN connection closings rather than active/passive closes required for #254.

**Comment by keshonok** [comment]
Tempesta calls a socket close in several situations:
- A regular socket close action from the other side (`FIN`). That's a passive close. In that case the socket is moved to `TCP_CLOSE_WAIT` state, and `ss_tcp_state_change()` is called.
- A socket reset action (`RST`). In that case the socket is moved directly to TCP_CLOSE state, and `ss_tcp_state_change()` is called.
- Various timeouts on Tempesta side. In that case the socket is also moved directly to TCP_CLOSE state, and `ss_tcp_state_change()` is called.
- Explicit socket close by Tempesta. That's an active close.

In all cases `ss_do_close()` is eventually called, most often through `ss_droplink()`. `ss_do_close()` makes a call to `sock_orphan()` which marks the socket dead by doing
```C
sock_set_flag(sk, SOCK_DEAD);
```
See here: http://lxr.free-electrons.com/source/include/net/sock.h#L1547

From that point on socket callbacks are not called by the kernel as typical socket callback invocation looks like this:
```C
if (!sock_flag(sk, SOCK_DEAD))
        sk->sk_state_change(sk);
```
That is the reason `ss_tcp_state_change()` is never called for TCP_CLOSE state in the regular course of action in Tempesta. It is only called on direct move to TCP_CLOSE state in case of any error, before `ss_do_close()` is called by Tempesta to close the socket.

**Comment by krizhanovsky** [comment]
The change is required for TfwBomber only. Since the benchmark tool isn't used much in 0.5, move the task to 0.6.

**Comment by krizhanovsky** [comment]
We're not going to spend more resource for TfwBomber, https://github.com/tempesta-tech/tempesta/issues/879#issuecomment-1485862857
