### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#484]
We have hardware servers and Amazon cloud testbeds, which are idle most of the time, so we need to utilize the resources for long running tests. The test suite must be easily suspended and waken up to let developers to run short tests. The short tests still means the kernel update and restart, so the suite should remember the current test number when it was suspended and continue from the test when it's waken up.

Basically, we don't need every-day commits and code integrations. Rather we need some script environment to runs heavy tests in the hardware servers and cloud testbeds. Continuous deployment must be implemented, so there is no need human actions to deploy current development branch for testing after each merge of a developer's branch. It also means that we need integration, stability and performance testing suite in tempesta/ directory (maybe it has sense to consider separate repository to keep the heavy tests) - the test must code all the system (including TempestaDB). The tests can use current functional tests, but rather emphasise long running stuff.

[BuildBot](https://buildbot.net/), which is simpler than [Jenkins](https://jenkins.io/), should be considered for automated builds and test runs, but I'm not sure whether it's applicable since we have to reboot the system after a kernel setup. We need to test bare metal versions as well. However, we also have to deploy KVM and Docker on the servers to test the scenarios plus to Xen HVM used in Amazon's testbed. [Travis CI](https://travis-ci.org/) is also not suitable since it uses only small VMs for tests while we need powerful hardware for stress tests, custom kernel are also an issue. It seems Jenkins and Travis CI are hard to setup on own. Also Java-based systems probably aren't a good to fit our techstack.

I'd be good to integrate it with static code analysing tool like [Coverity scan](https://scan.coverity.com/projects/tempesta-tech-tempesta).

Test results must be mailed to whole the team.

More discussion about related topics can be found in the [Wiki](https://github.com/tempesta-tech/tempesta/wiki/Development-Guidelines). The [Development branches chapter](https://github.com/tempesta-tech/tempesta/wiki/Development-Guidelines#development-branches) must be updated in finishing the issue and all the appropriate Git branches must be created. So please reassign the issue to me when you finish the task, so I can create the branches.

As it's described in [CI Wiki](https://github.com/tempesta-tech/tempesta/wiki/Development-guidelines#continuous-integration-ci) CI-specific tests must be kept in a separate repository since they're mostly unusable by an arbitrary user.

**Comment by sergsever** [comment]
Есть момент:
We're only showing your public repositories. You can find your private projects on travis-ci.com.

**Comment by krizhanovsky** [comment]
Please also develop a necessary integration API to weork with [GitHub status checks](https://developer.github.com/v3/repos/statuses/) for commits to master branch.

**Comment by krizhanovsky** [comment]
The system must constantly run the same test suite in a loop and monitor dmesg for Oops messages. This is wished to catch tricky crashes and warning by long term tests.

**Comment by krizhanovsky** [comment]
CI system must use debugging kernel, at least following options must be switched on:
```
CONFIG_DEBUG_RODATA=y
CONFIG_SCSI_DEBUG=m
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_FS=y
CONFIG_DEBUG_KERNEL=y
CONFIG_DEBUG_PAGEALLOC=y
CONFIG_DEBUG_PAGEALLOC_ENABLE_DEFAULT=y
CONFIG_DEBUG_OBJECTS=y
CONFIG_DEBUG_OBJECTS_FREE=y
CONFIG_DEBUG_OBJECTS_ENABLE_DEFAULT=1
CONFIG_DEBUG_SLAB=y
CONFIG_DEBUG_SLAB_LEAK=y
CONFIG_HAVE_DEBUG_KMEMLEAK=y
CONFIG_HAVE_DEBUG_STACKOVERFLOW=y
CONFIG_DEBUG_SPINLOCK=y
CONFIG_DEBUG_MUTEXES=y
CONFIG_DEBUG_LOCK_ALLOC=y
CONFIG_DEBUG_LOCKDEP=y
CONFIG_DEBUG_BUGVERBOSE=y
CONFIG_DEBUG_LIST=y
CONFIG_DEBUG_SET_MODULE_RONX=y
CONFIG_X86_DEBUG_FPU=y
```

**Comment by vladtcvs** [comment]
Buildbot is used for building and running functional and stress tests

**Comment by vladtcvs** [comment]
Progress: buildbot can run separate tests, not only whole test set

**Comment by vladtcvs** [comment]
Buildbot 1.1 installed, github sends webhooks on PR, buildbot builds and runs tests and send response with build and testing result
