### ISSUE TITLE
[RFC7234] Add request method to cache key

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#493]
We must return cached responses to exactly matching request methods only. I.e. if we receive HEAD requests, we must not return response cached for GET method. [RFC 7234](https://tools.ietf.org/html/rfc7234#section-2):

```
    The primary cache key consists of the request method and target URI.
```

So we should add request method to cache key.

**Comment by ikoveshnikov** [comment]
Issue is closed in 51cf3b05a094c48ac3d0893589764d9b32de525a

Now messages are cached with respect to request method.
