### ISSUE TITLE
[Cache] purging

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#501]
Manual cache purging must be implemented. An example of the purging is

        $ curl -X PURGE <URL>

which sends

        PURGE / HTTP/1.1\r\n
        User-Agent: curl/7.40.0\r\n
        Host: <host>\r\n
        Accept: */*\r\n
        \r\n

Following new configuration options must be introduced:

* `cache_purge` - cache purging mode, binary variable for first implementation, but can be extended in future (e.g. setting eviction strategy and speed for purged entries). `"invalidate"` value (default and the first implemented) means that purged entries are just invalidated and still can be returned to a client under certain conditions (#522, note that for 0.5 we never return stale responses, so this is just fake purging). `"purge"` means real purging backed by TDB deletion operator (this mode depends on #516).

* `cache_purge_acl` - control who can purge the cache by list of IP addresses or netmasks.

See [Nginx](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_purge), [Varnish](https://www.varnish-cache.org/docs/3.0/tutorial/purging.html) and [Squid](http://wiki.squid-cache.org/SquidFaq/OperatingSquid#How_can_I_purge_an_object_from_my_cache.3F) implementations as reference examples.

Wildcard purging is not necessary at this time.

**Use case.** If some content is changed at upstream server, then PURGE request followed by GET request will update appropriate entry in the cache.

**Comment by keshonok** [comment]
Implemented in #558.
