### ISSUE TITLE
Tempesta's modified SKB data may get corrupted in skb_linearize()

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#503]
When modifying SKB's data, Tempesta may map a piece of skb's linear data to a paged fragment. That leads to the following complications that may result in data corruption.
- Once that kind of data mapping is done, any subsequent skb modification cannot use the fast path optimization where `skb->tail` is moved forward towards `skb->end`.
- In certain cases in the egress path the skb may get linearized (`skb_linearize()`). Underneath of that `__pskb_pull_tail()` is used. The function may use the area between `skb->tail` and `skb->end` when copying data. If there's skb's data there that had been mapped to a paged fragment, then the data is corrupted in the process.

This lends itself to a flag that is a property of an skb itself as it need to travel across the Linux kernel along with the skb it belongs to. Given this flag, `skb_linearize()` can be modified to take care of this issue when Tempesta kernel is running.

Also, this flag needs to be checked when the above mentioned fast path modification is possible.

At first glance, there's a straightforward way of checking whether a piece of linear data had been mapped to a paged fragment:
```C
static inline bool
__skb_head_is_mapped(struct sk_buff *skb)
{
        struct page *pg_head;

        if (!skb_is_nonlinear(skb))
                return;

        pg_head = virt_to_head_page(skb->head);
        for (i = 0; i < skb_shinfo(skb)->nr_frags; ++i) {
                skb_frag_t *f = &skb_shinfo(skb)->frags[i];
                if (skb_frag_page(f) == pg_head)
                        return true;
        }

        return false;
}
```

However this is a heavyweight check that may spend lots of cycles. Also, one can imagine a case (though highly improbable), where the mapped paged fragment is shifted/moved to the next skb. In that case, this check would yield incorrect result.

A simple check for a flag would be significantly faster and always correct.

I think that a good place for the flag is `skb_shinfo(skb)->tx_flags`. There's one bit available there that can be used for that purpose. The flag can be called `SKBTX_MAPPED_HEAD` which is in line with the other names there. Then, a simple check for that flag would yield the desired result, and it can be used in both `ss_skb.c` in the fast path case, and in `__pskb_pull_tail()`.

**Comment by milabs** [comment]
Unfortunately, we can't use `skb_shinfo(skb)->tx_flags` as no free bits there. Taking a look at `skb->peeked` instead.

**Comment by milabs** [comment]
Fixed via:
23ef7571af604ddd0637f0a030eb5ff3a61a1fba

Kernel update:
https://github.com/tempesta-tech/linux-4.1-tfw/commit/a0a9d45fa79062034a7c6fc7423accb89a6df60f
