### ISSUE TITLE
[RFC 7234] Cache entry freshness

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#513]
[RFC 7234 4.2](https://tools.ietf.org/html/rfc7234#section-4.2) defines a cache entry freshness calculation. This must be generic function which can be called at request service time as well as in cache eviction thread.

The issue depends on #507 (Date is required header), #1 (we must generate warnings if [heuristic freshness](https://tools.ietf.org/html/rfc7234#section-4.2.2) is used).

Depends on #523 in that response `max-age` must be accounted.

This should generate 113'th warning (#1), mark this as TODO.

**Comment by keshonok** [comment]
Implemented in #559.
