### ISSUE TITLE
[RFC 7234] Process conditional requests for cache entries revalidation

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#519]
Tempesta must process `If-Modified-Since` header, see [RFC 7234 4.3.2](https://tools.ietf.org/html/rfc7234#section-4.3.2). `If-Match` and `If-None-Match` must be parsed as well since they affect `If-Modified-Since` processing, but their processing is subject for upcoming issues.

Depends on #1 in sending 111'st warning and #529 (ETag).

**Comment by ikoveshnikov** [comment]
Closed in 21bc2f1fdbde214259c83966e5c9598002107210
