### ISSUE TITLE
[RFC 7234] process Cache-Control

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#523]
Tempesta parses Cache-Control header for both the requests and responses, but doesn't do any logic on `TfwCacheControl`. [RFC 7234 5.2](https://tools.ietf.org/html/rfc7234#section-5.2) requires following logic to be implemented.

**Request cache control processing:**

1. `max- age` - Age must be processed (#507) and freshness (#513) is calculated for cached response before sending it to the client;

2. `max-stale` - like previous, requires #507 and #513;

3. `min-fresh` - like previous, requires #507 and #513;

4. `no-cache` - if `TFW_HTTP_CC_NO_CACHE` flags is set, don't lookup the cache;

5. `no-store` - if `TFW_HTTP_CC_NO_STORE` flags is set, then probably fulfill the request from cache, but if the cache doesn't have the entry, don't store response received from upstream in the cache;

6. `no-transform` - we don't do any [transformations](https://tools.ietf.org/html/rfc7230#section-5.7.2) for now, so just ignore;

7. `only-if-cached` - if `TFW_HTTP_CC_NO_OIC` flag is set, then don't forward the request to upstream, but rather fulfill the request from the cache or send 504.

**Response cache control processing:**

1. `must-revalidate` - `TfwCacheEntry` must be extended by appropriate flag. Depends on #513 and #516. Since TDB doesn't support update or delete operators for now, so first implementation just should bypass the cache and just forward requests and responses;

2. `no-cache` - just don't store the response in the cache. Not necessary to parse field-names in the directive;

3. `no-store` - just the same as `no-cache`;

4. `no-transform` - just ignore since we don't transform responses for now;

5. `public` - basically we already store all the responses as public, but #3 must be considered;

6. `private` - must be equivalent to `no-store`;

7. `proxy-revalidate` - the same as `must-revalidate`. If `private` is also set, then just bypass the cache and ignore the directive;

8. `max-age` - the value must be stored in `TfwCacheEntry` such that we can calculate the cache entry freshness (#513);

9. `s-maxage` - just rewrite `max-age` and Expires values in `TfwCacheEntry`.

`Pragma: no-cache` from #526 must be processed as well.

**Comment by keshonok** [comment]
Implemented in #559.
