### ISSUE TITLE
[RFC 7230] Via header

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#524]
[RFC 7230 5.7.1](https://tools.ietf.org/html/rfc7230#section-5.7.1) requires sending `Via` header for each forwarded message. We can just add a new header. `hdr_via` configuration option must be introduced, such that an administrator can specify `received-by` value. Default value should be `tempesta_fw`. Comment should be `"TFW_NAME " " TFW_VERSION`. Example of default value (default Tempesta protocol is 1.1):

        Via: 1.1 tempesta_fw (Tempesta FW 0.5.0-pre2)

**Comment by keshonok** [comment]
Implemented in #562.
