### ISSUE TITLE
Bugs in implementation of __hdr_append()

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#527]
Current implementation of `__hdr_append()` has several bugs:
- The last chunk of the header string should be used. However, that is not happening if there are duplicate headers.
- The skb from the last chunk should be used. However, that's not happening, and the skb from the first chunk of the header string is used instead.
- The end of the header string may match the end of a chunk of data in an skb. However, `ss_skb_get_room()`, as well as other functions in `ss_skb.c` operate on assumption that the split point (the place where the data is added or deleted) never points at the end of a chunk of data in an skb. If that happens, an error is returned and the data is not appended to the header string.

The issue in the last bullet requires that this case is recognized in `__skb_fragment()`, and the the split point is moved to the start of the next chunk of data in the message, be that the current or the next skb (see `__it_next_data()`).

**Comment by milabs** [comment]
Fixed via:
aebe6e7dc2b3e7f5c6de28a0a536c5c8e15b9b63
