### ISSUE TITLE
Appending to an existing HTTP header doesn't work as intended.

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#561]
Tempesta at current master (c055791).
Add `X-Forwarded-For:` header twice. The first time it is added, and that works fine. The second time the value of the header should be apended to the value of the existing header added in the previous step. That doesn't work as intended. Instead of appending at the end of the header before CRLF, it appears that the data is appended after CRLF. That leads to an incorrect HTTP message as after the second XFF is added the double CRLF is lost.

**Comment by milabs** [comment]
This is one of the possible solutions: 7ee0d5998f3deaaf1152df66c7c45f82fce4eca7.

**Comment by keshonok** [comment]
It appears the the issue is that the header strings are not created equal. The strings that come out of the parser do not include the trailing `CRLF`. Instead, `eolen` is set for those strings. However, that's not true for header strings that are created in Tempesta for addition, substitution, or deletion of header fields to/from an HTTP message.

I believe that the functions that implement modification of HTTP headers should work with `eolen`, and not with trailing `CRLF` in the strings. Currently, `__hdr_del()` and `__hdr_sub()` take `eolen` into consideration, but `__hdr_add()` and `__hdr_append()` do not. Likewise, `tfw_http_msg_hdr_xfrm()` and `tfw_http_msg_hdr_add()` do not take `eolen` into consideration.

`eolen` should be set for all strings that are or become part of the HTTP message.
