### ISSUE TITLE
Application Performance Monitoring (APM)

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#564]
Tempesta must provide APM for advanced DDoS mitigation logic as well as for system administration purposes. APM must extend `/proc/tempesta/perfstat` by application response time in milliseconds:

* maximum

* minimum

* middle value

* percentiles (50, 75, 90, 95)

**Comment by krizhanovsky** [comment]
[The implementation and basic test](https://github.com/tempesta-tech/tempesta/commit/7922d9a5df41ab2166f7492b91f3b906849065ab) for algorithm calculating percentilies and their trends on data stream.

**Comment by keshonok** [comment]
Implemented in 4e1e7a3
