### ISSUE TITLE
Advanced Load Balancing

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#565]
Load balancing algorithms must be extended in following way.

Firstly, Round-robin algorithm must be renamed to Ratio and extended by weights, probably dynamic. E.g. if we have 2 servers and the first has two times more CPUs than the second, then we can say that the first one has weight 2 and the first one 1. I.e. the scheduler must send requests in [1, 1, 2] instead of current [1, 2] manner. Generally speaking current RR scheme is exactly Ratio where all the servers have equal weights.

The weights can be configured manually or left for dynamic calculation. I.e. default weights for all the servers is 1 and a user can configure manually the server weights or specify `dynamic` for dynamic weights calculation. Dynamic ratio depends on #564: the weights relation is exactly relation of maximum, minimum, average or particular percentile (must be configured as well, average is the default) response time for last `T` seconds (`T` should be also configurable, 5 minutes by default).

The next option for Dynamic ration is more intelligent Predictive which must consider trend in backend response time as well as the response time itself. The exact algorithm for current weight calculation is TBD.

It worth to mention that we don't implement Fastest and Least connections algorithms like [F5 does it](https://devcentral.f5.com/articles/intro-to-load-balancing-for-developers-ndash-the-algorithms), because:
1. Fastest is essentially Dynamic Ratio, but firstly causes congestion/bufferbloat problem and then degrades the server ratio. It's pretty stupid way to balance load;
2. Tempesta FW makes significant efforts to pass HTTP traffic to backend servers in persistent connections as efficiently as possible, so all the upstreams have always equal number of connections. BTW https://github.com/tempesta-tech/tempesta/pull/423 must be resolved ASAP (this is TODO for me and @keshonok).

`sched_srv_conn` from #593 must also be implemented.

Also please update/develop appropriate unit tests as for current schedulers.

**Comment by krizhanovsky** [comment]
[The implementation and basic test](https://github.com/tempesta-tech/tempesta/commit/7922d9a5df41ab2166f7492b91f3b906849065ab) for algorithm calculating percentilies and their trends on data stream.

**Comment by krizhanovsky** [comment]
**NOTE.** Generally speaking longer response time doesn't mean that server processing appropriate request is overloaded. Response time depends on *type* of the request: it can involve long database query, other, probably remote, service request or just some script execution. HTTP scheduler should be used to correctly distribute request by resource URI. While the same upstream can process all request type, there should be several HTTP groups for different processing time. So the scheduling algorithms will compare response time for similar resources, not to compare apples with oranges.

Please add the comment to schedulers Wiki, #656.

**Comment by keshonok** [comment]
Implemented via #718.
