### ISSUE TITLE
SSL key and certificate description

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#611]
Please describe how to generate `certificate.pem` and `certificate-key.pem` in README. Basically `mkcert` scripts/tls/ just calls one openssl comamand, so it's better just to show the command to generate the certificate in README. Also please describe dummy generation of pem key and certificate in README, such that the commands are enough to run testing installation. Meantime scrips/tls should be removed.

**Comment by milabs** [comment]
Fixed via 38fab1fb1f5d3e7fffed2ac29a1476319356b6ae
