### ISSUE TITLE
Response with an empty body and missing Content-Length: header is not handled correctly

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#629]
When there's no `Content-Length:` header field in a response, then the response is considered complete after a server closes the connection. That works fine if a response has a body. However it doesn't work correctly when there's just the response header and no response body.

**Comment by keshonok** [comment]
When a CRLF is found after the set of all HTTP headers of a response, the parser moves to `Resp_BodyUnlimStart` state. As there's no body (yet), the parser sees that there's no more data and returns to the caller with the result `POSTPONE`. Then the back end server closes the connection, and in this case that means that the HTTP response has no body indeed. However, the parser has never really entered and processed the state `Resp_BodyUnlimStart`, and therefore has never moved to the next state `Resp_BodyUnlimRead`. The function `tfw_http_parse_terminate()` is based on the fact that the parser is in the state `Resp_BodyUnlimRead`, and therefore it doesn't return the expected result.

Resume: The function `tfw_http_parse_terminate()` must expect both `Resp_BodyUnlimStart` and `Resp_BodyUnlimRead` states.

**Comment by ikoveshnikov** [comment]
fixed in dc2409bd84864f282092ace89b9777715d015b1a
