### ISSUE TITLE
Binary packages

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#640]
Create Make rule to build Debian packages for the kernel and tempesta_fw. Kernel should be moved to 4.9 as next **(?)** [Debian release](https://packages.debian.org/source/stretch/linux) is [based on the kernel](https://packages.debian.org/source/stretch/linux). At this point Tempesta will be fully compatible with standard distro w/o any requirements to install or compile third-party software.

CentOS support isn't required for now, so README and other documentation should be updated that we support Debian 9 only.

Debian Stretch is going to use either Linux 4.10 or 4.9, so we'll have to move to the newer kernel as well. The package must use the same .config as the original Debian's kernel. Make sure that virtualization (either Xen and LXC) is fully supported by the kernel (i.e. the kernel can run in Xen domU as well as in Xen dom0 or LXC host system), so the package can be used in [clouds](https://github.com/tempesta-tech/tempesta/wiki/Clouds).

The package must configure all necessary `systemctl` scripts, so that Tempesta FW can be started/stopped using `systemctl` as well as added to bootup process.

From #251. We must be able to support user incidents, so Tempesta FW's packages must set `kernel.panic*` sysctls for automatic system reboot on various kernel faults. Moreover, the package must implement dependency on crash utility and properly set it up. See following links for the tool ( @keshonok has good experience with the tools, so he can help you with them) :
* http://people.redhat.com/anderson/crash_whitepaper/
* https://www.kernel.org/doc/Documentation/kdump/kdump.txt
* http://www.dedoimedo.com/computers/crash-book.html

Please write 2 Wiki pages:
1. **Installation** describing how to download and install the package including all prerequisites (can be taked from current README);
2. **Report an incident** - how to gather dmesg and crash output, how to submit the data to the development team and how to create a new issue at github.

**Comment by ikoveshnikov** [comment]
Fixed via f42263b279ed81bd1d49fe2dd02a5cda7999f115
