### ISSUE TITLE
Flaky network test

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#654]
We still have server reconnection issue on flaky network:

1. ifconfig eth2 down
2. ./scripts/tempesta.sh --start
3. ifconfig eth2 up
4. netstat -npta

`eth2` is the interface which Tempesta uses for upstream communications. Step (4) doesn't show any established connections.

The scenario must be tested by functional test suite. You can use iptables instead of down/up an interface, e.g.

        # iptables -A INPUT -p tcp --dport 8080 -i lo -j DROP
        # iptables -D INPUT -p tcp --dport 8080 -i lo -j DROP

, where 8080 is listening port of upstream server.

The test must switch off networking before Tempesta start and during the workload:

1. switch off networking
2. start Tempesta in pure proxy mode, w/o caching
3. do test checks
4. switch on networking
5. send request
6. switch off networking
7. send other request
8. do test checks
9. switch on networking
10. do final test checks

**Comment by krizhanovsky** [comment]
The test address #751, so move it to 0.5

**Comment by ikoveshnikov** [comment]
fixed in  0a482599678decacc366636ad5db24f265ce0344
