### ISSUE TITLE
Move README to Wiki

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#656]
Currently we have large monolithic README.md which describes almost everything about Tempesta and it's configuration. Please move it to separate Wiki pages with reader-friendly contents.

Extend Wiki by usage examples, Tempesta FW's design considerations and limitations (e.g. RAM-limited cache), comparison with Nginx and HAProxy.

**Comment by ikoveshnikov** [comment]
Although description of configuration directives was moved to wiki pages, second part of the issue is still open: still need to provide usage examples, comparison with other proxies and so on. Thus i leave the issue open.
