### ISSUE TITLE
Client friendly requests blocking

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#658]
Currently HTTP parser can return TFW_BLOCK in many cases. Meantime when TFW_BLOCK is returned from `tfw_http_msg_process()`, then the message is just silently dropped. So if a client uses poor browser, then they typically just see hang pages loading. System administrator should be able to specify the behaviour: return HTTP error message to a client of just silently block malformed and malicious message (requests and responses). This could be done by a new configuration option like

        block_action <drop|reply> [nolog]

`drop` is just current behaviour while `reply` sends error response to a client. Optional argument `nolog` requires don't do logging the reason for blocking. By default Tempesta FW must write to the log why particular message was blocked. I assume it could be done by replacing statements like 

        return TFW_BLOCK;

by

        return tfw_block("Content-Length with Transfer-Encoding in the same request");

, where `tfw_block()` checks configuration variable and does the logging.

**Comment by krizhanovsky** [comment]
There is difference between malicious and malformed requests: we should spend as little as possible resources (i.e. silently block) for the first ones and provide reasonable user-friendly responses for the second ones. So `TFW_DROP` should be introduced to handle malformed requests while `TFW_BLOCK` should be used to filter our malicious requests. Also there should possibility to configure actions for the two different request types in different ways.

**Comment by krizhanovsky** [comment]
Currently we just send HTTP error codes with empty body, so a user agent (tested with Firefox at least) just shows blank page. Thus, some predefined HTML body must be sent as well. Further we should allow a user to configure the error page body as it's done in all Web servers.

**Comment by krizhanovsky** [comment]
The task seems somewhat more complicated than it was expected initially. The problem is if `connection_recv()` returns `TFW_BLOCK` then `ss_tcp_data_ready()` calls `ss_linkerror()` to immediately close the client connection. (Note that `ss_tcp_state_change()` doesn't call `ss_linkerror()` if `ss_tcp_process_data()` returns bad code and this must be fixed.) Meantime, if a client has pipelined many HTTP requests, then they're can be on the fly while we're experiencing the blocking logic, so the connection can be closed before transmission of responses for previous good requests and it's unclear how to send the HTTP error response.

The absolute rule is that we must obey the requirement to keep responses in the same sequence as ingress requests, even for malicious (as we suppose) clients (which can be just a proxies forwarding traffic of an attacked along normal requests). Thus, the HTTP error message must use the same transmission queue as normal responses. Meantime, HTTP layer must still return TFW_BLOCK or similar code to lower SS layer to stop processing of following data from the client.

Suppose a client sends us 4 requests: the 1st one is fine, the 3rd one requires the HTTP error response, 2nd one is still not answered by a backend and the last 4th request arrived while we were processing 3rd request, so we don't answer it. We must forward response for the 1st requests ASAP and wait for the 2nd response only after which 3rd, error response, is sent to the client.

I propose following solution for the problem:
1. introduce bad/suspected connection flag at HTTP layer, just like TFW_HTTP_NON_IDEMP marking an HTTP request as suspicious as well as a connection having the request in the queue. The flag means that we're not interested in following client's data and should close the client connection ASAP. (That's different from normal error codes which can be produced by various server problems).
2. Introduce the similar flag at SS layer. When the flag is set, then `ss_tcp_process_data()` must not call upper layer for ingress data and just drop the data. However, then connection must remain valid in TCP sense, so the dropped data must be properly acknowledged, i.e. we read the data, but don't produce any reply for it.
3. HTTP response forwarding routines must inspect the suspicious connection flag and close the connection as soon as the suspicious request is responded, all following requests (4th in the example above) must be just dropped.
4. Callers of `ss_tcp_process_data()` must check the suspicious connection flag and do not call `ss_linkerror()` if it's set.

@aleksostapenko , @ikoveshnikov any thoughts?

**Comment by aleksostapenko** [comment]
I agree with proposed solution.

**Comment by keshonok** [comment]
There's also an old `TFW_STOP` and `SS_STOP` flags. The original intention was to stop processing subsequent messages from a client in certain conditions. However, that goal had never been quite accomplished. SS would stop processing the queue of incoming SKBs and drop all SKBs in the queue, yet it would still continue processing incoming SKBs if a client sent more and more requests for whatever reason. Before Tempesta had a chance to close the client connection (which would happen after a response to the client), more requests from that client could have been accepted and processed.

Now that there's a reliable mechanism to drop a client connection when necessary, and stop communication with the client until that happens, I believe that `TFW_STOP` and `SS_STOP` can be eliminated, and dropping of a client connection can be implemented using the new mechanism.

**Comment by krizhanovsky** [comment]
@keshonok yeah, good point. In this sense `TFW_STOP`/`SS_STOP` duplicates the new `Conn_Suspected`. It'd be good to unify both the mechanisms. @aleksostapenko please consider a unification patch, probably it has sense to rename `Conn_Suspected` to something like `Conn_Stop` since now it'll be responsible for stopping messages processing in normal `Connection: close` as well as in case of Frang blocking.
