### ISSUE TITLE
Schedulers functional test

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#659]
At least following functionality must be covered by the functional test:

1. HTTP scheduler working over at least 100 server groups emulating 100 virtual hosts;

2. servers failovering - servers must get load when they return to normal operation while the service must stay working during failovering. This point depends on #419 and #383: currently the system returns errors if upstream connection is reset. After fix of the issues there should not be such errors.

3. Servers backup - if an upstream is down and backup server is configured, it should get the traffic. When the upstream backs to normal operation, the backup should not receive traffic.

4. All the schedulers, including #593 and #565 must be involved in the test.

5. Some stress must be put onto the configurations to verify that there is no crashes. So some traffic generator like `wrk` should be used.

**Comment by ikoveshnikov** [comment]
implemented in c8b56b4ddefc5071976a144d44ce069e02669913
