### ISSUE TITLE
Dead lock at reading /proc/tempesta/servers/

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#664]
The test scenario is described in https://github.com/tempesta-tech/tempesta/issues/651#issuecomment-266771066 . After the test

        # cat /proc/tempesta/servers/127.0.0.1\:8080

leads to following deadlock

        [ 1567.900025] =================================
        [ 1567.900025] [ INFO: inconsistent lock state ]
        [ 1567.900025] 4.1.27+ #28 Tainted: G           O   
        [ 1567.900025] ---------------------------------
        [ 1567.900025] inconsistent {IN-SOFTIRQ-W} -> {SOFTIRQ-ON-R} usage.
        [ 1567.900025] cat/4213 [HC0[0]:SC0[0]:HE1:SE1] takes:
        [ 1567.910067]  (&data->stats.asent[0].rwlock){++-+..}, at: [<ffffffffa037fa8f>] tfw_apm_stats+0x4f/0xb0 [tempesta_fw]
        [ 1567.910067] {IN-SOFTIRQ-W} state was registered at:
        [ 1567.910067]   [<ffffffff810b4189>] __lock_acquire+0x449/0x1cb0
        [ 1567.910067]   [<ffffffff810b6277>] lock_acquire+0xb7/0x2b0
        [ 1567.910067]   [<ffffffff81606533>] _raw_write_lock+0x33/0x50
        [ 1567.910067]   [<ffffffffa037f8a2>] tfw_apm_prcntl_fn+0x512/0x6b0 [tempesta_fw]
        [ 1567.910067]   [<ffffffff810d981d>] call_timer_fn+0x9d/0x4a0
        [ 1567.910067]   [<ffffffff810da1ec>] run_timer_softirq+0x20c/0x490
        [ 1567.910067]   [<ffffffff81062475>] __do_softirq+0xd5/0x640
        [ 1567.910067]   [<ffffffff81062c95>] irq_exit+0xa5/0xb0
        [ 1567.910067]   [<ffffffff8103b4f1>] smp_apic_timer_interrupt+0x41/0x50
        [ 1567.910067]   [<ffffffff816077a0>] apic_timer_interrupt+0x70/0x80
        [ 1567.910067]   [<ffffffff8100f51a>] arch_cpu_idle+0xa/0x10
        [ 1567.910067]   [<ffffffff810a995b>] cpu_idle_loop+0x25b/0x520
        [ 1567.910067]   [<ffffffff810a9c2e>] cpu_startup_entry+0xe/0x10
        [ 1567.910067]   [<ffffffff81039213>] start_secondary+0x143/0x170
        [ 1567.910067] irq event stamp: 2609
        [ 1567.910067] hardirqs last  enabled at (2609): [<ffffffff811b5657>] __kmalloc+0x97/0x6f0
        [ 1567.910067] hardirqs last disabled at (2608): [<ffffffff811b5616>] __kmalloc+0x56/0x6f0
        [ 1567.910067] softirqs last  enabled at (1980): [<ffffffff8106260b>] __do_softirq+0x26b/0x640
        [ 1567.910067] softirqs last disabled at (1975): [<ffffffff81062c95>] irq_exit+0xa5/0xb0
        [ 1567.910067] 
        [ 1567.910067] other info that might help us debug this:
        [ 1567.910067]  Possible unsafe locking scenario:
        [ 1567.910067] 
        [ 1567.910067]        CPU0
        [ 1567.910067]        ----
        [ 1567.910067]   lock(&data->stats.asent[0].rwlock);
        [ 1567.910067]   <Interrupt>
        [ 1567.910067]     lock(&data->stats.asent[0].rwlock);
        [ 1567.910067] 
        [ 1567.910067]  *** DEADLOCK ***
        [ 1567.910067] 
        [ 1567.910067] 1 lock held by cat/4213:
        [ 1567.910067]  #0:  (&p->lock){+.+.+.}, at: [<ffffffff811efbb8>] seq_read+0x38/0x3a0
        [ 1567.910067] 
        [ 1567.910067] stack backtrace:
        [ 1567.910067] CPU: 0 PID: 4213 Comm: cat Tainted: G           O    4.1.27+ #28
        [ 1567.910067] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.9.1-1.fc24 04/01/2014
        [ 1567.910067]  0000000000000000 ffff880119743aa8 ffffffff815fd9db ffff880119af6950
        [ 1567.910067]  ffffffff82df8d80 ffff880119743b08 ffffffff815f92f9 0000000000000000
        [ 1567.910067]  ffff880100000001 ffff880100000001 ffffffff8101462a ffff880119af6950
        [ 1567.910067] Call Trace:
        [ 1567.910067]  [<ffffffff815fd9db>] dump_stack+0x67/0x90
        [ 1567.910067]  [<ffffffff815f92f9>] print_usage_bug+0x1f3/0x204
        [ 1567.910067]  [<ffffffff8101462a>] ? save_stack_trace+0x2a/0x50
        [ 1567.910067]  [<ffffffff810b2c20>] ? print_shortest_lock_dependencies+0x1d0/0x1d0
        [ 1567.910067]  [<ffffffff810b3763>] mark_lock+0x223/0x2b0
        [ 1567.910067]  [<ffffffff810b41f2>] __lock_acquire+0x4b2/0x1cb0
        [ 1567.910067]  [<ffffffff810b4910>] ? __lock_acquire+0xbd0/0x1cb0
        [ 1567.910067]  [<ffffffff810b6277>] lock_acquire+0xb7/0x2b0
        [ 1567.910067]  [<ffffffffa037fa8f>] ? tfw_apm_stats+0x4f/0xb0 [tempesta_fw]
        [ 1567.910067]  [<ffffffff81052bf1>] ? kmemcheck_pte_lookup+0x11/0x40
        [ 1567.910067]  [<ffffffff81606276>] _raw_read_lock+0x36/0x50
        [ 1567.910067]  [<ffffffffa037fa8f>] ? tfw_apm_stats+0x4f/0xb0 [tempesta_fw]
        [ 1567.910067]  [<ffffffffa037fa8f>] tfw_apm_stats+0x4f/0xb0 [tempesta_fw]
        [ 1567.910067]  [<ffffffffa0398b51>] tfw_srvstats_seq_show+0x71/0x130 [tempesta_fw]
        [ 1567.910067]  [<ffffffff811efc6d>] seq_read+0xed/0x3a0
        [ 1567.910067]  [<ffffffff812398f8>] proc_reg_read+0x38/0x70
        [ 1567.910067]  [<ffffffff811c78e3>] __vfs_read+0x23/0xd0
        [ 1567.910067]  [<ffffffff812ddbe4>] ? security_file_permission+0x84/0xa0
        [ 1567.910067]  [<ffffffff811c7e21>] ? rw_verify_area+0x51/0xd0
        [ 1567.910067]  [<ffffffff811c7f21>] vfs_read+0x81/0x140
        [ 1567.910067]  [<ffffffff811c8d84>] SyS_read+0x44/0xb0
        [ 1567.910067]  [<ffffffff811195cc>] ? __audit_syscall_entry+0xac/0x100
        [ 1567.910067]  [<ffffffff81606957>] system_call_fastpath+0x12/0x6f

**Comment by keshonok** [comment]
Fixed in ab94462.
