### ISSUE TITLE
Bad socket cpu locality on new Linux 4.8.15

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#668]
After moving to [Linux 4.8.15](https://github.com/tempesta-tech/linux-4.8.15-tfw) there are many warnings

        [   94.378748] net_ratelimit: 406 callbacks suppressed
        [   94.382632] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880098718a40 old_cpu=0 curr_cpu=2
        [   94.387874] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880098718a40 old_cpu=0 curr_cpu=2
        [   94.392556] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880098927540 old_cpu=0 curr_cpu=1
        [   94.392557] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880098927540 old_cpu=0 curr_cpu=1
        [   94.439161] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff8800b06da0c0 old_cpu=3 curr_cpu=2
        [   94.443579] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff8800b06da0c0 old_cpu=3 curr_cpu=2
        [   94.481354] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff8800af915540 old_cpu=2 curr_cpu=0
        [   94.483552] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff8800af915540 old_cpu=2 curr_cpu=0
        [   94.560506] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880098718a40 old_cpu=2 curr_cpu=3
        [   94.564996] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880098718a40 old_cpu=2 curr_cpu=3
        [   99.383667] net_ratelimit: 20 callbacks suppressed
        [   99.385786] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880098619500 old_cpu=1 curr_cpu=3
        [   99.389106] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880098619500 old_cpu=1 curr_cpu=3
        [  100.317697] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880098187500 old_cpu=1 curr_cpu=3
        [  100.322128] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880098187500 old_cpu=1 curr_cpu=3
        [  100.868599] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880098602a40 old_cpu=2 curr_cpu=0
        [  100.870961] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880098602a40 old_cpu=2 curr_cpu=0
        [  101.308907] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880098256ac0 old_cpu=0 curr_cpu=3
        [  101.314465] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880098256ac0 old_cpu=0 curr_cpu=3
        [  101.389476] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff8800985ec040 old_cpu=0 curr_cpu=2
        [  101.392882] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff8800985ec040 old_cpu=0 curr_cpu=2

Only "state change" and "close" events are affected. The issue seems due to the new Linux sockets locking optimizations. I replace `SS_WARN` by `SS_DBG` to not to irritate users. Probably there is nothing serious in the warnings and we could just safely remove the check.

**Comment by krizhanovsky** [comment]
It seems there is also some performance degradation: wrk running on 8 cores fully loads 12 cores Tempesta machine.

**Comment by ikoveshnikov** [comment]
Time to time i have the same warnings with 4.1.27 kernel
```
  289.255977] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  289.256037] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  289.256079] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  289.256185] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  289.256286] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  289.260151] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b20800 old_cpu=1 curr_cpu=0
[  289.265203] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b21000 old_cpu=1 curr_cpu=0
[  289.305010] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b21800 old_cpu=1 curr_cpu=0
[  289.313559] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  289.313706] [sync_sockets] Warning: Bad socket cpu locality on <recv>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  294.263869] net_ratelimit: 4 callbacks suppressed
[  294.264083] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880058b20800 old_cpu=1 curr_cpu=0
[  294.264290] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880058b20800 old_cpu=1 curr_cpu=0
[  294.464990] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880058b21000 old_cpu=1 curr_cpu=0
[  294.465076] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880058b21000 old_cpu=1 curr_cpu=0
[  294.766038] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880058b21800 old_cpu=1 curr_cpu=0
[  294.766262] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880058b21800 old_cpu=1 curr_cpu=0
[  294.967098] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  294.967182] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff880058b20000 old_cpu=1 curr_cpu=0
[  345.487124] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff88005c36e000 old_cpu=0 curr_cpu=1
[  345.487253] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff88005c36e000 old_cpu=0 curr_cpu=1
[  396.297732] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff88005c3aa000 old_cpu=0 curr_cpu=1
[  396.297857] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff88005c3aa000 old_cpu=0 curr_cpu=1
[  396.793671] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff88005c3aa800 old_cpu=0 curr_cpu=1
[  396.793753] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff88005c3aa800 old_cpu=0 curr_cpu=1
[  396.977733] [sync_sockets] Warning: Bad socket cpu locality on <state change>: sk=ffff88005c3ab000 old_cpu=0 curr_cpu=1
[  396.977813] [sync_sockets] Warning: Bad socket cpu locality on <close>: sk=ffff88005c3ab000 old_cpu=0 curr_cpu=1
```
That started to happen quite recently, i will try to find commit that affect this

**Comment by krizhanovsky** [comment]
The issue affects #254 and #116: sometimes sockets are touched by different CPUs which leads to improper per-cpu active connections counting. So `HANDLE_TOO_LONG_WAIT()` must be adjusted with WARN_ON() on too long wait instead of just returning.

**Comment by krizhanovsky** [comment]
Performance degradations seems caused by #691 and/or #697, which are probably duplicate. #697 is fixed by https://github.com/tempesta-tech/linux-4.8.15-tfw/pull/2 , so remove "crucial" label.

**Comment by krizhanovsky** [comment]
Strictly speaking there is no guarantee that socket flows stuck the same CPU, see [discussion in #583](https://github.com/tempesta-tech/tempesta/issues/583#issuecomment-233215551). Thus, synchronous sockets must not rely on sockets leaving on the same CPUs. Per-cpu socket operations is a performance optimization, but not a synchronization.
