### ISSUE TITLE
Upstream servers performance and health checking

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#683]
Tempesta FW must gather and represent information about performance and availability of upstream servers. The information must be gathered in two ways:
1. automatic - when a user sends appropriate request to an upstream;
2. timer - when there was no appropriate request to an upstream for specified time.

The option should be configured in following way. `server` option must be extended by a new attribute `health`:

        server 1.2.3.4 conns_n=4 health=auto;
        server 1.2.3.5 health=h_monitor1;

`auto` means the first way of monitoring and `h_monitor1` in this example or any other modifier but `auto` identifies a monitor configuration declared before or after the server configuration (use some map to save the identifiers between configuration sections). Health monitor should be configured in following way:

        health_check h_monitor1 {
                request "GET / HTTP/1.1\r\nHost: example.com\r\n\r\n';
                request_url '/';
                resp_code 200 302 304;
                resp_crc32 A0123456;
                timeout 10;
        }

`request` determines full HTTP request string, `GET / HTTTP/1.0\r\n\r\n` by default. The request must be sent by Tempesta on timer defined by `timeout` configuration option, in seconds. The request must be used only if there were no client requests statisfying `request_url` during `timeout` time in automatic mode ot just by timer event. `request_url` is used to match only URL of requests instead of whole request strings (used SIMD string matching for this). `resp_code` lists response codes which are treated as successful, i.e. meaning that the server is alive. Any other response codes mean that the server is dead. `resp_crc32` defines successful CRC32 value, calculated over the received response. If Tempesta must update APM statistics for a server and it receives a response for request matching `request_uri` or it sent `request` by the timer, then it must calculate crc32 for whole body of the response (i.e. a user can just calculate crc32 over a file string the page and write it to the configuration file). A user can specify either of `resp_code` and `resp_crc32` or both of them.

If a server is dead, then we should do the same as in #672. Meantime, if we determined the server as dead (in context of this issue or #672), then Tempesta still must periodically (by timer, even in auto mode) try to send requests. If the server revives at some point, it must be properly returned to a schedulers' sets (as in #672).

Please add statistic counters to APM data (`/proc/tempesta/servers/`) - number of each HTTP error received form the server (probably one line per an error) and time until next health checking request. Now we have `Total schedulable connections`, so we can say that the server is dead if the counter is zero, but having HTTP layer availability it's necessary to add one more line saying whether the server is available in HTTP sense.

Please update [the Wiki page](https://github.com/tempesta-tech/tempesta/wiki/Servers:-Tempesta's-side) at the end.

**Comment by aleksostapenko** [comment]
Closed in context of https://github.com/tempesta-tech/tempesta/pull/877.
