### ISSUE TITLE
Frang: limit HTTP error codes (password crackers blocking)

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#717]
We have several requests for protection against passwords crackers. The problem can be generalized to block a client sending requests which leads to N specific HTTP error codes in a specified time frame T (in seconds). The syntax for the new rule should be as:

        http_resp_code_block <list of error codes> <limit> <time>

e.g.

        http_resp_code_block 401 403 3 10

**Comment by craig** [comment]
Or maybe causing <limit> error codes in a timeframe? Otherwise it might be easy to circumvent by doing a 200 request every <limit -1> requests.

**Comment by krizhanovsky** [comment]
Yeah, good point! In fact we do so for other Frang limits, so we should do the same in this limit.
