### ISSUE TITLE
Functional tests for Ratio scheduler

### ISSUE THREAD

**Issue by keshonok** [tempesta-tech/tempesta#728]
The Ratio scheduler has replaced the Round-Robin scheduler. While Ratio scheduler can operate in round-robin fashion as well, there's lots of new pretty complex functionality. The new functionality needs testing, and unit tests are not well suited for that. Functional testing is preferred and required.

The functionality that needs testing is:
* equal static weights -- currently also covered by unit tests;
* different static weights;
* dynamic weights based on stats from APM module;
* predictive weights based on stats from APM module.

**Comment by krizhanovsky** [comment]
Relates #712

**Comment by ikoveshnikov** [comment]
Closed by tempesta-tech/tempesta-test#66
