### ISSUE TITLE
Cfg: can't address implicit default group in sched_http_rules

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#748]
It is impossible to use `default` server group in `sched_http_rules` if it is not explicitly defined in config file.

E.g. the next config cannot be parsed correctly:
```
sched hash;
server 192.168.122.1:8000 conns_n=1;

srv_group backup {
sched hash;
server 192.168.122.1:8001 conns_n=1;

}
cache 0;

sched_http_rules {
  match default * * * backup=backup;
}
```
Tempesta log:
```
[  124.516470] [tempesta] ERROR: sched_http: srv_group is not found: 'default'
[  124.517535] [tempesta] ERROR: configuration parsing error
[  124.518707] [tempesta] ERROR: failed to start modules
```

Parsing of `sched_http_rules` section requires defining server groups before using them. But implicit  `default` group will be created only when configuration file will be fully parsed (see `tfw_sock_srv_start()` function). This breaks user experience, especially if user writes full configuration of implicit `default` group before `sched_http_rules` section.

Posiible solution: create implicit `default` server group when the first server of that group was encountered.

**Comment by krizhanovsky** [comment]
The proposal should work. It'd be expected if we require C-behavior: define something before using it. So if a user uses `default` group in `sched_http_rules` and next defines the default group, then we should fail to error because we already created the goup when faced it in the scheduler `sched_http_rules` section.

**Comment by krizhanovsky** [comment]
Relates #51 and should be fixed in the same PR.
