### ISSUE TITLE
Stress tests with real life requests

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#765]
Current our functional tests use mostly simple GET requests, but all the implemented (and at least several not implemented!) request types must be tested. Many HTTP headers (also which we parse and not aware about) must be tested. All the requests must be run with significant load.

Keep in mind that we're developing our own high-peformance fuzzer [TfwBomber](https://github.com/tempesta-tech/tempesta/issues/375), so the test for the issue must be relatively simple and take not so much time to execute as a part of whole functional tests run. The real fuzzing is left for TfwBomber.

**Comment by intelfx** [comment]
Ideas for new stress tests:

- [ ] cache stress test
      - mixed workload
      - all cache modes
- [ ] scheduling stress/performance test
      - mixed workload
      - dynamic, layered schedulers
- [ ] failovering stress/performance test
      - mixed workload
      - dying and reappearing servers
- [ ] chunked responses test
      - elaborate cache configuration

**Comment by krizhanovsky** [comment]
A stress test exhibiting #692 was missed from results of #780, so I add a requirement to the test: we need a stress test reliably exhibiting #692 on our testbed. Also, since the issue is crucial, I mark the test as crucial as well.
