### ISSUE TITLE
Crash with TLS traffic

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#767]
Configuration

        sched ratio;
        listen 443 proto=https;
        server 10.0.221.20:443 conns_n=32;
        server 10.0.221.148:443 conns_n=32;
        ssl_certificate /root/self-ssl.crt.pem;
        ssl_certificate_key /root/self-ssl.key;
        server_queue_size 1000;
        sticky_sessions allow_failover;
        cache 0;
        sticky enforce;
        sticky_secret "f00)9eR59*_/22";

Produces following crash, seems on very initial traffic:

        [ 2730.152028] BUG: unable to handle kernel NULL pointer dereference at 00000000000002f4
        [ 2730.153838] IP: [<ffffffffc0a55365>] tfw_http_msg_process+0x395/0x760 [tempesta_fw]
        [ 2730.155554] PGD 0 [ 2730.155878] 
        [ 2730.156587] Oops: 0000 [#1] SMP
        [ 2730.157545] Modules linked in: tfw_sched_ratio(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) tempesta_tls(O) sctp_diag sctp libcrc32c crc32c_generic dccp_diag dccp tcp_diag udp_diag inet_diag unix_diag af_packet_diag netlink_diag sb_edac edac_core crct10dif_pclmul crc32_pclmul ghash_clmulni_intel aesni_intel aes_x86_64 lrw gf128mul glue_helper ablk_helper cryptd ppdev parport_pc intel_rapl_perf input_leds led_class serio_raw battery pcspkr sg parport shpchp vmwgfx ttm drm_kms_helper drm fb_sys_fops syscopyarea sysfillrect ac button vmw_vmci sysimgblt ip_tables x_tables autofs4 ext4 crc16 jbd2 fscrypto mbcache sd_mod sr_mod cdrom ata_generic psmouse crc32c_intel mptspi scsi_transport_spi mptscsih e1000 mptbase ata_piix libata i2c_piix4 scsi_mod [last unloaded: tempesta_tls][ 2730.175246] CPU: 2 PID: 0 Comm: swapper/2 Tainted: G        W  O    4.9.35 #2
        [ 2730.177015] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 09/30/2014
        [ 2730.179960] task: ffff8fd8da0181c0 task.stack: ffffac12406a8000
        [ 2730.181545] RIP: 0010:[<ffffffffc0a55365>]  [<ffffffffc0a55365>] tfw_http_msg_process+0x395/0x760 [tempesta_fw]
        [ 2730.184508] RSP: 0018:ffff8fd8fb243a50  EFLAGS: 00010202
        [ 2730.186019] RAX: 0000000000000010 RBX: 0000000000000000 RCX: 0000000000000003
        [ 2730.187839] RDX: 0000000000000001 RSI: ffff8fd8d7c5d3c0 RDI: ffff8fd8d82b50f0
        [ 2730.189661] RBP: ffff8fd8d82b5040 R08: 0000000000000004 R09: 0000000000000045
        [ 2730.191487] R10: 0000000000000000 R11: 0000000000000001 R12: 000000000000004c
        [ 2730.193303] R13: ffff8fd8d7c5d020 R14: ffff8fd8d82b5040 R15: 0000000000000000
        [ 2730.195146] FS:  0000000000000000(0000) GS:ffff8fd8fb240000(0000) knlGS:0000000000000000
        [ 2730.197138] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
        [ 2730.198770] CR2: 00000000000002f4 CR3: 0000000118838000 CR4: 00000000001406e0
        [ 2730.200658] Stack:
        [ 2730.201656]  ffff8fd8d82b5058 ffff8fd8d82b50e0 ffffffffc0a824e0 0000000000000000
        [ 2730.203666]  ffff8fd8d7c5d3c0 0000000000000000 0000004cc958f8d4 ffff8fd8d81eb000
        [ 2730.205665]  00000000596e2985 000000001a132350 0000000000000101 563d53a9c958f8d4
        [ 2730.207664] Call Trace:
        [ 2730.208752]  <IRQ> [ 2730.209106]  [<ffffffffc0a51dd1>] ? __gfsm_fsm_exec+0x51/0x90 [tempesta_fw]
        [ 2730.210986]  [<ffffffffc0a51f43>] ? tfw_gfsm_move+0x133/0x160 [tempesta_fw]
        [ 2730.212864]  [<ffffffffc074a85c>] ? mbedtls_ssl_read+0x10c/0x550 [tempesta_tls]
        [ 2730.214786]  [<ffffffffc0a759ff>] ? tfw_tls_msg_process+0x10f/0x190 [tempesta_fw]
        [ 2730.216723]  [<ffffffffc0a51dd1>] ? __gfsm_fsm_exec+0x51/0x90 [tempesta_fw]
        [ 2730.218569]  [<ffffffffc0a6df98>] ? ss_tcp_process_data+0x188/0x3f0 [tempesta_fw]
        [ 2730.220497]  [<ffffffffc0a6e44e>] ? ss_tcp_data_ready+0x3e/0x80 [tempesta_fw]
        [ 2730.222382]  [<ffffffff98a897d0>] ? tcp_rcv_established+0x460/0x6b0
        [ 2730.224112]  [<ffffffff98a4bd08>] ? sk_filter_trim_cap+0x28/0x2b0
        [ 2730.225796]  [<ffffffff98a93b2e>] ? tcp_v4_do_rcv+0x12e/0x1f0
        [ 2730.227406]  [<ffffffff98a952cf>] ? tcp_v4_rcv+0x89f/0x9a0
        [ 2730.228963]  [<ffffffff98a6f714>] ? ip_local_deliver_finish+0x94/0x1c0
        [ 2730.230671]  [<ffffffff98a6f9d6>] ? ip_local_deliver+0x66/0xe0
        [ 2730.232251]  [<ffffffff98a94a1b>] ? tcp_v4_early_demux+0x12b/0x140
        [ 2730.233874]  [<ffffffff98a6f3fc>] ? ip_rcv_finish+0x16c/0x3f0
        [ 2730.235413]  [<ffffffff98a6fcd1>] ? ip_rcv+0x281/0x3d0
        [ 2730.236833]  [<ffffffff98a6f290>] ? inet_del_offload+0x30/0x30
        [ 2730.238352]  [<ffffffff98a330aa>] ? __netif_receive_skb_core+0x4aa/0x9b0
        [ 2730.240009]  [<ffffffff98a3458d>] ? process_backlog+0x7d/0x100
        [ 2730.241503]  [<ffffffff98a33d70>] ? net_rx_action+0x200/0x320
        [ 2730.242996]  [<ffffffff9865e863>] ? __do_softirq+0xf3/0x200
        [ 2730.244430]  [<ffffffff9865eab3>] ? irq_exit+0xa3/0xb0
        [ 2730.245779]  [<ffffffff98b288df>] ? call_function_single_interrupt+0x7f/0x90
        [ 2730.247438]  <EOI> [ 2730.247803]  [<ffffffff98b27242>] ? default_idle+0x2/0x10
        [ 2730.249220]  [<ffffffff9869515a>] ? cpu_startup_entry+0x1ba/0x220
        [ 2730.250734]  [<ffffffff98631608>] ? start_secondary+0x138/0x160
        [ 2730.252211] Code: 00 49 8d be b0 00 00 00 e8 09 24 0d d8 49 8b 86 a0 00 00 00 48 39 44 24 08 74 27 49 8b 86 a8 00 00 00 48 85 c0 0f 84 03 03 00 00 <8b> 88 e4 02 00 00 48 89 c2 f6 c5 08 74 10 80 e5 f7 89 88 e4 02 
        [ 2730.258528] RIP  [<ffffffffc0a55365>] tfw_http_msg_process+0x395/0x760 [tempesta_fw]
        [ 2730.260369]  RSP <ffff8fd8fb243a50>
        [ 2730.261483] CR2: 00000000000002f4
        [ 2730.263485] ---[ end trace dd550d394957eefa ]---
        [ 2730.264761] Kernel panic - not syncing: Fatal exception in interrupt

**Comment by keshonok** [comment]
Fixed via 6e47734.
