### ISSUE TITLE
run_tests.py requires dummy tests_config.ini

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#793]
As described in the [Wiki](https://github.com/tempesta-tech/tempesta/tree/master/tempesta_fw/t/functional#configuration) `./run_tests.py -d` generates default config file and it actually does so:

        $ touch tests_config.ini
        $ ./run_tests.py -d
        Default configuration saved to /root/tempesta.759/tempesta_fw/t/functional/helpers/../tests_config.ini

However, if there is no tests_config.ini, then the script is unable to generate it as well as to show help:

        $ rm tests_config.ini
        $ ./run_tests.py -d
        Tests configuration error! Configuration file "tests_config.ini" not found. Exiting.
        $ ./run_tests.py -h
        Tests configuration error! Configuration file "tests_config.ini" not found. Exiting.

**Comment by ikoveshnikov** [comment]
#783 introduces a better way to start only specified tests: `run_tests.py` becomes the entry point to run specified tests, so just disable configuration checking on module import: https://github.com/tempesta-tech/tempesta/blob/master/tempesta_fw/t/functional/helpers/tf_cfg.py#L109  It was needed to use testcase modules as stand-alone programs.
