### ISSUE TITLE
run_tests.py: negative selection + execution status persistence and/or "start from given test"

### ISSUE THREAD

**Issue by intelfx** [tempesta-tech/tempesta#795]
It would be nice for `run_tests.py` to support:

* negative selection (`./run_tests.py sessions -sessions.test_cookies`)
* persistence (`./run_tests.py` *[writes a status file]* ⇒ crash ⇒ `./run_tests.py --continue`)
* "start from given point" (`./run_tests.py --start-from flacky_net`)

**Comment by krizhanovsky** [comment]
As #794 occurred it has sense to skip the failing test_hash_scheduler, all tests for hash scheduler or even all tests for all schedulers, but there is no such opportunity. It's very inconvenient to account all available tests (BTW what's the best way to do this?) and point all of them out in the test command line. Need to develop all the types of the negative selection of tests.

**Comment by intelfx** [comment]
Follow-ups:

* accept filename-style testcase names (`./run_tests.py sessions/test_cookies.py`) to allow globs
* add a mode to list all matched tests without executing them (`./run_tests.py --list-only [ARGUMENTS...]`)
* accept directories (`./run_tests.py sessions`) — currently they are accepted, but actually skipped as empty modules (looks like sub-modules are not taken into account by unittest framework)
