### ISSUE TITLE
Incorrect restoring of responces from chunked cache entries

### ISSUE THREAD

**Issue by vankoven** [tempesta-tech/tempesta#803]
Applicable to saving and restoring responses from _chunked_ cache entry. There is a situation when `TfwCStr` header can't be fit into the rest of current data chunk (`TdbVRec`). In this case `TfwCStr` will be saved into the next record. This condition is handled in `tfw_cache_copy_hdr()`:
https://github.com/tempesta-tech/tempesta/blob/65d9723b22b208c3d8428faed2dd5ac229c3ec33/tempesta_fw/cache.c#L686

The `tfw_cache_copy_hdr()` has also an optimization in order not to split short `TfwCStr`:
https://github.com/tempesta-tech/tempesta/blob/65d9723b22b208c3d8428faed2dd5ac229c3ec33/tempesta_fw/cache.c#L675-L678

But there is a couple of issues, when restoring responses from a cache entry. First of all optimization above is ignored. So if a response is written to cache with at least one such optimisation we can expect crash or serving corrupted response.

Secondly, crash will happen in `tfw_cache_build_resp_hdr()` if `TfwCstr` of the next header couldn't fit the rest of the current chunk and was placed into the next one:
https://github.com/tempesta-tech/tempesta/blob/65d9723b22b208c3d8428faed2dd5ac229c3ec33/tempesta_fw/cache.c#L1019-L1020

To fix both issues we need to add a function to adjust current pointer in the current data chunk before reading `TfwCStr` similarly to `tdb_entry_get_room()` which is used before writing. And use the function any time we are reading a  `TfwCStr`. To make function aware of optimization above, we need to write a _padding_ `TfwCStr` header with flag `SKIP_REC_TAIL` set every time when the optimization is used. The flag will help us understand that the rest of data chunk doesn't contain any data and must be skipped. `tdb_entry_get_room()` must write this padding `TfwCStr`  header.

**Comment by krizhanovsky** [comment]
It's better to fix this after #516 (TDBv2) which will affect caching a lot.

**Comment by const-t** [comment]
Fixed by #1831
