### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#81]
Must be implemented TLS support on top of latest stable release of [libressl](http://www.libressl.org/) ported to Linux kernel.

**Comment by stefanstrogin** [comment]
Here are results of benchmarks of mbed tls, wolfssl and libressl.
1. ssl_read() execution time and speed of data decoding.
https://docs.google.com/spreadsheets/d/1Gg04OLxRSgYL0Y2vwqf4CHpNc8Q_lkKf_P7OnRWPYfI/edit
(unfortunately in case of libressl ssl_read decodes faster than we can read data from the socket).
2. ssl connection time:
https://docs.google.com/spreadsheets/d/1SvSjL2OiqbTEZeqTSzbcXylFC8dHwl0lO6bE95VSVjw/edit

Modificated libressl's s_client is used to connect to stud and send 16 MB of random (from /dev/urandom) data at a time (in the 1st test). Stud doesn't resend the received data neither processes it anyhow just reading it to a buffer.

**Comment by krizhanovsky** [comment]
Since the difference is too large between the results, it seems the benchmarks require more observations. Probably there are communication issues (actually there are and we saw some of them) and generation of crypto-context on negotiation phase.

Also there are some [licensing issues](https://people.gnome.org/~markmc/openssl-and-the-gpl.html) and generally speaking OpenSSL (and LibreSSL corespondingly) is GPL incompatible.

**Comment by stefanstrogin** [comment]
The same graphs with logarithmic scale.
1. ![ssl_read-log](https://cloud.githubusercontent.com/assets/10670399/9150600/77681718-3dea-11e5-85da-5d26b2492ea3.png)
2. ![ssl_connect-log](https://cloud.githubusercontent.com/assets/10670399/9150601/7982af2c-3dea-11e5-8870-c875811dbe94.png)

**Comment by krizhanovsky** [comment]
A simple benchmark, probably based on [Stud](https://github.com/bumptech/stud), on top of tempesta/ktest framework must be implemented to compare performance of the resulting implementation against LibreSSL, GnuTLS and wolfSSL.

**Comment by krizhanovsky** [comment]
[SSL session caching](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslsessioncache) should be implemented using TDB to replicate sessions to other nodes for full connections failovering.

**Comment by krizhanovsky** [comment]
Consider GPU usage (e.g. [kgpu](https://github.com/wbsun/kgpu)) for acceleration like [SSLShader](http://shader.kaist.edu/sslshader/).

**Comment by krizhanovsky** [comment]
[Ideal HTTP Performance](https://www.mnot.net/blog/2016/04/22/ideal-http) refers [TLS 1.3](https://tlswg.github.io/tls13-spec/) and [Cache Digests](http://mnot.github.io/I-D/h2-cache-digest/) for better performance. Consider this still uncommitted standards to update the implementation.

**Comment by krizhanovsky** [comment]
High-Tech Bridge provides [free SSL Server Test](https://www.htbridge.com/ssl/), so we can use it for initial test of the implementation.

**Comment by milabs** [comment]
mbedTLS was updated to 2.3.0 (80e6d70619215017ebc2d10c942c8ce01c3fb12d)

**Comment by milabs** [comment]
After merging TLS implementation (92c51182d6fc6d372b714ca98ae96638e03878b2) me and @keshonok run [Free SSL Server Test](https://www.htbridge.com/ssl/?id=cdbe28c2b0e2fc80cb067b53bcde44bede6ce281dc5fa170fe331af5325d7347) collecting debugging information via [dmesg](https://github.com/tempesta-tech/tempesta/files/439922/tls-test.log.gz).

Analyzing kernel's log for TLS errors shows us the following:

~~~
$ grep mbedtls tls-test.log | grep returned | cut -d' ' -f 9 | sort | uniq -c
      6 (-0x7180)
    255 (-0x7280)
      1 (-0x7780)
     65 (-0x7880)

/* Verification of the message MAC failed. */
#define MBEDTLS_ERR_SSL_INVALID_MAC                 -0x7180
/* The connection indicated an EOF. */
#define MBEDTLS_ERR_SSL_CONN_EOF                    -0x7280
/* A fatal alert message was received from our peer. */
#define MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE         -0x7780
/*The peer notified us that the connection is going to be closed. */
#define MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY           -0x7880
~~~

~~~
$ grep TLS tls-test.log | grep ERROR | awk '{print $NF}' | sort | uniq -c
     22 (6980)
     14 (6e80)
      4 (7180)
     81 (7380)
     13 (7900)
      5 (7c00)

/* None of the common ciphersuites is usable. */
#define MBEDTLS_ERR_SSL_NO_USABLE_CIPHERSUITE       -0x6980
/* Handshake protocol not within min/max boundaries */
#define MBEDTLS_ERR_SSL_BAD_HS_PROTOCOL_VERSION     -0x6E80
/* Verification of the message MAC failed. */
#define MBEDTLS_ERR_SSL_INVALID_MAC                 -0x7180
/* The server has no ciphersuites in common with the client. */
#define MBEDTLS_ERR_SSL_NO_CIPHER_CHOSEN            -0x7380
/* Processing of the ClientHello handshake message failed. */
#define MBEDTLS_ERR_SSL_BAD_HS_CLIENT_HELLO         -0x7900
/* Processing of the ClientKeyExchange handshake message failed. */
#define MBEDTLS_ERR_SSL_BAD_HS_CLIENT_KEY_EXCHANGE  -0x7C00
~~~

In my opinion, everything looks good, in spite of these errors.

**Comment by krizhanovsky** [comment]
Basic TLS support is implemented, move performance optimization tasks to 0.6 as #614.
