### ISSUE TITLE
Miscellaneous functional/regression tests

### ISSUE THREAD

**Issue by intelfx** [tempesta-tech/tempesta#822]
We need a set of functional tests that expose Tempesta to (simple) invalid requests/responses:

- [ ] malformed well-known headers
- [ ] malformed request/response structure (missing lines, duplicate lines)
- [x] mismatching data/metadata (content length; non-empty body when no body is expected; ...)

General functionality tests:
- [ ] request pipelining
  - [ ] functional tests (check ordering):
    - [ ] common case (w/ and w/o failovering)
    - [ ] failure mode (single server w/failovering so that a 502 response is built)
    - [ ] failure mode w/fault injection
  - [x] stress tests
    - [x] common case (#845)
    - [x] failure mode (#845)

**Comment by ikoveshnikov** [comment]
In recent #824 a crash covered by `regression.test_invalid.TestInvalidResponse.test_no_crlf_before_body()` test was fixed. Please update expected TempestaFW response and remove `expectedFailure` decorator.

**Comment by vladtcvs** [comment]
During discussion we found out, that we need a set of unit tests for http header parsers

https://github.com/tempesta-tech/tempesta/issues/1059
