### ISSUE TITLE
Functional tests for locations

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#823]
Please develop following functional tests for [locations](https://github.com/tempesta-tech/tempesta/wiki/Virtual-hosts-and-locations): ensure that different resources are serviced in different ways depending on location (e.g. one resource is processed by cache, while another is directly passed to a backend). Check [all the available options](https://github.com/tempesta-tech/tempesta/blob/master/tempesta_fw/vhost.c#L1004) to be nested into the section, such as `nonidemptotent` and `cache_fulfill`.

**Comment by nickzaev** [comment]
Done in https://github.com/tempesta-tech/tempesta-test/commit/24ca5a972cf3e8cd5199a684eff66f2ba2d3d662
