### ISSUE TITLE
cfg: double server list specification

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#84]
From #78 

Backend connections are managed by Tempesta FW, but groups of servers are managed by the tfw_sched_http. Hence, a system administrator has to duplicate each backend entry in the configuration file when he uses the tfw_sched_http (see tfw_sched_http.conf).

Poor design. Must be fixed.

**Comment by krizhanovsky** [comment]
With #495 and #471 in mind the issue is more crucial to fix in this release. Actually `server` configuration option isn't needed: `sock_srv.c` parses `srv_group` configuration option and can manage connections with parsed out server entities.

**Comment by keshonok** [comment]
It's no longer required to specify servers outside any groups just to be able to specify them later inside groups. Thus there's no duplication now,

**Comment by krizhanovsky** [comment]
Just checked that following configuration works just fine:

        srv_group static sched=hash {
	        server 127.0.0.1:8080;
        }
        
        srv_group dynamic {
        	server 127.0.0.1:9090;
        }
        
        sched_http_rules {
        	match	static	uri	eq	"/";
        	match	dynamic	*	*	*;
        }
