### ISSUE TITLE
Frang: wrong handle of errors during init.

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#842]
The error is in https://github.com/tempesta-tech/tempesta/blob/e88059d183bb45d63ed62351a83923c0a8038aaa/tempesta_fw/classifier/frang.c#L1118

The function returns non-null `r` on errors. But if error happens during one of `tfw_gfsm_register_hook()` calls, `r` equals to `0`, so the `frang_init()` function returns successful error code (`0`).

**Comment by krizhanovsky** [comment]
Yeah, this is known issue: GFSM is unable to unregister its hooks, linked with #838.
