### ISSUE TITLE
Whitelisting from nftables

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#844]
Frang and especially sticky cookies modules may significantly impact user experience and the site availability for search engines, so we need a whitelist for IP addresses which should not be impacted by Frang and sticky cookies. Bot the modules must introduce a new options to bypass traffic with specified label. 

The new configuration option must be defined as

        whilelist_mark <mark>

, where <mark> is an integer value set in `skb->mark` by [nftables](https://wiki.nftables.org/wiki-nftables/index.php/Setting_packet_metainformation).

Please create an issue for appropriate functional test (for the next milestone) and add corresponding description to https://github.com/tempesta-tech/tempesta/wiki/Handling-clients

**Comment by aleksostapenko** [comment]
Wiki has been updated and issue for functional test has been created: https://github.com/tempesta-tech/tempesta/issues/917.
