### ISSUE TITLE
Defensive programming in functional tests

### ISSUE THREAD

**Issue by intelfx** [tempesta-tech/tempesta#846]
This is something I overlooked when I was cleaning up the functional test suite. Our tests' cleanup routines abort on the first error met, possibly leaving the node in a dirty state (i. e. modules still loaded, nginx still running etc.).

This must be fixed in a general manner — e. g. catch all external exceptions and have a special `error.bug()` that logs the error but does not raise an exception.

**Comment by vladtcvs** [comment]
Some code refactoring requred: Now we use tearDown() not only for stopping Tempesta and Nginx after test, but also for stopping some garbage instances of them, leaved after previous tests, if they were interruped. This is not good. We need to separate this tasks
