### ISSUE TITLE
http_match for Referer header

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#853]
Several DDoS attacks can be mitigated by filtering `Referer` HTTP header, so need to add the header to list of Special headers and make sure that it's quickly processed by `http_match`.

Update Wiki for DDoS use cases. Also please create a task for appropriate test for the next milestone.

**Comment by krizhanovsky** [comment]
@aleksostapenko you didn't update neither https://github.com/tempesta-tech/tempesta/wiki/Scheduling-and-Load-Balancing#http-scheduler-for-server-groups nor https://github.com/tempesta-tech/tempesta/wiki/DDoS-mitigation#iframes-on-a-busy-site . Close the issue after the Wiki updates.

**Comment by aleksostapenko** [comment]
Wiki updated.
