### ISSUE TITLE
[Func tests] Check required binaries before runnng tests

### ISSUE THREAD

**Issue by ikoveshnikov** [tempesta-tech/tempesta#857]
As functional tests becoming more complicated and complete they require more and more external tools. Functional tests suite must check all the required tools before start to prevent false tests failures. Some required tools are not documented in readme for functional tests, e.g. curl and systemtap.

**Comment by krizhanovsky** [comment]
Guys, it seems the testing system becomes quite large and complex. What about to move it to separate repository? @intelfx , @ikoveshnikov any opinions?

**Comment by intelfx** [comment]
That's gonna introduce some pretty complex problems with correlating revisions of code and tests. I intended to test (at least smoke-test) every incoming revision (not just the latest of each PR), and this will make it impossible.

**Comment by ikoveshnikov** [comment]
I think, that the question depends on CI only. There is no strong dependencies between the code and the functional tests. I know only one dependency - Tempesta's version string, since it's evaluated during parsing of Tempesta's replies.

The functional tests are not aware about implementation  at all. If a test passes on one revision of Tempesta and fails on the other, that means that the tested feature is broken or not implemented on the latter one. You just can't break functional tests by changing the Tempesta's code.

But there is a problem, that you can't say that the test itself is error-free, until the feature is fully implemented (or a bug is fixed). So yes, there is some correlating issue.

It's usual approach to separate functional tests from the code. I'm for the separation, but as i said it depends on CI system.

**Comment by krizhanovsky** [comment]
Guys, we  can require, somewhere in installation docs, that the test repository/directory must reside in the same directory with tempest source code and built module, so technically tests just move few directories up.

**Comment by vladtcvs** [comment]
https://github.com/tempesta-tech/tempesta-test/pull/30

**Comment by vladtcvs** [comment]
Fixed in tests PR#30
