### ISSUE TITLE
DSL for test scenarios

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#878]
The task is motivated by https://github.com/tempesta-tech/tempesta/pull/851#discussion_r159002053 : each functional test must be developed in Python, in imperative way. It'd be much more efficient to develop tests in special purpose domain specific language (DSL), e.g. MariaDB [test suite](https://github.com/tempesta-tech/mariadb/tree/trunk/mysql-test) uses SQL-based shell-like language for the tests. The test are much more readable and can be quickly analysed for which scenarios are implemented.

Since the test system is in-house infrastructure project with different development & release flow, it has sense to consider it to move into separate project.

**Comment by krizhanovsky** [comment]
The issue was originally in 0.8 milestone, however in 0.5 we faced significant setbacks in the tests development: many issues required significant changes in the kernel of the test suite. So the issue becomes crucial and first to do in 0.6 to arrange the test development process.

**Comment by ikoveshnikov** [comment]
Need to create backend configuration capable to serve different types of resources:
- small files, around ten or hundred bytes, making several responses to fit single skb
- large files, which won't fit single skb
- successful post requests (not just overriding response code, but full featured response)
- failed post requests

**Comment by ikoveshnikov** [comment]
All tests creates only one TfwClient, since only one source IP is used, many TfwClients are required for Frang tests

**Comment by krizhanovsky** [comment]
Probably the most simple way to emulate many source IP addresses is to rewrite the addresses on ingress and egress directions by iptables. Mangling packets in both the directions is required to keep TCP sessions. You can generate the rules on the fly, e.g. by some hash on source port.

**Comment by krizhanovsky** [comment]
Probably the most simple way to emulate many source IP addresses is to rewrite the addresses on ingress and egress directions by iptables. Mangling packets in both the directions is required to keep TCP sessions. You can generate the rules on the fly, e.g. by some hash on source port.

**Comment by krizhanovsky** [comment]
Minutes from today call:

1. configuration templates must be explicitly defied in test .py files as a variables or members of a dictionary. Global test definitions (e.g. IP addresses, directories etc) must be handled using standard template engine (e.g. Template).
2. The template arguments must be used to define 'workstation' or 'CI' workload. E.g. (I took syntax from http://search.cpan.org/~samtregar/HTML-Template-Expr/Expr.pm)
```
keepalive_requests <TMPL_VAR EXPR="100 * keepalive_requests_mul">
```
3.  High level test abstractions, such as `testers/functional` are removed and only low level abstractions such as `deproxt`, `wrk` wrappers and tempesta on Nginx start/stop handlers are implemented as test library API.

So the new tests are implemented as separate Python files of following structure:
1. define configuration for Tempesta, backend server and probably content of its document root directory;
2. API call to start tempesta and Nginx with specified configuration (configuration is passed to the routines as plain text and can be written to files internally)
3. API call to generate load, e.g. deproxy call or wrk wrapper call
4. API or local function/object definition for custom logic such as SystemTap injections or TCP analyzer
5. API call to get results
6. API call to shutdown Tempesta and backend server

The new test suite is going to be implemented in https://github.com/tempesta-tech/tempesta-test . We're going to live for some time with both the testing suites until we finally move to the new suite.

**Comment by vladtcvs** [comment]
https://github.com/tempesta-tech/tempesta-test/pull/5
