### ISSUE TITLE
WebSocket test

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#881]
Need to develop a functional test for Tempesta FW websockets (#755). Python [websockets](https://websockets.readthedocs.io/en/stable/index.html) can be used for both the client and server sides. However, it seems all Python websockets libraries (also [websocket-client](https://pypi.org/project/websocket-client/)) depend on Python 3, so the issue is blocked by [migration of our testing framework to Python3](https://github.com/tempesta-tech/tempesta-test/issues/56).

Following tests for HTTP/1 ~and HTTP/2~ client must be done (**UPD** it seems the modern HTTP/2 applications [prefer SSE over WebSockets](https://www.mnot.net/blog/2022/02/20/websockets), so it's hard to find an HTTP/2 WebSocket client):
- [x] ping pong over ws:// (for HTTP/1 only)
- [x] ping pong over wss:// (client - tfw - backend)
- [x] ping pong over wss:// (client - tfw - proxy - backend, see at the below)
- [x] ~HTTP tables rules to [load balance websockets](https://www.haproxy.com/blog/websockets-load-balancing-with-haproxy/) traffic by `Host` or `Connection: upgrade` headers~ We have other HTTPtable tests and it seems there is nothing special about websockets
- [x] cache: check that we never cache 101 responses with `Upgrade` header. Error responses for invalid client upgrade requests still can be cached
- [x] (stress test) establish many wss connections against several server groups using all current connections schedulers, cause severe load and do several Tempesta restarts during the workload
- [x] ~(scheduler stress test) we have stress tests for the schedulers, at least https://github.com/tempesta-tech/tempesta-test/blob/master/sched/test_hash_stress.py , so we need a similar tests for this and other schedulers to make sure that we can normally create a websocket under high scheduler load~ The test case seems covered by the previous test.

### wss://

Tempesta FW doesn't have client side TLS (#769 ) yet. However, websockets have nothing about TLS and just use the same upgrade scheme for both ws:// and wss:// . In the default scheme a client connects Tempesta on HTTPS and Tempesta has plain HTTP connection to the backend, which leads to wss:// between the client and Tempesta and ws:// between Tempesta and the backend server.

One wishing to have wss:// to the backend should use an additional HTTPS server, e.g. Nginx or HAproxy, supporting client side TLS. Tempesta FW config must specify the server (typically running on the same host with Tempesta FW) as the backend server.
```
                       +---------------------------+
+--------+   wss://    |              ws://        |  wss://   +----------------+
| client | ----------> | Tempesta FW  -----> proxy | --------> | origin backend |
+--------+             |                           |           +----------------+
                       |     [one physical host]   |
                       +---------------------------+
```

**Comment by ttaym** [comment]
It seams that there are not so many http/2 websocket clients. Only modern browsers are prominent wide-spread clients. For example:

```
<!DOCTYPE HTML>

<html>
   <head>
      <script type = "text/javascript">
         function WebSocketOpen() {
            if ("WebSocket" in window) {
               var ws = new WebSocket("wss://ru.ayum.ru/url");
               ws.onopen = function() {
                  console.log('ws opened')
               };

               ws.onmessage = function (evt) {
                  var received_msg = evt.data;
                  console.log('ws msg: ' + received_msg)
               };

               ws.onclose = function() {
                  console.log('ws close')
               };

               window.ws = ws
            } else {
               alert("WebSocket NOT supported by your Browser!");
            }
         }
         function WebSocketSend() {
            window.ws.send("msg");
         }
      </script>
   </head>

   <body>
      <div id = "sse">
         <a href = "javascript:WebSocketOpen()">Open WebSocket</a>
         <a href = "javascript:WebSocketSend()">Send message to WebSocket</a>
      </div>
   </body>
</html>
```
