### ISSUE TITLE
Functional test for HTTP tables

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#883]
Need a test for HTTP tables. 

One special case must be covered by the test. HTTP tables (#731) make possible to load balance traffic just using `mark`. So test a scenario of several, say 10, server groups and distribute traffic among them by value of `mark` (from 1 to 10 for example).

**Comment by aleksostapenko** [comment]
Resolved in https://github.com/tempesta-tech/tempesta-test/pull/22.
