### ISSUE TITLE
Debug with tagged priority

### ISSUE THREAD

**Issue by vladtcvs** [tempesta-tech/tempesta#915]
Now we are using simple number (1, 2, 3, etc) for debug levels in tests. It is not good, because when we need to debug some part of code, log is flooded with debug messages from other parts of code. There is a solution: add tag to debug message. And when we debug, we specify show debug messages up to the some level of priority and for specified tag up to the other level of priority

**Comment by krizhanovsky** [comment]
We have now `DBG_CFG`, `DBG_HTTP_PARSER` and so on in `tempesta/Makefile`.
