### ISSUE TITLE
Test for white/black-listing functionality

### ISSUE THREAD

**Issue by aleksostapenko** [tempesta-tech/tempesta#917]
According to https://github.com/tempesta-tech/tempesta/issues/844, functional test for checking requests whitelisting is needed. Test should verify following scenario:
1. Set some mark for particular type of incoming network packets (via `nftables` interface)
1. Configure whitelisting with corresponding mark in Tempesta via directive `whilelist_mark <mark>`
1. Enable Frang and Sticky cookie (with `enforce` option) modules in Tempesta configuration
1. Check that requests of specified in p.1 type are not filtered out via Frang and not answered with 302 response

**Comment by krizhanovsky** [comment]
Need to test that whitelisted IPs (https://github.com/tempesta-tech/tempesta/wiki/Handling-clients#whitelist-marks) aren't
1. challenged by JS challenge
2. filtered by Frang rules

but all other IPs are still filtered by both the modules

**Comment by krizhanovsky** [comment]
We had a request for the feature and probably there is a bug: `whitelist_mark 1;` and `iptables -t mangle -A PREROUTING -p tcp -s 192.168.1.23 -j MARK --set-mark 1` still don't pass frang:

```
[ 4995.577824] [tempesta fw] Warning: frang: new connections rate exceeded for 192.168.1.23: 51 (lim=50)
[ 4995.579500] [tempesta fw] Warning: frang: new connections rate exceeded for 192.168.1.23: 52 (lim=50)
[ 4995.581117] [tempesta fw] Warning: frang: new connections rate exceeded for 192.168.1.23: 53 (lim=50)
[ 4995.582041] [tempesta fw] Warning: frang: new connections rate exceeded for 192.168.1.23: 54 (lim=50)
[ 4995.583662] [tempesta fw] Warning: frang: new connections rate exceeded for 192.168.1.23: 55 (lim=50)
[ 4995.585283] [tempesta fw] Warning: frang: new connections rate exceeded for 192.168.1.23: 56 (lim=50)
[ 4995.586903] [tempesta fw] Warning: frang: new connections rate exceeded for 192.168.1.23: 57 (lim=50)
[ 4995.588518] [tempesta fw] Warning: frang: new connections rate exceeded for 192.168.1.23: 58 (lim=50)
```
