### ISSUE TITLE
Dead loop in tfw_sg_wait_release()

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#959]
Test
```
test (mixed_requests.test_mixed.GetPostRequests) ... FAIL
```
causes dead loop with
```
[ 1926.684030] [tempesta] Warning: pending for server callbacks to complete for 5s, 1 server groups still exist
[ 1931.688017] [tempesta] Warning: pending for server callbacks to complete for 5s, 1 server groups still exist
[ 1936.692039] [tempesta] Warning: pending for server callbacks to complete for 5s, 1 server groups still exist
...
```

The reason for the leaving server group must be fixed. Also, it really has sense to crash instead of infinitely wait.

**Comment by ikoveshnikov** [comment]
Then a response is received, corresponding request is removed from servers's forward queue. If the request is not the first one in client's `seq_queue`, it won't be forwarded to the client right away.
When the client disconnects, `tfw_http_conn_cli_drop()` is called, but requests-responses pairs are not freed. That is the reason, why server connections are not restored after closing by backend servers and not destroyed on shutdown.
